// Frases del grupo «origen». Cada hueco: 5 filas (épica 0..4) × 3 columnas (drama 0..2).
(function (g) {
  'use strict';
  const F = g.SIM.frases;

  // ── Nacimiento y cuna ─────────────────────────────────────────────────────────────────────────────
  F('nace', [
    ['Nació en {lugar} el año {anio}.', 'Nacimiento: {lugar}, año {anio}. Año de racionamiento.', 'Nacimiento: {lugar}, año {anio}. Año de muertos.'],
    ['La primera jornada de su vida fue en {lugar}, el año {anio}, un día como cualquier otro, sin presagios.', 'Llegó al mundo en {lugar} el año {anio}, cuando los depósitos de grano ya estaban casi vacíos.', 'Nació en {lugar} en {anio}, un año de sirenas y cuarentenas del que casi nadie quiso acordarse después.'],
    ['Vino al mundo en {lugar} el año {anio}, en un turno de noche, mientras las luces de los muelles se apagaban una a una.', 'El año {anio} nació en {lugar}, entre recortes de ración y vecinos que contaban en voz baja lo que quedaba en las despensas.', 'Su primer llanto se perdió entre alarmas y pasos apresurados en {lugar}, el año {anio}.'],
    ['Consta en los registros de {lugar} que en el año {anio} nació quien más tarde sería recordad{o|a} por los suyos y por los ajenos.', 'Los libros de {lugar} anotan, en el año {anio}, un nacimiento más en tiempos de penuria; nadie sospechó lo que daría de sí {el niño|la niña}.', 'Nació en {lugar} el año {anio}, entre humo y luto; la sangre ya corría por las calles antes de que {él|ella} aprendiera a andar.'],
    ['Cuentan que en {lugar}, el año {anio}, nació alguien a quien los muelles aprenderían a nombrar, y que esa noche los reactores zumbaron más hondo sin que nadie supiera decir por qué.', 'Nació en {lugar} el año {anio}, cuando el grano escaseaba, y su primer llanto sonó a aviso: nada vendría sin precio.', 'El año {anio}, cuando la ceniza aún cubría los muelles de {lugar}, nació {el niño|la niña} de quien hablarían las lápidas; no lloró, como si ya conociera el precio.'],
  ]);

  F('nace_padres', [
    ['Hij{o|a} de {padre} y de {madre}.', 'Hij{o|a} de {padre} y {madre}, casa de voces altas.', 'Hij{o|a} de {padre} y {madre}; los perdió pronto.'],
    ['Sus padres fueron {padre} y {madre}, gente de la que {él|ella} habló siempre con cariño.', 'Tuvo por padres a {padre} y a {madre}, y creció entre voluntades que casi nunca coincidían.', 'Fue hij{o|a} de {padre} y de {madre}, a quienes la vida le arrebató antes de que pudiera conocerlos bien.'],
    ['Sus padres, {padre} y {madre}, le dejaron una infancia de sobremesas largas y de historias contadas bajo la luz tenue del turno de noche.', 'De {padre} heredó la terquedad y de {madre} el silencio; entre ambos le armaron una infancia tirante, de puertas cerradas.', 'Perdió demasiado pronto a {padre} y a {madre}; de ellos solo quedaron un nombre repetido en voz baja y un colgante de aleación gastada.'],
    ['Los registros dejan constancia de su filiación: hij{o|a} de {padre} y de {madre}, vecinos de buena fama y de mesa abierta.', 'Fue hij{o|a} de {padre} y de {madre}, una pareja cuyas disputas conocía todo el puerto y que curtió su carácter a base de reproches.', 'La crónica consigna que {padre} y {madre} murieron pronto, y que de esa orfandad salió buena parte de lo que {él|ella} llegó a ser.'],
    ['Corría por {él|ella} la sangre de {padre} y de {madre}, que en los muelles tenían fama de haber soñado con alguien capaz de mirar más lejos que las luces del puerto.', 'Entre {padre} y {madre} la discordia ardió sin tregua, y de esa lumbre mala se forjó el alma de su hij{o|a}, dura como el acero que se enfría en aceite negro.', 'Fue hij{o|a} de {padre} y de {madre}, y la fatalidad se los llevó sin pedir permiso: quedó {el huérfano|la huérfana} con nombres que honrar y ninguna casa.'],
  ]);

  F('nace_sin_padres', [
    ['Padres desconocidos.', 'Padres desconocidos; nadie quiso decir más.', 'Padres desconocidos. Recogid{o|a} junto a un muelle.'],
    ['Nunca supo quiénes fueron sus padres, y aprendió a vivir sin preguntarlo.', 'De sus padres no quedó ni un nombre; esa falta le escocía cada vez que alguien presumía de linaje.', 'Sus padres se perdieron sin dejar rastro en ningún registro, y esa ausencia fue la primera herida.'],
    ['Su origen se disolvía en una niebla de registros extraviados: nadie guardaba el nombre de quienes le dieron la vida, y a {él|ella} le bastó con el apellido que le pusieron en el muelle.', 'Nadie en el puerto supo decir de quién era hij{o|a}; los rumores le llegaban por detrás y se le clavaban como esquirlas.', 'Apareció en el mundo sin padres que l{o|a} reclamaran: una cuna de embalaje, una manta térmica y ni una palabra de quien la dejó junto a la esclusa.'],
    ['Los archivos callan sobre su filiación: ningún padre firmó por {él|ella}, ninguna madre reclamó su nombre, y la historia hubo de empezar donde empezó, sin antecedentes.', 'Su ascendencia es un vacío que los cronistas rellenaron con conjeturas; {él|ella} lo supo y, según los testigos, jamás desmintió ninguna.', 'Se perdió el rastro de quienes l{o|a} engendraron: tragados por el olvido o por algo peor, dejaron una herida que no cerró hasta el final.'],
    ['Nadie supo de qué sangre venía; se contaba que había salido del muelle mismo, como sale la escarcha en el casco de una nave, sin padre ni nombre que anunciara su llegada.', 'Sin padres a quienes invocar, hizo de esa carencia su único blasón; y quien preguntaba por su cuna recibía una mirada que se quedaba grabada.', 'Hij{o|a} de nadie, dijeron, de la noche y del vacío: sus padres se deshicieron en el olvido como ceniza en la esclusa, y {él|ella} caminó con esa orfandad a cuestas hasta el último día.'],
  ]);

  F('cuna_humilde', [
    ['Creció con lo justo.', 'Creció con lo justo y viendo a otros con más.', 'Creció con hambre; vecinos murieron de ello.'],
    ['Su infancia transcurrió en una casa de pasillos estrechos, donde todo se aprovechaba y nada sobraba, y no la recordó nunca como una carencia.', 'Nació en la parte del puerto donde el agua caliente llegaba por turnos, y aprendió pronto a medir lo que le faltaba frente a lo que otros tiraban.', 'Se crió entre raciones menguantes y puertas que nadie abría; el frío de las cubiertas bajas le enseñó lo que cuesta un día más.'],
    ['De niñ{o|a} jugó con tornillos y arandelas que otros dejaban por inservibles, y en esa pobreza limpia aprendió a ver el valor de una pieza, de una hora, de un plato caliente.', 'Creció en un cuarto compartido, con los avisos de cobro siempre pegados a la puerta, y de aquella estrechez sacó una dureza que ni los años ablandaron.', 'Su infancia fue de cubiertas heladas y cenas de sobras; vio apagarse a vecinos por falta de medicina y de pan, y supo muy temprano que la miseria también mata.'],
    ['Vino de los barrios bajos del puerto, de donde salía la gente que movía la carga y apagaba los fuegos; la crónica anota que su origen fue modesto y que {él|ella} no lo ocultó jamás.', 'Cuna pobre, estómago vacío, memoria larga: así se cuenta su principio, y de aquella penuria salió un resentimiento que luego movió montañas de papel y de acero.', 'Nació y creció en el fondo de la miseria, donde los fríos se cobraban niños y los depósitos de grano se vaciaban antes que las súplicas: así quedó señalad{o|a} para siempre.'],
    ['Salió de la fragua de la pobreza, de donde salen los metales que no se doblan: sin herencia, sin techo propio, con las manos vacías y el nombre por estrenar.', 'La miseria fue su cuna y su primera maestra; en ella aprendió el sabor del rencor y del pan duro, y el mundo habría de pagarle esa escuela con intereses.', 'Creció donde el hambre pasa lista cada madrugada y se lleva a los más débiles; sobrevivió {él|ella}, y de entre los que quedaron nadie olvidó el silencio de aquellas cubiertas.'],
  ]);

  F('cuna_rica', [
    ['Creció con holgura.', 'Creció con holgura y con cuentas que rendir.', 'Creció con holgura; la desgracia llegó a la casa.'],
    ['Nació en una casa de mesa abundante y pasillos tranquilos, donde el dinero estaba en todas partes y casi nadie hablaba de él.', 'Se crió entre sedas de contrabando y deudores a la puerta, y supo pronto que cada comodidad tenía su precio y su acreedor.', 'Creció rodead{o|a} de lujos que ocultaban una casa podrida: la herencia sostenía a unos y aplastaba a otros, y {él|ella} vio de cerca ambas cosas.'],
    ['De niñ{o|a} corrió por salones con suelos de madera traída de otro mundo, y tuvo a mano más libros, más maestros y más tiempo del que nadie le pidió merecer.', 'La opulencia de su casa tenía un revés: cenas con invitados que sonreían de más, tutores que medían cada gesto y una herencia que olía a obligación.', 'Nació entre vajillas de plata y ventanales sobre el muelle, pero la fortuna de su casa acabó en pleitos y sangre, y aprendió que el oro no compra el sueño.'],
    ['Su cuna fue de las más altas del puerto: casa mercante de largo apellido, con sellos en los contratos y criados en las escaleras; la crónica deja claro que nunca conoció la necesidad.', 'Nació en la opulencia de una casa que mandaba más de lo que parecía; las rivalidades de familia fueron su primera escuela, y el lujo, su primera trampa.', 'Nació en una casa de libros de cuentas y de sombras, donde el oro llamaba a la envidia y la envidia acababa, tarde o temprano, en cuchillo.'],
    ['Nació en lo más alto de la casa mercante, bajo lámparas que nunca se apagaban, y el mundo entero parecía haber sido dispuesto para {él|ella} antes de que abriera los ojos.', 'Creció tras un muro de abundancia que otros habrían envidiado y que {él|ella} sintió como cerrojo: nada le faltaba y nada era suyo, y esa jaula fue el primer enemigo al que hubo de vencer.', 'Las arcas de su casa habrían comprado una flota y no compraron ni un aplazamiento del destino: la riqueza que la cuna le dio atrajo después a quienes esperaban verla caer.'],
  ]);

  // ── Retratos de carácter ──────────────────────────────────────────────────────────────────────────
  F('rasgo_codicia_alta', [
    ['Guardaba cada moneda y quería más.', 'Contaba lo ajeno y nunca daba por bastante lo propio.', 'Por dinero perdió amistades y salud.'],
    ['Llevaba las cuentas de todo, desde el precio del grano hasta el de un favor, y no soltaba una moneda sin saber cuánto volvería con intereses.', 'Regateaba hasta el último céntimo con estibadores y socios, y cuando la mesa terminaba tenía más, pero ni así quedaba satisfech{o|a}.', 'La sed de ganar l{o|a} consumió: por un cargamento firmó contratos que sabía envenenados, y los muertos de las bodegas le pesaron menos que las pérdidas.'],
    ['Tenía el olfato de las casas mercantes: le bastaba ver cómo estibaban un contenedor para calcular su valor, y los ojos se le encendían, discretos, ante todo lo que pudiera tener precio.', 'Mirar sus manos era mirar la contabilidad de una vida: siempre llenas, siempre cerradas, y en la mirada un hambre de oro que ningún banquete saciaba.', 'Quiso todo y todo lo pagó caro: durmió sobre sacas de oro y velando cerrojos, y los suyos, cansados de ser una partida más en el libro, se fueron apartando.'],
    ['Su apetito de riqueza era proverbial: acaparaba cargas, créditos y concesiones con la minuciosidad de un contable y la ambición de un conquistador.', 'Cuantos trataron con {él|ella} dejaron escrito el mismo reproche: ningún pacto le bastaba, ninguna ganancia le sabía a suficiente, y a su alrededor crecía el rencor de los socios.', 'Su codicia, que había levantado fortunas, acabó devorándolas: el oro que amasó no cabía ya en los almacenes y, sin embargo, siguió exigiendo más, sin ver cómo la ruina avanzaba por detrás.'],
    ['Era un reactor que quemaba oro sin enfriarse: las flotas lo alimentaban y no bastaban; donde había grano, núcleo o cargamento, allí estaba su mirada, y cada riqueza ganada solo le enseñaba lo mucho que aún faltaba.', 'El oro l{o|a} atraía como un pozo de gravedad atrae todo lo que pasa cerca; cada contrato cerrado abría otro, y en ese hambre sin tregua se fue agriando cuanto alguna vez fue afecto.', 'Lo quiso todo, y el todo se lo cobró: murieron a su alrededor los que no supieron callar, se pudrieron en los depósitos los bienes que no quiso repartir, y ni el último puñado de oro le dio calor.'],
  ]);

  F('rasgo_codicia_baja', [
    ['No llevaba cuentas ni las echaba en falta.', 'Regalaba lo suyo y se burlaba de quien contaba.', 'Perdió todo lo suyo y no lo lamentó.'],
    ['Cobraba sin mirar la cifra y pagaba sin mirar el recibo; su bolsa pasaba de mano en mano y volvía a veces, sin que le inquietara si volvía.', 'El dinero le resbalaba, y eso irritaba a socios y acreedores, que no entendían a quien rechazaba una ganancia segura por no discutir un precio.', 'Dejó que le vaciaran las arcas sin levantar la voz: el oro, decía, solo pesaba, y no vio venir a quienes se aprovechaban de su desprendimiento hasta que ya no quedó nada que repartir.'],
    ['Dormía igual con los cofres llenos que vacíos; las monedas le parecían fichas de un juego ajeno, y la gente que se le acercaba lo notaba y respiraba más tranquila.', 'Pasaba junto a una fortuna con el desdén de quien cruza un pasillo: no la codiciaba, y ese desinterés ponía nerviosos a los que lo habían apostado todo a comprar su voluntad.', 'Vivió sin aferrarse a nada que se pudiera contar: cuando llegó la ruina de los precios, no tenía reservas ni queja, y se quedó mirando cómo se vaciaban los almacenes con una calma que dolía ver.'],
    ['Fue rareza en su tiempo: la riqueza no tuvo poder sobre {él|ella}. Rechazó comisiones, repartió botines y jamás se le oyó hablar de precio cuando todos hablaban de precios.', 'Su desdén por el dinero, que algunos tomaron por virtud y otros por insolencia, le granjeó tantas amistades como enemigos entre los hombres de cuentas de la época.', 'Nunca pensó en el oro hasta que le faltó; entonces, sin reservas, vio caer a los suyos de hambre y comprendió, demasiado tarde, lo que cuesta el desprecio por lo que otros guardan.'],
    ['Pasó entre tesoros como la luz entre el polvo, sin dejar huella en ellos ni llevarse nada; hubo quien juró que, puesto un núcleo de reactor entero en sus manos, lo habría cambiado por un buen cuento.', 'El oro, que a otros doblaba el espinazo, no le dijo nunca nada; esa sordera fue escudo y afrenta para quienes ofrecían fortunas por comprar su voluntad, y ninguna fortuna la movió.', 'Lo dio todo y no guardó nada, y cuando la desgracia llamó a su puerta no había arcas que abrir ni muro que alzar: quedó desnud{o|a} ante el destino, con las manos limpias y vacías.'],
  ]);

  F('rasgo_valor_alto', [
    ['Entraba en el peligro antes que nadie.', 'Desoía las órdenes de retirada.', 'No retrocedió nunca y quedó herid{o|a} por ello.'],
    ['Cuando sonaba la alarma de abordaje, caminaba hacia la esclusa en lugar de alejarse de ella, y quienes le seguían descubrían que el miedo se contagiaba menos que su calma.', 'Retroceder le parecía una forma lenta de morir; plantaba cara a todo, a los jefes que le ordenaban prudencia y a los enemigos que le apuntaban, con una terquedad que sacaba de quicio.', 'Se lanzó a una cubierta en llamas para sacar a los suyos y salió con las manos abrasadas; la cicatriz le quedó para siempre, y también la costumbre de volver a entrar.'],
    ['Su temple era el de quien conoce el vacío y no lo teme: en los asaltos más duros avanzaba con paso tranquilo, como si el peligro fuera una estancia más de camino a casa.', 'Daba un paso adelante donde otros lo daban atrás; ese reflejo le ganó respeto y le valió enemigos, y a sus propios mandos les costaba tenerle a raya.', 'Se plantó ante lo que nadie se atrevía a mirar y lo pagó con cicatrices y con amigos enterrados; era valiente de un modo que costaba caro, y {él|ella} lo sabía y seguía de frente.'],
    ['Su arrojo se citaba como ejemplo en los cuarteles: en el momento del choque no se vio un temblor en su voz ni una duda en su paso, y las tropas a su mando aprendieron a medirse con esa vara.', 'Su coraje era de los que incomodan: ni órdenes, ni presagios, ni consejos le detenían, y más de un superior se preguntó si aquella falta de miedo no acabaría por hundir a todos.', 'Fue valiente hasta la temeridad, y la historia lo apunta en su cuenta y en su contra: marchó al frente de los suyos allí donde la muerte esperaba con los brazos abiertos, y la muerte no siempre se conformó con el enemigo.'],
    ['El vacío mismo parecía abrirle paso: caminaba hacia el fuego cuando todos corrían en dirección contraria, y los disparos le rozaban como quien sabe que no puede detener a quien no se detiene.', 'No hubo muro que no tentara, ni oscuridad que no probara con la frente; su audacia era un desafío lanzado al destino, y el destino, que todo lo anota, esperaba con paciencia.', 'Avanzó siempre y nunca supo volver sobre sus pasos: marchó contra lo imposible con el pecho descubierto, y las lápidas de sus compañeros, alineadas tras {él|ella}, fueron el precio de aquella marcha sin freno.'],
  ]);

  F('rasgo_valor_bajo', [
    ['Evitaba el peligro siempre que podía.', 'Callaba ante los fuertes y esquivaba lo arriesgado.', 'Huyó cuando debía quedarse, y lo supo.'],
    ['Prefería los pasillos sin ventanas a las cubiertas expuestas y tenía siempre calculada la salida más cercana; nadie le reprochaba nada hasta que el peligro llegaba de verdad.', 'El miedo le dictaba las decisiones: cedía antes de discutir, se escondía en las reuniones difíciles y se justificaba luego con razones de prudencia que no engañaban a nadie, ni a sí mism{o|a}.', 'Se quedó en la esclusa cuando los suyos entraron en la bodega, y desde allí oyó lo que ocurría; esa vergüenza le fue más pesada que cualquier herida.'],
    ['Su pulso se aceleraba ante una voz alzada y se le iban los ojos hacia las puertas; no era perverso, solo tenía el miedo a flor de piel y el hábito de obedecerlo en cuanto se le presentaba.', 'Temblaba por dentro y lo disimulaba mal: cada vez que había que dar la cara, encontraba un motivo urgente en otra parte, y los compañeros acabaron por no esperarle.', 'Cuando llegó el asalto, el miedo le cerró la garganta y las piernas; huyó entre gritos que luego no dejaron de perseguirle, y la memoria de lo que dejó atrás le quitó el sueño para siempre.'],
    ['Los testigos no ocultan que su ánimo flaqueaba ante el peligro: en las horas críticas buscaba resguardo, y los que dependían de {él|ella} aprendieron a no contar con su brazo cuando silbaban los disparos.', 'Era sabido que, en el instante decisivo, el miedo hablaba antes que {él|ella}: pactaba, retrasaba, cedía, y cada retirada alimentaba el desprecio de unos y la lástima de otros.', 'Su cobardía, en una hora de prueba, costó vidas: abandonó su puesto cuando el enemigo cruzó las barreras, y la historia, que perdona casi todo, no le perdonó eso.'],
    ['El miedo vivía en {él|ella} como un segundo corazón, más grande que el propio, y ordenaba cada paso; ante las puertas del peligro, siempre torcía hacia el lado opuesto.', 'Vivía a la sombra de su propio miedo, que le susurraba al oído y le tapaba los ojos; cada vez que el destino l{o|a} llamaba al frente, encontraba un pretexto, y el pretexto se hacía costumbre y la costumbre, destino.', 'Huyó, y la huida l{o|a} alcanzó: el miedo que le salvó una vez le exigió luego cada noche un precio mayor, hasta que ya no quedó nada de {él|ella} que no fuera fuga.'],
  ]);

  F('rasgo_lealtad_alta', [
    ['Nunca abandonó a los suyos.', 'Defendía a los suyos aunque se equivocaran.', 'Siguió a los suyos hasta perderlo todo.'],
    ['Su palabra valía más que cualquier contrato: quien trabajó a su lado sabía que le cubriría la espalda en la bodega y en la mesa de negociación, hubiera o no testigos.', 'Tragó insultos y ofertas jugosas por no vender a su gente, y vivió con la sospecha de que esa fidelidad le salía más cara que a otros su traición.', 'Se mantuvo junto a los suyos cuando todo aconsejaba soltarlos; cargó con culpas ajenas, pagó con su nombre y vio cómo la lealtad, que nadie le agradeció, le costaba el sitio que tenía.'],
    ['Pertenecía a su gente como el casco a la nave: no había discusión sobre eso. Cuando alguien de la tripulación necesitaba un aval, un hombro o un secreto guardado, ya sabía a quién acudir.', 'Mantuvo su fidelidad incluso a contrapelo: rechazó los mejores ofrecimientos de los rivales, cargó con deudas que no eran suyas y sostuvo con obstinación a gente que no siempre lo merecía.', 'Prefirió caer con los suyos antes que salvarse sin ellos; cuando llegó el hundimiento, ya habían pasado por la esclusa todas las ofertas y todos los pretextos, y {él|ella} seguía en su puesto.'],
    ['Su nombre quedó entre los de quienes nunca cambiaron de bando: fiel a su casa, a su flota y a su palabra, ofrecía una firmeza que sus aliados daban por descontada y sus enemigos desesperaban de quebrar.', 'Su lealtad era proverbial y no siempre cómoda: obedecía mal a quien no la merecía, sostenía a los caídos con un empeño casi terco, y por ello algunos poderosos la tenían por reproche.', 'Fiel hasta el sacrificio, perdió posición, bienes y sangre por no soltar a los suyos; la historia dejó constancia de aquella entrega y de lo poco que ya se estilaba en su tiempo.'],
    ['Ni el oro ni el miedo hallaron nunca grieta en su palabra: quien la tenía de su parte tenía una muralla, y los suyos dormían tranquilos mientras {él|ella} velaba.', 'Era de los que juran una vez y cumplen para siempre; l{o|a} pusieron a prueba con fortunas y con amenazas, y salió de cada prueba más pesad{o|a} de lo que entró, cargad{o|a} de rencores ajenos.', 'No soltó la mano de los suyos ni cuando se hundían en la oscuridad; cayó con ellos, y los que quedaron grabaron en la piedra del puerto que hubo alguien que no supo qué era abandonar.'],
  ]);

  F('rasgo_lealtad_baja', [
    ['Servía a quien pagaba más.', 'Cambió de bando cuando convino y lo negó.', 'Traicionó a los suyos y le salió caro.'],
    ['Llevaba sus fidelidades como se lleva el abrigo, según la estación: hoy con una casa, mañana con otra, y siempre con una explicación a mano para quien se sorprendiera.', 'Juraba con la mano en el pecho y miraba de reojo a quien ofrecía más; sus compañeros aprendieron a no darle la espalda ni los secretos, y {él|ella} aprendió a no echarlos de menos.', 'Vendió a quien le había dado cobijo en cuanto cambió el reparto, y los de su antigua gente, cuando lo supieron, no quisieron volver a pronunciar su nombre.'],
    ['Tenía una fidelidad de superficie: se adaptaba a cada bando con la sonrisa justa, repetía sus consignas con fluidez y, sin dolor visible, las cambiaba por las de enfrente cuando el reparto de fuerzas se torcía.', 'Ninguna bandera le duró lo bastante para mancharla: la lealtad, para {él|ella}, era una moneda de cambio, y quienes la aceptaron como pago pronto aprendieron a contar el cambio con cuidado.', 'Cambió de bando una y otra vez, y la última traición le salió al encuentro: los que había abandonado l{o|a} esperaron en el muelle, y los que había servido no movieron un dedo.'],
    ['Su volubilidad fue célebre: sirvió a casas rivales con el mismo fervor y las dejó con la misma prisa, de modo que nadie supo nunca de qué lado estaba más allá del día de la pregunta.', 'Su palabra circulaba con descuento: había pactado con todos y a todos había fallado, y aun así los poderosos seguían escuchándole, porque sabían que quien no se comprometía con nadie podía comprarse.', 'Traicionó una y otra vez hasta que la traición l{o|a} alcanzó: el día en que cambió de bando por última vez ya no quedaba bando que le recibiera, y la historia anotó su fin entre el desprecio de unos y el olvido de otros.'],
    ['Cambiaba de bando como el corsario de pabellón al entrar en cada puerto: hoy bajo una insignia, mañana bajo la rival, y siempre dispuest{o|a} a jurar que su corazón había estado allí desde el principio.', 'La fidelidad le era un traje prestado y lo dejaba en cualquier posada del camino; en cada giro de la fortuna encontraba una razón noble para el cambio, y el mundo, cansado, fue dejando de preguntarle por ellas.', 'Vendió a quienes l{o|a} amaron por quienes no sabían su nombre, y a estos por otros más; cuando se le acabaron los bandos, el silencio de los muelles fue la sentencia.'],
  ]);

  F('rasgo_empatia_alta', [
    ['Se detenía ante quien sufría.', 'Sufría por los demás y no lo callaba.', 'Lloró a muertos que no eran suyos.'],
    ['Notaba al primer vistazo quién llevaba un mal día en el turno, y sin decir palabra le dejaba una taza caliente o le cubría el trabajo; sentía lo ajeno casi como propio.', 'Le dolían las penas de los demás más que las suyas, y esa herida abierta le impedía pasar de largo; pagaba con noches en vela las cosas que no podía arreglar.', 'Se quedó junto a los moribundos de la cuarentena cuando los demás cerraron las puertas, y cada muerte le dejó una grieta; con el tiempo, el pesar ajeno acabó pesándole más que el propio.'],
    ['Sabía escuchar de un modo que desarmaba: la gente le contaba sus cuitas en los pasillos, en las colas del racionamiento, junto a las escotillas, y se iba más ligera.', 'Cualquier lágrima ajena le encogía el pecho, y le era imposible fingir indiferencia ante el hambre o el miedo de otros, aunque ello le costara el favor de quienes preferían no mirar.', 'Cargó con el duelo de quienes no tenían quien lo cargara: veló cadáveres de desconocidos, consoló a viudas de otros y, poco a poco, fue consumiéndose bajo un dolor que no era suyo y que acabó pareciéndolo.'],
    ['Su compasión era conocida en todo el puerto: no pasaba junto a un sufrimiento sin detenerse, y en los años duros su puerta fue la primera a la que llamaban los desamparados.', 'Su sensibilidad al dolor ajeno era virtud y herida a la vez: cada injusticia que presenciaba la sentía en el cuerpo, y de esa llaga brotaba una indignación que incomodaba a los poderosos.', 'Se dejó el alma en los hospitales, en los depósitos de grano vacíos y en los barrios cerrados por la peste, sosteniendo a quienes se caían; aquella piedad le costó la salud y, por fin, la paz.'],
    ['Oía el dolor ajeno como otros oyen una alarma, de un extremo a otro del puerto, y ninguna distancia lo hacía menos suyo: allí donde alguien lloraba, {él|ella} ya iba caminando.', 'El sufrimiento de los demás le entraba por los ojos y se le instalaba en el pecho sin pedir permiso; por no cerrar las puertas a nadie, el mundo le fue cargando más penas de las que un corazón puede llevar.', 'Lloró con cada huérfano y veló cada muerte, hasta que el dolor ajeno, tantas veces acogido, se le volvió muro y mortaja, y a su lado el mundo siguió sin enterarse.'],
  ]);

  F('rasgo_empatia_baja', [
    ['Pasaba junto a quien sufría sin mirar.', 'Ignoraba las quejas ajenas.', 'Vio morir a otros y no se inmutó.'],
    ['Los problemas de los demás le resbalaban: escuchaba el relato de una desgracia con la misma atención con que oía un parte de carga, y en cuanto se acababa pasaba a otra cosa.', 'Había en su trato una frialdad que enfriaba las salas; ante las lágrimas ajenas fruncía el gesto, impaciente, y a quien se quejaba le recordaba el precio del tiempo.', 'Ordenó cerrar una esclusa sobre quienes suplicaban al otro lado, y no volvió la cabeza; los gritos se apagaron y su sueño, esa noche, fue tan profundo como siempre.'],
    ['Tenía los ojos secos y un oído que solo atendía a lo útil: el sufrimiento de los demás era para {él|ella} un ruido de fondo, como el de los recicladores de aire, que a fuerza de oírlo uno deja de notar.', 'Miraba el hambre ajena desde una distancia de cristal: ni un gesto, ni una palabra de consuelo, y cuando se lo reprochaban sonreía de lado, con un cansancio que parecía desdén.', 'Atravesó hospitales atestados y muelles de duelo sin variar el paso, y quienes quedaron sin amparo a su sombra aprendieron a pronunciar su nombre en voz baja y con los dientes apretados.'],
    ['Su sequedad llamaba la atención de cuantos le trataron: no se le vio conmoverse ante las muertes, los llantos ni los ruegos, y en sus consejos se medía la vida de las personas como se miden las raciones.', 'Su insensibilidad ante el sufrimiento era tan notoria que los subordinados la daban por una forma de poder; sin embargo, quienes cruzaron su sombra la recordaron durante generaciones como un frío más duro que el del vacío.', 'Firmó el sacrificio de poblaciones enteras con el mismo pulso con que firmaba un albarán, y ni el eco de los lamentos turbó su descanso.'],
    ['Cuentan que llevaba el corazón como un reactor sin combustible, apagado y mudo; el dolor ajeno rebotaba en {él|ella} como el polvo estelar en el casco y se perdía sin eco.', 'Ante el llanto no se detenía, ante el hambre no bajaba la voz, ante la muerte no levantaba la vista; de esa indiferencia hizo coraza y estandarte, hasta que los suyos aprendieron a no esperar nada de {él|ella}.', 'Pasó por el mundo sin que el dolor de nadie le dejara marca, y el mundo, a cambio, le devolvió el silencio: cuando le llegó el turno de sufrir, no hubo mano que se tendiera ni puerta que se abriera.'],
  ]);

  F('rasgo_rencor_alto', [
    ['Recordaba cada ofensa recibida.', 'Guardaba cada agravio y esperaba su turno.', 'Una ofensa vieja acabó en sangre.'],
    ['Llevaba una cuenta minuciosa de los agravios, como otros llevan la de las provisiones; no los exhibía, pero tampoco olvidaba un nombre ni la fecha en que se lo ganó.', 'Una palabra de más, dicha años atrás, seguía escociéndole como el primer día; saludaba con cortesía a quien le había ofendido y esperaba, sin prisa, el momento en que la deuda se saldaría.', 'Hizo del agravio su combustible: lo alimentó de noche, lo protegió del perdón y lo dejó crecer hasta que, con los años, estalló en algo mucho peor que la afrenta que lo había encendido.'],
    ['Su memoria para las ofensas era de archivo bien cuidado: sacaba de ella, con la serenidad de quien consulta un mapa, el nombre, el lugar y la hora en que alguien le había faltado.', 'El rencor se le había hecho casa: vivía en él, lo ventilaba cada tanto y, al menor roce con el ofensor, lo reavivaba como quien sopla sobre un rescoldo.', 'Guardó una afrenta durante años, como se guarda una carga peligrosa, hasta que el día de cobrarla llegó y se llevó por delante al ofensor, a su casa y a quienes tuvieron la mala suerte de estar cerca.'],
    ['No olvidaba una ofensa ni la perdonaba: sus enemigos lo sabían y sus aliados le temían, y la lista de agravios, escrita o de memoria, rigió buena parte de sus decisiones.', 'Su rencor, constante y callado, envenenó alianzas que habrían podido salvarse: bastaba un desaire antiguo para que se cerraran puertas, y los embajadores aprendieron a comenzar sus visitas pidiendo perdón por lo que no habían hecho.', 'No perdonó nunca, y esa tenacidad dejó un rastro de ruinas: familias enteras, puertos y flotas pagaron la deuda de una ofensa cuyo origen ya nadie recordaba salvo {él|ella}.'],
    ['Era un archivo de afrentas, y en él cada nombre tenía su fecha y su precio; los años no borraban nada, solo afilaban, y los ofensores caminaban por el mundo con la certeza sin voz de que alguien los esperaba.', 'El rencor ardía en {él|ella} como una estrella que no sabe apagarse: podía esperar generaciones, y quienes alguna vez le hicieron daño sentían su calor en la nuca aunque no lo vieran.', 'Alimentó su agravio con una paciencia que no conocía el cansancio y lo cobró con sangre: cayeron los que le ofendieron y también los que no tenían culpa, y de aquella deuda no quedó ni el recuerdo de la causa.'],
  ]);

  F('rasgo_rencor_bajo', [
    ['Perdonaba las ofensas al día siguiente.', 'Perdonaba pronto, aunque le ofendieran de nuevo.', 'Perdonó a quien le hirió y lo pagó.'],
    ['Las ofensas le duraban lo que un mal turno: al día siguiente ofrecía la mano, partía el pan y hablaba de otra cosa, como si el agravio se hubiera quedado en el corredor.', 'Perdonaba antes de que le pidieran perdón, y a algunos eso les parecía debilidad y a otros impertinencia; las cuentas pendientes de otros le cansaban más que las ofensas que soportaba.', 'Estrechó la mano de quien l{o|a} había traicionado y le abrió de nuevo la puerta; el perdón era su costumbre y su flaqueza, y el traidor, agradecido, volvió a clavarle el cuchillo con el mismo gesto.'],
    ['Su rencor era de arena: bastaba una disculpa, o a veces ni eso, para que se deshiciera, y quien se acercaba a pedirle cuentas se encontraba con una sonrisa y una silla en la mesa.', 'Le costaba guardar un resentimiento aunque lo intentara; ante los agravios, apretaba los labios una tarde y luego los soltaba, y los que se aprovechaban sabían bien dónde acudir a estirar su indulgencia.', 'Perdonó una y otra vez a quien le hacía daño, sin amargura y sin memoria; cuando la última ofensa resultó irreparable, ya no le quedaba rencor con el que defenderse, y la noche l{o|a} encontró desarmad{o|a}.'],
    ['Poseía una clemencia rara en los tiempos que corrían: olvidaba las ofensas con presteza, no cobraba deudas de honor y trataba a sus antiguos adversarios con la cortesía de un amigo.', 'Su facilidad para perdonar fue vista como sabiduría por unos y como debilidad por otros; la historia da la razón a ambos, pues más de un enemigo salió indemne de sus manos para volver, con intereses.', 'Perdonó a quienes no debía y abrió las puertas a quienes iban a cerrarlas con sangre; esa generosidad se celebró entonces, y lo que costó a su casa se contó después, más bajo.'],
    ['Dicen que el agravio le resbalaba como la luz de una estrella lejana sobre el casco de una nave: lo tocaba un instante y se iba, y al día siguiente su mano volvía a estar tendida.', 'Perdonaba como respira el que no puede evitar hacerlo, y ese don, que aplacó contiendas, le enfrentó a quienes pedían sangre; la hiel de los demás se acumulaba a su alrededor y se le cobraba en soledad.', 'Tendió la mano a quienes le hirieron una y otra vez, sin guardar memoria ni cuenta, y el mundo, que no sabe perdonar, se la devolvió ensangrentada: no se enfrió su ternura, pero se agotó el aire a su alrededor.'],
  ]);

  F('rasgo_ambicion_alta', [
    ['Pedía cada puesto que quedaba libre.', 'Se disputaba cada ascenso con sus compañeros.', 'Pisó a otros para subir.'],
    ['Estudiaba los organigramas como otros estudian cartas de navegación: sabía quién mandaba en cada muelle y cuánto faltaba para ocupar su puesto, y avanzaba con paso discreto y constante.', 'Ningún cargo le bastaba: en cuanto lo tenía, miraba el siguiente, y cada ascenso le dejaba el mismo sabor a insuficiencia y una lista más larga de rivales.', 'Subió a golpe de zancadilla y de favor cobrado, dejando atrás amigos que se convirtieron en estorbos; en la cima descubrió que el sitio era estrecho y que nadie quedaba cerca.'],
    ['Su mirada siempre iba un peldaño más arriba que sus pies: planeaba con paciencia, se ganaba a los jefes, enseñaba a sus subordinados a depender de {él|ella} y no hablaba de poder, solo de responsabilidades.', 'Aspiraba a mandar y no lo disimulaba lo suficiente: bajo la cortesía se le notaba el cálculo, y los superiores, que sabían leer ese hambre, empezaron a vigilar sus pasos y a la vez a dejarle avanzar.', 'La ambición le quemaba por dentro como un reactor sin blindaje: subió, mandó, aplastó, y lo que quedó a su paso —amistades, familia, sueño— lo dio por pérdida aceptable a cambio de una silla más alta.'],
    ['La crónica anota su sed de mando: escaló puesto a puesto, enlazó favores y silencios, y no pareció satisfech{o|a} con ninguna de las alturas que alcanzaba, porque cada una le revelaba otra más.', 'Quiso mandar y no se contentó con ser primero entre iguales: urdió alianzas, deshizo rivalidades y vio en cada puesto ocupado el peldaño del siguiente, mientras la desconfianza de los suyos crecía con cada ascenso.', 'Su ambición, que fue su grandeza, acabó por ser su condena: ascendió sobre cuerpos y ruinas, tocó el poder y vio que no era sino un trono hueco, y pagó caro el haber sacrificado todo por alcanzarlo.'],
    ['Parecía haber nacido con la mirada puesta en el último escalón; cada puerto conquistado era el umbral del siguiente, y cada cargo, apenas una estación de paso en un viaje que no conocía destino ni descanso.', 'Su sed de mando era una llama que se nutría de lo que ganaba: cuanto más tenía, más pedía, y cada trono alcanzado solo le servía para divisar el siguiente y, a los que dejaba atrás, para temerle.', 'Quiso el mundo entero y el mundo se lo cobró: subió sobre la sangre de los suyos, subió sobre los restos de lo que amó, y en lo más alto no halló corona sino un silencio helado, donde el eco devolvía su propio nombre.'],
  ]);

  F('rasgo_ambicion_baja', [
    ['Rechazó ascensos; le bastaba su puesto.', 'Rehusó cargos y le llamaron conformista.', 'Se quedó donde estaba y perdió lo que no defendió.'],
    ['Se contentaba con su oficio, su mesa y el trozo de muelle que sentía propio; cuando le ofrecían subir de puesto, agradecía y declinaba, y nadie lograba convencerle de que se perdía algo.', 'No quería mandar ni que le mandaran más de la cuenta; cuando los suyos le pedían dar un paso adelante, se encogía de hombros, y la amargura de los que esperaban algo mejor se le acumulaba a la espalda.', 'Rechazó la silla que otros habrían matado por tener, y en ese rechazo quedó a merced de quienes sí la quisieron; lo que no defendió por desinterés se lo arrebataron sin ruido.'],
    ['Tenía el sosiego de quien ya ha llegado adonde quería: un taller en orden, la ventana abierta al muelle, una cena que no esperaba a nadie; los cargos, las medallas y los nombramientos le pasaban por delante como naves de otro puerto.', 'Nadie consiguió despertar en {él|ella} ambición alguna: se le ofrecieron mandos, tierras, contratos, y los dejaba sobre la mesa con la delicadeza con que se devuelve un regalo que no se necesita, para exasperación de quienes contaban con su ayuda.', 'Solo quiso lo suyo, y creyó que bastaba; cuando la tormenta política llegó a su puerta, sus pocas pertenencias eran lo único que defendía, y fue poco y fue tarde.'],
    ['Sorprendió a todos por su moderación: pudo haber medrado y no quiso, pudo haber mandado y declinó, y vivió sin sombra de codicia política, atendiendo su oficio mientras otros se disputaban los despachos.', 'Su falta de ambición, que los tibios llamaban sabiduría y los audaces desidia, le valió el respeto de pocos y el desdén de muchos; quienes querían usarle como peldaño se estrellaron contra aquella calma obstinada.', 'No aspiró a poder alguno, y el poder le buscó a {él|ella}: arrastrad{o|a} por los intereses de otros, pagó con su sosiego y con su sangre una guerra que nunca había querido.'],
    ['Dicen que le ofrecieron un trono y respondió preguntando por el precio del grano; no quería más reino que el de su mesa, y en esa pequeñez cabía una paz que los grandes del mundo no supieron comprar.', 'Se mantuvo al margen de las grandes mesas, y los ambiciosos, que no entienden a quien no quiere nada, buscaron durante años el vicio o la trampa que explicara su calma; no había ninguno: solo una paz que les ofendía.', 'Quiso poco y poco tuvo, y cuando el fuego de las ambiciones ajenas llegó hasta su umbral, no había nada con qué apagarlo; así se perdió quien nada reclamaba, en una guerra que los otros habían iniciado por todo.'],
  ]);

  F('rasgo_fe_alta', [
    ['Cumplía cada rito y no dudaba.', 'Creía sin dudar y reñía con quien dudaba.', 'Perdió a los suyos por sus creencias.'],
    ['Rezaba antes de cada guardia y daba gracias a los muros, a la luz y al aire de su hogar; no hacía alarde de ello, pero cuando hablaba de lo sagrado se le notaba la certeza como una temperatura.', 'Creía con una firmeza que no admitía matices, y con ella medía a los tibios y a los escépticos, a quienes miraba con una mezcla de lástima y reproche; en su mesa, las discusiones sobre lo sagrado terminaban pronto y mal.', 'Entregó su vida a una convicción que los demás miraban de lejos; la sostuvo cuando le cerraron puertas y le quitaron lo suyo, y la sostuvo todavía cuando, ya sin nada, solo le quedaba esa certeza.'],
    ['Sus creencias no eran un traje de fiesta sino un hueso: caminaba, comía y trabajaba apoyad{o|a} en ellas, y su serenidad en los días malos sorprendía a quienes veían en ellas un simple consuelo.', 'Vivía con la mirada puesta en promesas que otros daban por cuentos, y su convicción, tan limpia como inflexible, la enfrentaba a quienes preferían que las cosas se explicaran con balances y cifras.', 'Siguió creyendo cuando el credo que profesaba fue perseguido, y creyó con más fuerza en las bodegas donde l{o|a} encerraron, entre quienes lo negaban; su fe, que fue su luz, acabó siendo su cadena.'],
    ['Su fe no tenía fisuras: creía en lo que predicaba y lo practicaba sin cálculo, de modo que ni los premios ni los reproches movieron un ápice sus convicciones, y los fieles de su entorno hallaron en ella un modelo.', 'Su fe era de las que dividen a las familias y las naves: nada la hacía ceder, ni la burla, ni la prudencia ajena, ni la amenaza, y a su sombra se partieron amistades que parecían de acero.', 'Creyó hasta el final y hasta el límite, y bien se supo lo que esa certeza le cobró: perdió bienes, familia y reposo, sin que ninguna de las pérdidas le arrancara una duda.'],
    ['Su creencia era tan honda que lo sagrado le hablaba en el zumbido de los reactores y en el silencio de los pasillos, y que la serenidad de su mirada fue, para muchos, la mejor prueba de lo que predicaba.', 'Creía como se arde: sin término medio, sin reposo, sin espacio para el escéptico; su fe fue lámpara para unos y hoguera para otros, y su luz, tantas veces, quemó más de lo que alumbró.', 'Su fe fue baliza y patíbulo: guió a multitudes y condujo a quien la sostenía hacia el sacrificio, y quedó escrito en el casco de los muelles que creer así vale una vida, y que {él|ella} la pagó entera.'],
  ]);

  F('rasgo_fe_baja', [
    ['No creía en nada que no pudiera ver.', 'Se burlaba de quienes creían en profecías.', 'No creyó en el peligro hasta verlo.'],
    ['Pedía pruebas de todo: verificaba las cifras del almacén, desmontaba las máquinas para ver cómo funcionaban y escuchaba las promesas de los profetas con una sonrisa cortés y los brazos cruzados.', 'Tenía el escepticismo afilado de quien ha visto demasiados milagros por encargo; en los cultos y en las profecías no veía más que negocios, y se lo decía a quien quisiera oír, con la crudeza de un parte de averías.', 'No creyó en los avisos, ni en los presagios, ni en los ruegos de los suyos; solo creía en lo que podía tocar, y cuando por fin lo tuvo delante, ya no quedaba nadie que le hiciera caso.'],
    ['Su mundo se medía con instrumentos: lo que no marcaba aguja ni se dejaba pesar, para {él|ella} no existía, y dormía, tranquil{o|a}, sin más promesas que las de un buen mantenimiento.', 'Sonreía ante el fervor de los demás con una ironía que cortaba; discutía con los fieles, con los videntes y con los que le pedían confianza, y en sus palabras no había fe ni cabida para ella.', 'No creía en nada que no pudiera ver, y por eso nada le advirtió: el desastre vino por donde no miraba, y en la hora de la ruina no tuvo ni plegaria ni consuelo a los que agarrarse, solo la evidencia.'],
    ['Su escepticismo fue notorio: ni las profecías, ni los ritos, ni las promesas de más allá de la muerte le merecían crédito, y gobernó su vida por lo comprobable con una obstinación que algunos tomaron por frialdad.', 'Su incredulidad, ostentosa y áspera, le enemistó con los fieles de su tiempo: llamaba superstición a lo que otros llamaban consuelo, y con esa claridad hiriente se ganó tantos respetos como odios.', 'Nada creyó que no tocara con las manos, y esa limitación, convertida en orgullo, le impidió ver llegar lo que ya muchos intuían; el desastre se le presentó sin nombre y no comprendió de dónde venía.'],
    ['Se negaba a creer en lo que los ojos no abarcaran: no creía en estrellas que no estuvieran en un mapa ni en voces que no viajaran por un cable, y el misterio, harto de esperar, rodeaba su casa y no entraba.', 'Medía el universo con la regla de lo visible y lo declaraba entero; las profecías le provocaban risa, los presagios, un encogimiento de hombros, y el silencio de lo que no veía, un desafío al que respondía con desdén.', 'No creyó en lo que no vio, y lo que no vio vino a buscarle: el mal que desoyó golpeó a su puerta sin anuncio y arrasó lo que tenía, y entre las ruinas {él|ella} seguía exigiendo una prueba.'],
  ]);

  F('rasgo_prudencia_alta', [
    ['Comprobaba todo antes de actuar.', 'Aplazaba las decisiones y le reprochaban la lentitud.', 'Esperó demasiado y llegó tarde.'],
    ['Estudiaba cada trayecto antes de zarpar, revisaba las reservas, preguntaba a los viejos y solo entonces daba la orden; sus planes tardaban en nacer, pero rara vez se rompían.', 'Medía los pasos con tanta cautela que sus rivales l{o|a} tomaban por indecis{o|a}; el día entero lo pasaba sopesando riesgos, y a la hora de decidir, los más impacientes ya se habían marchado a otros bandos.', 'Su cautela le salvó de muchas trampas, pero no de la hora en que había que arriesgarse: dudó con el mapa abierto, dejó pasar la ocasión y vio cómo otros la aprovechaban sobre las ruinas de su plan.'],
    ['Calculaba antes de dar un paso con la serenidad de quien conoce los campos de escombros: llevaba siempre un plan de repuesto, una reserva de aire y una salida, y le gustaba decir que el mundo premia más a quien llega que a quien corre.', 'Su prudencia era una fortaleza y también un lastre: cada decisión pasaba por incontables comprobaciones, y mientras el mundo se movía, sus consejeros aprendían a pronunciar «aún no» con idéntica resignación.', 'Previó todo salvo lo que no se podía prever: tras años de cálculos meticulosos, la desgracia entró por la única rendija que no había sellado, y {él|ella} comprendió demasiado tarde que la cautela no es un escudo.'],
    ['Se elogiaba su cautela en todos los puertos: nunca dio un paso sin medirlo, nunca ordenó una maniobra sin saber cómo se desharía, y su tiempo, de tantas tormentas, l{o|a} recordó como timonel sin naufragios.', 'Su cálculo llegó al extremo: midió tanto que dejó pasar mucho, y los cronistas anotan sus planes perfectos y sus ocasiones perdidas, y la desesperación de los que dependían de una orden suya que no llegaba.', 'Su prudencia, que salvó flotas, no pudo salvarle: previó cada riesgo menos el que llevaba dentro de casa, y la crónica deja constancia de que ni el plan más minucioso protege de lo que no se mira.'],
    ['Pesaba el aire antes de respirarlo y medía el silencio antes de romperlo; cada paso suyo había sido ensayado incontables veces en su cabeza, y el destino mismo parecía esperar a que {él|ella} diera el siguiente.', 'Avanzaba como quien cruza un campo de minas, sin prisa y sin tregua, y su lentitud, que salvó vidas, hizo perder batallas; el mundo, impaciente, empezó a murmurar que la sensatez también puede ser una forma de cobardía.', 'Midió cada paso y cada sombra, y la fatalidad, que no entiende de medidas, acabó cayendo por el único lado que no tenía en cuenta; quedó el rastro de una vida entera de cuidados deshecha en un instante.'],
  ]);

  F('rasgo_prudencia_baja', [
    ['Actuaba antes de pensar.', 'Actuaba sin pensar y los avisos no servían.', 'Se lanzó sin pensar y hubo muertos.'],
    ['Decidía sobre la marcha y a golpe de impulso, con una sonrisa y sin plan; a veces acertaba, y esas veces le bastaban para seguir creyendo que pensar es perder el tiempo.', 'Las advertencias le entraban por un oído y le salían por el otro: se lanzaba a todo con la cabeza caliente y, cuando salía mal, buscaba culpables en vez de causas.', 'Se echó a una maniobra sin mirar el combustible ni el reloj, y no calculó lo que un minuto de impulso podía costar a quienes le seguían; el balance se lo cobraron los demás.'],
    ['Vivía a golpe de corazonada: tomaba el timón antes de leer la carta, y la temeridad con la que se lanzaba a las empresas le daba un aire de despreocupación que a muchos resultaba contagioso y a otros temible.', 'La reflexión le sobraba: firmaba al vuelo, abordaba antes de contar, prometía sin medir, y cada desastre evitable lo atribuía a la mala suerte, mientras los prudentes de su entorno contenían el aliento.', 'Se lanzó de cabeza a lo que cualquiera con sensatez habría rodeado, y el precio lo pagaron otros: tripulaciones enteras que fueron tras {él|ella} hacia un callejón sin salida; supo, demasiado tarde, que le habían avisado.'],
    ['Su impetuosidad pasó a los anales: decidía en un latido, ordenaba antes de escuchar y se internaba en lo desconocido sin mapas, con una fortuna que, durante un tiempo, pareció respaldarle.', 'Obraba sin freno: cada empresa suya nacía de un arrebato y desembocaba en una crisis, y los cronistas, entre el asombro y la alarma, apuntaron la desesperación de quienes tenían que arreglar lo que dejaba a medias.', 'Su precipitación fue su perdición y la de muchos: arrastró a flotas y casas a empresas que solo la prisa podía justificar, y el eco de sus errores, pagados con sangre ajena, resonó mucho más allá de su tiempo.'],
    ['Se echaba al abismo antes de mirar si había suelo, y el suelo, por no desairarle, aparecía; en cada salto improvisado había un destello de audacia que los prudentes llamaron locura y la gente, leyenda.', 'Era fuego sin cauce: ardía de golpe y sin cuidado, y alrededor de su impulso se acumulaban las cenizas de empresas a medio hacer; el mundo, fascinado y receloso, le seguía a distancia, como a un incendio que aún no ha elegido casa.', 'Se arrojó al destino sin pensar, y el destino, que no perdona la prisa, le respondió con todo su peso: de la imprudencia de aquel instante nacieron lutos que nada pudo deshacer, y el nombre de {él|ella} quedó unido a ellos.'],
  ]);

  F('rasgo_carisma_alto', [
    ['La gente le seguía sin que lo pidiera.', 'Atraía seguidores y la envidia de sus superiores.', 'Muchos le siguieron y murieron por ello.'],
    ['Entraba en una sala y se hacía un hueco a su alrededor: contaba las cosas con una voz cálida, recordaba los nombres y sabía mirar a cada uno como si fuese el único; la gente le seguía sin que tuviera que mandar.', 'Tenía el don de reunir voluntades y también el de provocar celos: los que le seguían le querían de más y los que no, de menos, y esa tirantez entre devotos y recelosos marcaba cada una de sus apariciones.', 'Bastó su voz para arrastrar a una multitud al muelle, y su voz bastó también para que muchos no regresaran; cargó desde entonces con el peso de las vidas que había movido con una palabra.'],
    ['Su sola presencia ordenaba el aire: las conversaciones se acercaban a {él|ella} como las naves al muelle, y quien le trataba una tarde volvía al día siguiente sin saber del todo por qué, pero con ganas.', 'Atraía como un imán: los jóvenes le copiaban los gestos, los viejos le pedían consejo y los poderosos, que veían crecer aquella estela, le miraban con la misma admiración que desconfianza.', 'Convocó lealtades tan ardientes que algunas ardieron con {él|ella}: los que le siguieron hasta el final cayeron a su lado, y la plaza donde hablaba por última vez quedó, durante años, vacía y reverente.'],
    ['Su don de gentes no tenía rival en su tiempo: movía a las multitudes con una frase, ganaba corazones con un gesto y, allí donde llegaba, las voluntades se ordenaban espontáneamente tras su figura.', 'Su magnetismo hizo de {él|ella} estandarte para unos y amenaza para otros: arrastraba a las gentes y a su paso se agrietaban las jerarquías, de modo que los poderosos no supieron si convenía abrazarl{o|a} o apartarl{o|a}.', 'Quienes le siguieron lo dieron todo, y el precio fue el de los que se entregan sin reserva: se enumeran sus partidarios caídos con la misma solemnidad con que se enumeran sus victorias, y pocos de ellos se arrepintieron.'],
    ['Cuando hablaba, las voces se callaban; cuando caminaba, los pasos se juntaban tras {él|ella}, y se decía que bastaba su mirada para convertir a un desconocido en devoto, y a un devoto, en leyenda.', 'Su voz era un cable tendido sobre los muelles: la tocaban muchos y la sentían todos, y esa atracción, que empujaba a los suyos e inquietaba a los otros, creció hasta que nadie supo si era una persona o una fuerza.', 'Le siguieron como se sigue una estrella, hasta el último pasillo; y cuando la estrella cayó, sus seguidores cayeron con ella, y de aquella multitud rendida nació un silencio que todavía los viejos llaman por su nombre.'],
  ]);

  F('rasgo_carisma_bajo', [
    ['Pasaba inadvertid{o|a} en las reuniones.', 'Hablaba y nadie le escuchaba.', 'Nadie notó su ausencia cuando faltó.'],
    ['Tenía un rostro que se olvidaba al volver la esquina y una voz que se perdía entre las demás; los compañeros de turno recordaban su trabajo mejor que su cara.', 'Se esforzaba por llamar la atención y solo lograba que los demás miraran otra cosa; hablaba en las reuniones y las miradas se le escurrían, y esa invisibilidad le fue agriando el carácter.', 'Alzó la voz en una sala llena y nadie se volvió; con los años dejó de alzarla y empezó a callar de otro modo, y su soledad se fue haciendo costumbre y herida.'],
    ['Era de los que nadie recuerda haber invitado: cruzaba los salones como un cable por una pared, indispensable y apenas visible, y cuando sus colegas hablaban de aquella obra bien hecha, tardaban en acordarse de a quién se debía.', 'Hablaba con sentido y sin fuerza, y sus propuestas, tan buenas como las ajenas, solo prosperaban cuando otro las repetía con mejor voz; esa injusticia pequeña y constante le dejaba un poso de amargura.', 'Nadie reparó en {él|ella} mientras vivía y casi nadie cuando faltó: pasó por los muelles como una sombra entre sombras, y el silencio que dejó fue tan hondo como la indiferencia que l{o|a} había rodeado.'],
    ['Los registros apenas le mencionan: sin presencia ni labia, ocupó puestos que otros recordaron por la obra y no por la persona, y su nombre aparece, discreto, al pie de lo que importó.', 'Carecía de ese brillo que arrastra a las multitudes, y pasó años viendo cómo otros, menos capaces, recogían los aplausos; los cronistas anotan la hiel de sus silencios y la dignidad con que la llevaba.', 'Su paso por el mundo fue tan discreto que hubo que rebuscar para dar con su rastro; cuando cayó, nadie lo supo, y esa soledad —la de quien nunca fue notado— quedó como su rasgo más fiel.'],
    ['Era un nombre sin eco: pronunciado en el muelle, se perdía antes de llegar a la dársena, y los que cruzaban miradas con {él|ella} las olvidaban en el mismo instante, como se olvida el reflejo de una ventana.', 'La luz de los demás le pasaba por encima sin tocarle; hablaba y la sala seguía su ruido, alzaba la mano y nadie la veía, y de aquella invisibilidad fue sacando una dureza sorda, un ruido propio que nadie oiría.', 'Pasó entre la gente como el humo entre naves ancladas: sin mover a nadie, sin dejar marca, y cuando el mundo le fue arrebatando lo que tenía, ni una voz se alzó a nombrarle; fue olvidad{o|a} antes de ser perdid{o|a}.'],
  ]);

  F('rasgo_habilidad_alta', [
    ['Hacía bien su trabajo.', 'Trabajaba mejor que sus superiores.', 'Hizo bien su trabajo y se ganó enemigos.'],
    ['Tenía manos y cabeza para el oficio: lo que le ponían delante, una soldadura, una ruta, un balance, salía de las suyas ajustado y limpio, sin alardes, y quien trabajaba a su lado aprendía solo con mirar.', 'Dominaba su oficio con una soltura que irritaba a los menos hábiles; corregía en silencio los errores de los demás y esperaba un reconocimiento que, cuando llegaba, tardaba y sabía a poco.', 'Su pericia l{o|a} hizo imprescindible, y eso fue su cárcel: no le dejaban descansar ni cambiar de oficio, y cuando una avería grave exigió lo imposible, el peso de todos cayó sobre sus manos.'],
    ['Trabajaba con una precisión que daba gusto mirar: la herramienta parecía obedecer a una voluntad tranquila, el casco quedaba sellado a la primera y los demás, sin confesarlo, regulaban su paso al de {él|ella}.', 'Su oficio era para {él|ella} un idioma natural: lo hablaba mejor que sus maestros, y esa ventaja, ejercida sin humildad, le valía tanto admiración como resentimiento en las salas de máquinas.', 'Brillaba tanto en su arte que los envidiosos le cercaron: sabotearon sus herramientas, difundieron rumores sobre su obra, y {él|ella} siguió ajustando tornillos con la misma precisión, aunque cada noche la soledad apretaba más.'],
    ['Su maestría no admitía discusión: en cualquier tarea que se le encomendó mostró una competencia pocas veces vista, y los de su gremio, aun sus rivales, repitieron durante años sus métodos.', 'Su talento era tal que humillaba a los que le rodeaban; la historia recuerda sus obras impecables y también la ojeriza de sus pares, que no le perdonaron nunca la facilidad con que hacía lo que ellos conseguían a duras penas.', 'Fue maestr{o|a} en lo suyo y pagó la excelencia con su tranquilidad: los poderosos exigieron cada vez más de sus manos, la gloria de sus obras fue ajena y {él|ella} comprobó que ser indispensable es una manera lenta de ser sacrificad{o|a}.'],
    ['Lo que tocaba prosperaba: las máquinas despertaban bajo sus manos, los planes más enredados se desenmarañaban a su paso, y quienes presenciaron su trabajo hablaban de aquello, durante años, como de un fenómeno natural.', 'Su destreza era un don que no pedía permiso: lo que otros hacían con esfuerzo, {él|ella} lo hacía como respirar, y por eso los de su gremio la veneraban con la misma intensidad con que la envidiaban en lo oscuro.', 'Fue artífice tan hábil que su obra quedó por encima de su vida: entregó las manos, los ojos y el sueño a lo que hacía, y lo que construyó sigue en pie en los muelles mientras la mano que lo hizo ya no puede descansar.'],
  ]);

  F('rasgo_habilidad_baja', [
    ['Era torpe en su oficio.', 'Cometía errores y le echaban la culpa.', 'Un error suyo causó muertos.'],
    ['Se le caían las herramientas y se le atascaban las tareas; con buena voluntad y mucho esfuerzo cumplía a medias lo que otros resolvían en un rato, y nadie le tenía en cuenta la torpeza, de tan ordinaria.', 'Trabajaba con empeño y resultaba mal: cada informe necesitaba correcciones, cada pieza se pasaba de medida y, cuando alguien lo señalaba, respondía con una susceptibilidad que empeoraba las cosas.', 'Se equivocó en una soldadura y un tramo del casco cedió; nadie le reprochó nada en voz alta, pero {él|ella} no volvió a mirar una junta sin que le temblara el pulso.'],
    ['Su oficio le pesaba como un traje ajeno: tropezaba con los mismos errores, los salvaba con un ingenio de último momento, y todos, con una paciencia de buenos vecinos, esperaban a que acabara y rehacían en silencio lo que había dejado.', 'Las herramientas parecían burlarse de {él|ella}: lo que a otros les salía a la primera, en sus manos pedía intentos y reproches; y ese tropiezo constante, visto por todos, se le fue clavando en el orgullo.', 'Un error de cálculo, uno entre muchos, acabó pagándose con vidas: {él|ella} siguió ejerciendo su oficio entre murmullos y miradas bajas, y la memoria de aquel fallo l{o|a} acompañó a cada pieza que tocó después.'],
    ['Su pericia dejaba que desear: en el oficio que le tocó ejercer cometió errores de bulto, enmendados una y otra vez por colegas pacientes, y sus éxitos se debieron más a la tenacidad que al talento.', 'Su torpeza era sabida, y a pesar de ello ocupó puestos que le venían grandes; los cronistas anotan los fallos, las correcciones de otros y la creciente amargura de quien intuye que no da la talla pero no puede dejar de intentarlo.', 'Su impericia, que durante años fue chiste, acabó siendo tragedia: un fallo suyo en una hora decisiva costó naves y vidas, y nadie se lo perdonó, aunque nunca se puso en duda que lo hubiese intentado con todas sus fuerzas.'],
    ['Las máquinas desconfiaban de sus manos: los instrumentos se descalibraban a su paso, las cargas se descolocaban cuando las tocaba, y entre los muelles se decía que un oficio mal aprendido es un hijo ingrato.', 'Persistía en el oficio sin dominarlo, como quien empuja un casco con las manos desnudas: cada intento fallaba, cada fallo alimentaba el murmullo, y el eco de su torpeza fue formando una leyenda menuda que l{o|a} siguió hasta el último puerto.', 'Sus manos fallaron cuando más se necesitaban, y de aquel instante vino una ruina que ningún mérito posterior pudo compensar; vivió con el recuerdo de su error como con una pieza rota en el pecho, y nadie tuvo que pedirle cuentas: se las pedía a diario con el silencio.'],
  ]);

  // ── Familia ───────────────────────────────────────────────────────────────────────────────────────
  F('familia_pareja', [
    ['Su pareja era {pareja}.', 'Pareja: {pareja}. Convivencia con disputas.', 'Vivía con {pareja}; la casa conoció golpes.'],
    ['Compartía casa y sobremesas con {pareja}, y la vida de ambos transcurría entre rutinas tranquilas.', 'Vivía con {pareja} en una convivencia de silencios largos, de reproches contenidos y de reconciliaciones que no terminaban de sanar nada.', 'Quiso a {pareja} con una intensidad que la vida no supo proteger: hubo más despedidas que encuentros, y cada regreso venía con una herida nueva.'],
    ['Al lado de {pareja} halló el reposo que buscaba: una mesa compartida, un cuarto con vistas al muelle y la costumbre de despertar y saber que no estaba sol{o|a}.', 'Su historia con {pareja} era un pulso afectuoso y áspero, hecho de gestos tiernos y reproches viejos, de portazos que se arreglaban a medianoche con una taza caliente.', 'La vida le unió a {pareja} y fue desgarrando esa unión sin cesar: lo que empezó con ternura derivó en ausencias, deudas y lutos, y quedó entre ellos un hueco que nadie supo llenar.'],
    ['Los registros asocian su nombre al de {pareja}, con quien fue visto en las ceremonias y en los días corrientes, y de quien se dice que fue sosiego y consejo durante largos años.', 'Su unión con {pareja} fue de las que murmuraban los pasillos: rivalidades de casa, desacuerdos públicos y una fidelidad obstinada que nadie quiso romper.', 'Amó a {pareja} en una época en que amar era arriesgarlo todo, y la historia recuerda que esa unión se pagó con exilios, pérdidas y ausencias que ya no tuvieron remedio.'],
    ['Con {pareja} caminaba por los muelles de la mano, y las luces, a su paso, parecían brillar con más calma: se amaron con la mansedumbre de lo que ha de durar.', 'Su amor por {pareja} fue fuego que no se apaga ni se calma: entre ellos se tendió siempre una cuerda tirante de orgullo y deseo, y todo el que los veía juntos sentía que algo tenía que ceder, y que nada cedió.', 'A {pareja} le dio {él|ella} cuanto tenía y el destino se lo cobró con intereses: lo que el mundo llamó una gran historia de amor se escribió con despedidas y con un silencio que los viejos aún recuerdan.'],
  ]);

  F('familia_viudez', [
    ['Su pareja, {pareja}, murió antes que {él|ella}.', 'Enviudó de {pareja} y no volvió a hablar de ello.', 'Perdió a {pareja} de golpe, sin despedida.'],
    ['Despidió a {pareja} tras una vida compartida, y siguió adelante con una nostalgia mansa, haciendo cada día un pequeño gesto en su memoria.', 'Quedó viud{o|a} de {pareja} con asuntos sin resolver, palabras que no se dijeron y un pesar áspero hacia sí mism{o|a}, que apenas disimulaba.', 'La muerte le arrebató a {pareja} sin aviso, y la casa quedó repleta de objetos que nadie se atrevía a mover.'],
    ['Sobrevivió a {pareja} con la serenidad de quien ha aceptado el orden de las cosas: guardó una cuchara, una chaqueta y una costumbre, y cada tarde las miraba un momento antes de seguir.', 'La muerte de {pareja} le dejó una casa demasiado grande y un resentimiento contra el tiempo; hablaba poco de ello y mucho de lo que debía haber hecho, y a quien se lo recordaba le despedía con sequedad.', 'Acompañó a {pareja} hasta la última esclusa y desde entonces anduvo como quien ha perdido el lado de la sombra en que se apoyaba: cada pasillo le devolvía una voz que ya no existía.'],
    ['Su viudez fue silenciosa: guardó con dignidad el recuerdo de {pareja} durante el resto de su vida y no habló nunca de su duelo en público, pues lo consideraba cosa privada.', 'Con la muerte de {pareja} se cerró una etapa de su vida y se abrió otra, más dura y más fría: los testigos advirtieron que, desde entonces, su trato se hizo áspero y su mirada, remota.', 'La muerte de {pareja} fue el golpe del que nunca se rehízo: se recuerda el luto riguroso, las decisiones sin sosiego de los años siguientes y la sombra que aquella pérdida arrojó sobre cada uno de sus actos.'],
    ['Cuando {pareja} murió, dicen que las luces del muelle vacilaron un instante, y que quien quedó vivo siguió caminando por los mismos pasillos, con la misma calma, hablando en voz baja con un silencio al lado.', 'Sobrevivió a {pareja} y no se lo perdonó: guardó el luto como se guarda una brasa bajo la ceniza, ni encendida ni apagada, y de esa llama sorda salió una dureza que el mundo tardó en conocer.', 'La muerte arrancó a {pareja} de su lado, y con ello se fue lo mejor que había: quedó un mundo gris, un nombre repetido a solas y una pena que no se aplacó ni con los años, ni con la gloria, ni con el olvido.'],
  ]);

  F('familia_hijos', [
    ['Tuvo {n} hijos: {hijos}.', 'Casa con {n} hijos ({hijos}) y poca paz.', 'Hijos: {n} ({hijos}). Hubo duelo en la casa.'],
    ['Crió a {n} hijos, {hijos}, entre las rutinas del puerto, con una paciencia que los vecinos celebraban.', 'Sus {n} hijos, {hijos}, crecieron entre exigencias y silencios, y ninguno terminó de entender lo que se esperaba de ellos.', 'Vio crecer a {n} hijos, {hijos}, a través de años de miseria y de pérdidas, y no a todos pudo defenderlos de lo que la vida les tenía reservado.'],
    ['Su casa se llenaba de voces cuando {hijos}, sus {n} hijos, volvían de los muelles; eran la mejor parte de su vida, y en torno a ellos se ordenaban las tardes y las sobremesas.', 'Educó a {n} hijos, {hijos}, con una mezcla de ternura y de rigor que a todos desconcertó: quería verlos fuertes y los dejaba sin consuelo, y de esa tensión salieron adultos tan amantes como cautelosos.', 'Dio la vida a {n} hijos, {hijos}, y la fatalidad le cobró parte de lo que le debía: hubo cunas vacías, noticias que llegaron tarde y un silencio nuevo en la mesa.'],
    ['Su descendencia, {n} hijos ({hijos}), recibió una educación esmerada y ocupó a su tiempo un lugar digno en el mundo.', 'Sus {n} hijos, {hijos}, fueron a la vez su orgullo y su pleito: las crónicas hablan de disputas por la herencia, de reproches y de reconciliaciones tardías, que acompañaron a la familia hasta el final.', 'Fue {padre|madre} de {n} hijos, {hijos}, y la historia anota que les tocó pagar las deudas de su casa: sangre, destierro y orfandad, cuyas huellas se advierten todavía en su descendencia.'],
    ['Los {n} hijos que tuvo, {hijos}, brillaban juntos en los muelles como un cúmulo de estrellas jóvenes, y el mundo veía en ellos la prolongación de su estirpe.', 'De su sangre nacieron {n} hijos, {hijos}, y cada uno heredó un fragmento de su fuego y una parte de su sombra; el eco de esas herencias ha ido de generación en generación sin que nadie consiga separarlas.', 'Trajo al mundo {n} hijos, {hijos}, y la sombra del destino cayó sobre ellos como cae la noche en los puertos sin sol: lutos, destierros, disparos en la oscuridad; la casa quedó reducida a un nombre hueco, y esa herencia pesó más que cualquier fortuna.'],
  ]);

  F('familia_sola', [
    ['Vivió sin pareja ni hijos.', 'Sin pareja ni hijos; rehuía toda compañía.', 'Sin pareja ni hijos. Todos los suyos murieron antes.'],
    ['Pasó la vida sin compañía estable ni descendencia, repartiendo los días entre el trabajo y la mesa de siempre, y no parecía echar nada en falta.', 'Nadie compartió su casa, nadie heredó sus manías; vivía sol{o|a} con la sospecha de que alguna vez estuvo a punto de tener algo mejor.', 'Quienes pudo haber amado se le fueron perdiendo por el camino, y llegó al final sin pareja, sin hijos y sin quien guardara su nombre.'],
    ['Su cuarto tenía sitio para {él|ella} y nada más: una litera ordenada, una ventana al muelle y una taza que nadie más usaba; no conoció pareja ni hijos, y en esa quietud encontró una libertad sin disculpas.', 'Rehuía los lazos como quien evita una fuga de presión: ni pareja que le esperase, ni hijos que le pidieran, y en las fiestas del puerto se retiraba pronto con el aire de quien oculta un hueco.', 'La vida le fue quitando compañías: la pareja que no llegó, los hijos que no nacieron, los amigos que partieron; envejeció entre muros silenciosos con la certeza de ser {el último|la última} de su linaje.'],
    ['Las crónicas no le conocen pareja ni descendencia, y la sobriedad de su vida privada contrasta con el ruido de su carrera; pasó los años entregad{o|a} a su obra y dejó a su casa por único heredero.', 'Su soledad fue elegida a medias y padecida a medias: los cronistas anotan ausencia de pareja y de hijos y sugieren, con cautela, que la ambición o el recelo ocuparon el sitio de los afectos.', 'Sin pareja ni hijos, su estirpe se extinguió con {él|ella}: se anotó con la sequedad con que se anotan las cosas irreparables, y en el hueco de aquella casa solo quedó el eco de sus pasos.'],
    ['No conoció pareja ni hijos: se dijo que había desposado a su destino, y que de esa unión quedaba en los muelles una sombra larga, de las que no se apagan con la luz de los días.', 'Anduvo sin compañía y sin descendencia, y quienes le rodeaban aprendieron a leer en esa soledad un orgullo: el de quien no se deja atar, aunque lo que le ata sea precisamente su falta de amarras.', 'Ni pareja ni hijos le sobrevivieron, porque no los tuvo: quedó su nombre solo, como un casco a la deriva, y cuando faltó, el mundo no halló a quién entregar sus llaves ni a quién rendir sus lágrimas.'],
  ]);

  // ── Ideas ─────────────────────────────────────────────────────────────────────────────────────────
  F('ideas_orden', [
    ['Defendía el orden y la autoridad.', 'Defendía el orden y despreciaba a los díscolos.', 'Defendió el orden aun cuando costó vidas.'],
    ['Creía en las cadenas de mando, en los horarios cumplidos y en las cosas en su sitio; para {él|ella} un puerto con orden era un puerto que sobrevivía.', 'Veía en la autoridad la única defensa contra el caos y tragaba con mal humor los desórdenes ajenos; los que cuestionaban lo establecido le parecían imprudentes y, en el fondo, peligrosos.', 'Sostuvo el orden establecido con dureza creciente: toleraba cada vez menos a los que lo discutían, y el peso de la regla, aplicado sin piedad, cayó sobre inocentes.'],
    ['Había en {él|ella} un amor a lo bien dispuesto: manifiestos al día, guardias relevadas a la hora, una jerarquía clara en la que cada cual conocía su sitio y encontraba en ello consuelo.', 'Creía que sin autoridad el mundo se desmoronaba, y no se cansaba de decirlo; cada insubordinación le sonaba a presagio, y trataba a los inquietos con la severa paciencia de quien cuida un reactor cerca del límite.', 'Quiso que todo siguiera como estaba y todo se lo llevó la corriente: defendió la ley hasta el último momento, vio caer una a una las certezas que la sostenían y no supo ver que lo que perdía no era un orden, sino una época.'],
    ['Fue defensor{|a} seren{o|a} de la autoridad: sostuvo las jerarquías y los hábitos de su tiempo con una convicción que contagió a sus subordinados y tranquilizó a los asentamientos que dependían de su firmeza.', 'Su fe en el orden era inflexible y le enemistó con los reformadores: vio en cada cambio una amenaza, en cada discrepancia una insolencia, y la historia anota su empeño como baluarte para unos y como cerrojo para otros.', 'Defendió el orden hasta ahogar toda disidencia: sus años quedaron marcados por la rigidez de una autoridad que no admitió réplica y por las víctimas que su celo, bien intencionado, fue dejando en el camino.'],
    ['Su palabra era regla y su regla, ley; en los muelles se ordenaba hasta el silencio al compás de sus pasos: creía que el mundo es una nave, y que una nave sin mando se rompe contra la primera roca.', 'Veneró la autoridad como si fuera un reactor sagrado, y contra los que la discutían alzó un muro de leyes y de miradas; el orden fue su credo y su celda, y a su sombra el mundo respiró con miedo y con alivio.', 'Quiso congelar el mundo en su forma y el mundo se le deshizo entre las manos: defendió la ley con la dureza de la desesperación, y los muros que levantó para contener el caos acabaron siendo el recinto de su derrota.'],
  ]);

  F('ideas_cambio', [
    ['Quería cambiar todo y desconfiaba de quien mandaba.', 'Discutía toda orden y pedía cambios.', 'Pidió cambios y le cerraron las puertas.'],
    ['Pensaba que nada de lo establecido merecía durar solo por costumbre; hacía preguntas incómodas en las asambleas y sonreía cuando la respuesta era que siempre se había hecho así.', 'Desconfiaba de cada uniforme, de cada sello y de cada discurso desde arriba; convencid{o|a} de que todo debía cambiar, vivía en un malestar constante con el mundo tal como era.', 'Quiso cambiarlo todo y chocó contra los de siempre: perdió puestos, amigos y parte de la salud empujando una puerta que los de arriba se empeñaban en mantener cerrada.'],
    ['Veía el mundo como un taller en obras: cada ley, cada jerarquía y cada costumbre era para {él|ella} una pieza que podía mejorarse, y hablaba de ello con la alegre terquedad de quien nunca ha esperado permiso.', 'Su desconfianza hacia quienes mandaban era un hábito del corazón: leía los edictos buscando la trampa y los discursos buscando el truco, y de esa suspicacia sacó, en proporciones iguales, lucidez y soledad.', 'Creyó que todo debía cambiar y lo gritó en las plazas de los puertos, y lo que cambió fue su propia vida: persecuciones, exilios, amigos que no volvieron; el mundo cedió, pero cedió despacio y sin {él|ella}.'],
    ['Su pensamiento, recogido en las crónicas, fue el de un reformador sin tregua: propuso cambiar leyes, rangos y costumbres, desconfió de los poderosos y su ejemplo inspiró a los inconformes de la época.', 'Los poderosos l{o|a} vieron como amenaza y los jóvenes, como bandera: su desconfianza ante la autoridad era una forma de lucidez, y su empeño en derribar lo viejo trazó una grieta que ya no hubo manera de cerrar.', 'Quiso demoler lo establecido y lo establecido se defendió: la historia registra las persecuciones que sufrió, los compañeros que perdió y la vigencia que sus ideas, a pesar de todo, conservaron en el tiempo.'],
    ['Cuentan que desconfiaba hasta de su sombra si esta daba órdenes, y que soñaba un mundo rehecho desde los cimientos; su palabra, cuando hablaba de cambio, hacía temblar los estandartes de quienes mandaban.', 'Era brasa bajo los tronos: allí donde había una orden, dudaba; allí donde había un cetro, cuestionaba; y cada dueño del poder oyó en su voz el crujido que anuncia las grandes caídas.', 'Pidió un mundo nuevo y el viejo le cobró la osadía: l{o|a} persiguieron, l{o|a} callaron, l{o|a} rodearon de soledad, pero su duda ante el poder quedó grabada en los muros, y los que vinieron después la leyeron como un testamento.'],
  ]);

  // ── Fama ──────────────────────────────────────────────────────────────────────────────────────────
  F('fama_ninguna', [
    ['Nadie fuera de su casa supo su nombre.', 'Su nombre no pasó de su casa, y eso le amargó.', 'Quienes conocían su nombre murieron sin repetirlo.'],
    ['Vivió y trabajó sin que su nombre saliera de las paredes de su casa, y lo prefirió así; la fama le parecía un ruido innecesario.', 'Nadie más allá de su puerta pronunció su nombre, y en esa oscuridad fue creciendo la sospecha de que merecía algo mejor, que el mundo ignoraba por pereza.', 'Murió sin que nadie fuera de su casa supiera que había existido, y quienes lloraron su ausencia lo hicieron en voz baja y entre pocas paredes.'],
    ['Su nombre era un asunto doméstico: lo sabían la mesa, las paredes y los vecinos de pasillo, y más allá de la esclusa familiar nadie habría sabido pronunciarlo, lo cual no parecía pesarle.', 'Ni un cronista, ni un registro, ni una conversación de muelle recogieron su nombre; vivió con el resquemor de quien hace cosas que no se cuentan y habla a quienes no escuchan.', 'El mundo no supo de {él|ella} ni siquiera cuando faltó: su nombre se apagó dentro de los muros de su casa, como un reactor que se enfría sin que nadie en el puerto note la bajada de temperatura.'],
    ['La crónica, que todo lo recoge, no recoge nada sobre su persona: ni un decreto, ni un parte, ni una queja con su firma, y de su paso por el mundo solo da fe el recuerdo de quienes compartieron su techo.', 'Fue un nombre que ninguna voz repitió fuera de su casa, y los historiadores apenas lo mencionan: sus rivales lo olvidaron pronto y sus aliados, más pronto aún, como si la sombra hubiera sido una elección de {él|ella} o de los demás.', 'Nadie fuera de su hogar supo su nombre, ni cuando vivió ni cuando murió; no hubo lamento público por {él|ella}, y su vida entera, con sus amores y sus penas, pasó por el mundo sin dejar marca.'],
    ['Su nombre no cruzó el umbral de su casa, y los cronistas, que lo escriben todo, se quedaron sin línea alguna para {él|ella}; fue una vida sin eco, como una estrella demasiado pequeña para ser vista desde el puerto.', 'Quiso ser oíd{o|a} y el mundo pasó de largo: su nombre quedó entre las paredes de su casa, y de la indiferencia universal nació un orgullo callado, el de quien sabe que su historia es grande aunque nadie la haya escrito.', 'El olvido l{o|a} cubrió antes de que fuera dicho su nombre: ni lápida, ni registro, ni palabra que dijera quién fue; apenas susurrado en la casa donde nació, se apagó con los últimos que lo oyeron, y del mundo no quedó rastro de que alguna vez hubiera estado.'],
  ]);

  F('fama_extendida', [
    ['Su nombre se conocía en {n} mundos.', 'Su nombre sonaba en {n} mundos, y a muchos molestaba.', 'Su nombre se maldecía en {n} mundos.'],
    ['La gente de {n} mundos sabía quién era: sus hechos llegaban en los manifiestos de carga y en las conversaciones de los puertos, y se recordaban, en general, con respeto.', 'En {n} mundos se pronunciaba su nombre con admiración o con rabia, según de qué lado del mostrador se oyera, y {él|ella} tenía la sensación de que nadie lo decía con indiferencia.', 'Su nombre corrió por {n} mundos, y no siempre como habría querido: se contaba como aviso y como amenaza, y a su paso las madres bajaban la voz.'],
    ['Los muelles de {n} mundos habían oído hablar de {él|ella}: viajeros, estibadores y escribanos repetían su nombre entre carga y carga, con la familiaridad que da la costumbre.', 'Se hablaba de {él|ella} en {n} mundos, con tonos dispares: reverencia en unos, recelo en otros, y en todos una curiosidad inquieta que ninguna desmentida lograba aplacar.', 'Su fama alcanzó {n} mundos y llegó teñida de luto: allí donde se pronunciaba su nombre, alguien recordaba una pérdida, una ruina o una deuda sin saldar, y el eco de aquello viajaba con {él|ella}.'],
    ['Su nombre era familiar en {n} mundos: constaba en los registros de puertos lejanos, se grabó en los muros de los depósitos y se enseñó, a su tiempo, a los hijos de quienes lo habían oído.', 'Su nombre se pronunciaba en {n} mundos como se pronuncia una promesa discutible: los poderosos lo ponderaban, los humildes lo comentaban y los cronistas lo anotaban con prudencia, sabiendo que la fama es un arma de doble filo.', 'Fue conocid{o|a} en {n} mundos y pagó la fama con la paz: su rostro apareció en carteles, en muros y en las listas de buscados, y la historia consigna el peso con que aquel renombre cayó sobre sus hombros.'],
    ['Su nombre cruzó el vacío entre {n} mundos y se instaló en cada uno como una constelación nueva: los niños lo aprendían junto a las estrellas, y los viejos lo decían con la voz de quien ha visto el curso de algo grande.', 'En {n} mundos se oía su nombre con un estremecimiento: hombres y mujeres, en la oscuridad de los muelles, lo repetían entre devoción y recelo, y su fama, enorme y vigilante, llegó a ser una segunda sombra que l{o|a} seguía por todas las órbitas.', 'Su fama recorrió {n} mundos como una estela de ceniza: allí donde llegó el nombre llegó también el duelo, y quienes lo oyeron lo grabaron en la piedra de los puertos, con letras hondas como heridas.'],
  ]);
})(typeof globalThis !== 'undefined' ? globalThis : this);
