// Frases del grupo «carrera». Cada hueco: 5 filas (épica 0..4) × 3 columnas (drama 0..2).
(function (g) {
  'use strict';
  const F = g.SIM.frases;

  // ── Cargos ──────────────────────────────────────────────────────────────────────────────────────────────
  F('cargo_gobernante', [
    ['Gobernó {estado}.', 'Ocupó el gobierno de {estado}; casi nadie le prestó apoyo.', 'Dirigió {estado}; hubo muertos durante su mandato.'],
    ['Alcanzó la jefatura de {estado} y la ejerció largos años sin grandes conflictos.', 'Se hizo con el gobierno de {estado}, aunque muchos de los suyos le discutían el puesto y esperaban su tropiezo.', 'Tuvo en sus manos {estado} durante una etapa de duelos y sangre de la que casi nadie de su círculo salió indemne.'],
    ['Tomó las riendas de {estado} en tiempos de calma y las llevó con la paciencia de quien sabe que un Estado se gobierna despacio, como se cuida un cultivo.', 'Subió a lo más alto de {estado} con las manos limpias a la vista y la sospecha pegada a la espalda como una segunda sombra.', 'Rigió {estado} bajo un cielo de entierros: cada año en el despacho grande le arrancaba a alguien querido, y aun así no soltó el mando.'],
    ['Presidió {estado} en una época de orden, y las crónicas recuerdan su mandato como un tiempo de depósitos llenos y puertos abiertos.', 'Ejerció el poder supremo de {estado} entre bandos enfrentados, y los cronistas coinciden en que gobernó siempre con un ojo puesto en la puerta.', 'Condujo {estado} por sus años más negros: bajo su gobierno las casas se vaciaron de hijos y los muelles se llenaron de luto.'],
    ['Cuando los mundos aún hablaban bajo, empuñó el mando de {estado}; se dice que con {pila} ni el grano ni la paz se echaron a perder.', 'Se sentó en el sillón del mando de {estado}, y desde entonces cada sombra del palacio repitió su nombre; nadie olvidó lo que costó ese asiento.', 'Reinó sobre {estado} como la tormenta sobre un puerto: lo cubrió todo, lo quebró todo, y cuando amainó solo su nombre seguía en pie.'],
  ]);

  F('cargo_gobernador', [
    ['Fue gobernador{|a} de {lugar}.', 'Nombrad{o|a} gobernador{|a} de {lugar}; allí no cayó bien.', 'Gobernó {lugar} por nombramiento; hubo disturbios y heridos.'],
    ['Recibió de la capital el gobierno de {lugar} y administró el asentamiento con puntualidad, mandando a tiempo cuentas y tributos.', 'Enviad{o|a} desde la capital para gobernar {lugar}, nunca logró que sus vecinos le tomaran cariño.', 'Regentó {lugar} por mandato de la capital durante una racha de motines y entierros que nadie logró contener.'],
    ['Llegó a {lugar} con el sello de la capital y gobernó con tal serenidad que los vecinos acabaron esperando sus decretos como se espera el cambio de turno en los muelles.', 'Sostuvo en {lugar} el sello de una capital lejana y poco querida, y gobernó entre miradas bajas y conversaciones que se cortaban cuando {él|ella} entraba.', 'Aceptó de la capital el mando de {lugar} justo cuando ardían las barricadas, y cada decreto que firmó dejó tras de sí una hilera de nombres tachados.'],
    ['Representó a la capital en {lugar} durante una larga etapa de orden, y el asentamiento prosperó bajo su administración: cada muelle ampliado y cada almacén lleno llevó su firma.', 'Al frente de {lugar} por voluntad de una capital que desconfiaba de todos, gobernó con firmeza y sin amigos; la crónica local recuerda aquel mandato como frío, correcto y temido.', 'Dirigió {lugar} en nombre de la capital durante las jornadas más oscuras de su historia: los archivos conservan sus órdenes y, junto a ellas, la lista de cuantos no volvieron a casa.'],
    ['Mandó en {lugar} como un astro tranquilo manda en su órbita: sin prisa, sin ruido y sin que nadie recordara cuándo empezó a obedecer.', 'Llevó a {lugar} el mandato de una capital ausente y lo ejerció con mano de hierro; en las noches del asentamiento se decía que los pasos de {nom} hacían callar hasta los motores.', 'Sobre {lugar} cayó su gobierno como cae la noche en un puerto sin faros: lenta, completa y con un nombre que aún se pronuncia en voz baja.'],
  ]);

  F('cargo_almirante', [
    ['Mandó la {flota}.', 'Fue almirante de la {flota}; los capitanes le obedecían de mala gana.', 'Tuvo a su cargo la {flota}; muchos de sus capitanes no volvieron.'],
    ['Recibió el mando de la {flota} y la mantuvo en orden: escuadras al día, maniobras regulares y dotaciones bien pagadas.', 'Ascendió a almirante al frente de la {flota}, pero los capitanes se repartían en bandos y cada orden suya llegaba discutida.', 'Condujo la {flota} por una campaña larga y mala, en la que fue enterrando oficiales y pidiendo naves que la capital ya no tenía.'],
    ['Paseó la {flota} por las rutas con una disciplina tan tranquila que los puertos abrían los muelles antes de que las escuadras pidieran paso.', 'Reunió bajo su insignia la {flota}, y las dotaciones {lo|la} seguían con ese respeto agrio que se tiene a quien manda bien y no perdona nada.', 'Arboló su insignia en la {flota} cuando la guerra ya devoraba escuadras: de cada salida regresaban menos cascos, y {él|ella} contaba por la noche los que faltaban.'],
    ['Ejerció el mando supremo de la {flota} en una era de rutas seguras y puertos prósperos; la crónica atribuye a su vigilancia que durante años no se perdiera un solo convoy.', 'Al frente de la {flota} cargó con la desconfianza de una capital que temía su prestigio; los cronistas lo anotan: una flota fiel a su almirante es siempre una amenaza para quien paga.', 'Comandó la {flota} en la hora más amarga: cuando regresó, faltaban más naves de las que volvían, y el parte de bajas ocupó más folios que el de victorias.'],
    ['Con la {flota} desplegada a sus espaldas parecía un astro rodeado de lunas: se cuenta que las escuadras se movían antes de que {pila} alzara la mano.', 'Hizo de la {flota} una sola voluntad: sus capitanes le juraron lealtad como se jura sobre una tumba, y ya no volvieron a pertenecerse.', 'Llevó la {flota} al fuego y regresó con el casco ennegrecido y la insignia intacta; de las naves que partieron con {él|ella}, el vacío guarda ahora los nombres.'],
  ]);

  F('cargo_general', [
    ['Fue general del ejército de {estado}.', 'Sirvió de general a {estado}; la tropa no le tenía aprecio.', 'Ascendió a general en {estado}; sus guarniciones sufrieron muchas bajas.'],
    ['Ingresó en el ejército de {estado} y fue subiendo escalón a escalón hasta el generalato, que desempeñó con competencia y sin estridencias.', 'Llegó a general de {estado} entre recelos: los políticos de la capital temían su influencia sobre las guarniciones y se lo hacían notar.', 'Mandó los ejércitos de {estado} en una campaña dura que dejó las guarniciones diezmadas y a {él|ella} sin dormir casi ninguna noche.'],
    ['Vistió el galón de general de {estado} con la seriedad de quien conoce el peso de cada vida confiada; sus soldados lo notaban y se lo pagaban con una lealtad callada.', 'Se convirtió en la espada de {estado} y en su inquietud a la vez: mientras vigilaba las fronteras, desde la capital vigilaban cada uno de sus pasos.', 'Marchó al frente del ejército de {estado} entre columnas de humo y listas de caídos que crecían cada mañana; cada noche revisaba los nombres de los muertos a la luz de una lámpara.'],
    ['Dirigió los ejércitos de {estado} durante un tiempo de firmeza, y bajo su estandarte las guarniciones se sintieron por primera vez parte de una sola fuerza.', 'Sostuvo la espada de {estado} en la hora en que la capital más temía a sus propios generales: los cronistas dejaron escrito que, de haberlo querido, sus tropas habrían marchado antes sobre el palacio que sobre el enemigo.', 'Condujo al ejército de {estado} a través de la peor campaña de su historia; los estados mayores aún discuten cómo se perdió tanta tropa y por qué {él|ella} no se rindió.'],
    ['Se dice que el ejército de {estado} era una sola armadura y que su corazón latía bajo la insignia de general: mientras mandó {pila}, ni una guarnición se rindió.', 'Empuñó el bastón de general de {estado}, y las tropas le dieron lo que ningún Estado sabe pedir: la lealtad sin condiciones. En la capital lo supieron y no durmieron tranquilos.', 'Al frente de los ejércitos de {estado} atravesó la noche más larga: a su paso quedaron tantas banderas rotas como nombres sin tumba, y aun así siguió adelante.'],
  ]);

  F('cargo_ministro', [
    ['Fue ministr{o|a} de {estado}.', 'Ocupó un ministerio de {estado}; tuvo enemigos en el consejo.', 'Firmó como ministr{o|a} de {estado}; hubo destituciones, exilios y muertes.'],
    ['Se encargó de las cuentas de {estado}: recaudó tributos, ordenó los archivos y mantuvo en pie un aparato que nadie más sabía manejar.', 'Llegó a ministr{o|a} de {estado} a fuerza de papeles y alianzas, y se mantuvo en el puesto vigilando a quienes querían quitárselo.', 'Administró los impuestos de {estado} en años de escasez, y cada decreto suyo tuvo su precio: despidos, requisas de grano y enemigos que no perdonaban.'],
    ['Manejó los tributos de {estado} con la exactitud de un reloj de muelle, y los legajos que salían de su despacho llevaban siempre la tinta justa y la intención justa.', 'Tejió entre los pasillos de {estado} una red de favores, deudas y silencios: nada se aprobaba sin su firma, y cada firma costaba un favor.', 'Sirvió a {estado} entre expedientes y puñales: vio caer a compañeros de consejo, firmó sus destituciones con pulso firme y pasó las noches en vela.'],
    ['Dirigió la hacienda y los papeles de {estado} en tiempos de bonanza; los cronistas le deben el orden de los archivos, y los pueblos, en buena parte, que los impuestos fueran por fin previsibles.', 'Entre las intrigas del consejo de {estado} sostuvo la hacienda con una mano y vigiló a sus enemigos con la otra; la crónica no sabe si {lo|la} temían más por sus cuentas o por su memoria.', 'Gobernó desde un despacho sin ventanas los papeles de {estado}, y bajo su sello se firmaron las leyes de aquellos años de ruina: los impuestos que vaciaron los graneros y las destituciones que vaciaron los pasillos.'],
    ['Tuvo en sus manos la bolsa y la pluma de {estado}; se cuenta que nada en el Estado se movía sin que {pila} lo supiera, y que la paz de aquellos años se escribía con su letra.', 'Hizo de la pluma un arma en {estado}: en el consejo su silencio pesaba más que los gritos ajenos, y quien cruzó su sello supo luego lo que cuesta una firma.', 'Contó las deudas de {estado} en una noche sin luna y firmó con la tinta más negra la ruina de media corte; los pasillos del palacio guardan aún el eco de su paso.'],
  ]);

  F('cargo_arzobispo', [
    ['Encabezó la iglesia de {estado}.', 'Presidió la iglesia de {estado}; sus clérigos discutían su elección.', 'Rigió la iglesia de {estado}; hubo cismas y condenas.'],
    ['Llegó a la cúspide de la iglesia de {estado} tras una vida de templo en templo, y desde allí ordenó el culto y los nombramientos con sobriedad.', 'Ocupó la silla más alta de la iglesia de {estado}, aunque una parte del clero no aceptaba su elección y recurría a la capital para minarla.', 'Dirigió a los fieles de {estado} durante una época de condenas y expulsiones; hubo templos cerrados y clérigos arrestados, y {él|ella} firmó casi todas las órdenes.'],
    ['Veló por la fe de {estado} desde el púlpito mayor con una voz que no necesitaba alzarse: bastaba su presencia para que los templos se llenaran de silencio.', 'Condujo la iglesia de {estado} entre dos fuegos, el de la capital, que quería un altar obediente, y el de los fieles, que querían un pastor; no contentó a ninguno y a ambos los sostuvo.', 'Guio a los fieles de {estado} por una época de templos incendiados; oficiaba entre las ruinas, de pie sobre el polvo, y los supervivientes aún repiten sus palabras como se repite un duelo.'],
    ['Estuvo al frente de la iglesia de {estado} en tiempos de bonanza, y bajo su báculo los templos se multiplicaron y los fieles se reconciliaron: la crónica anotó la mayor paz entre creyentes que se recordaba.', 'Pesó sobre {estado} su palabra: la iglesia que encabezó rivalizó con el poder civil, y cada sermón suyo fue leído en la capital con el temor con que se lee un parte de guerra.', 'Capitaneó la iglesia de {estado} en el tiempo de las condenas: firmó las sentencias, bendijo las piras y vio desde su sitial cómo los templos se llenaban de miedo; la crónica no {lo|la} absuelve.'],
    ['Su voz fue la voz de la iglesia entera de {estado}, y se dice que bastó para apagar discordias: cuando oficiaba {pila}, los puertos contenían el aliento y los muelles se quedaban quietos.', 'Alzó sobre {estado} una torre de fe que ni la capital supo derribar; se cuenta que ante sus fieles los poderosos bajaban los ojos, como ante un faro que no se deja apagar.', 'Se mantuvo como un faro sobre {estado} cuando el fuego caía de todos lados; murieron templos, murieron fieles, y su nombre quedó como queda lo último en la noche: una luz que nadie apagó del todo.'],
  ]);

  F('cargo_jefe_guardia', [
    ['Fue jef{e|a} de la Guardia de {estado}.', 'Dirigió la Guardia de {estado}; nadie confiaba en {él|ella}.', 'Mandó la Guardia de {estado}; hubo detenciones y desapariciones.'],
    ['Tomó la jefatura de la Guardia de {estado} y montó un archivo de fichas, informantes y celdas, todo con una eficacia silenciosa.', 'Ejerció la jefatura de la Guardia de {estado} sabiendo demasiado de todos; hasta sus superiores terminaron evitando su mirada.', 'Comandó la Guardia de {estado} durante una racha de arrestos y celdas llenas; en los barrios la gente bajaba la voz cuando se acercaban sus agentes.'],
    ['Gobernó en la sombra a través de la Guardia de {estado}: oía lo que se susurraba tras las puertas y archivaba lo que nadie se atrevía a decir, con la paciencia de quien sabe que el miedo trabaja solo.', 'Convirtió la Guardia de {estado} en un oído que llegaba a todas las casas: le temían los ministros y los generales, y {él|ella} sabía por qué.', 'Al mando de la Guardia de {estado}, abrió celdas que no figuraban en ningún plano y llenó los libros de nombres tachados; algunas noches los gritos llegaban hasta los despachos de la capital.'],
    ['Condujo la Guardia de {estado} en una época de calma vigilada: no hubo motines, y la crónica no sabe si fue por la justicia del régimen o por la eficacia de sus fichas.', 'Sobre {estado} se extendió la sombra de su Guardia: jef{e|a} de la policía del régimen, supo de cada conjura antes de que naciera y la ahogó en la cuna, y aún se pronuncia su nombre con cautela en las casas.', 'Presidió la Guardia de {estado} durante los años del terror; sus celdas se llenaron, sus archivos rebosaron de acusaciones y la crónica recuerda cada una de las puertas que se cerraron tras sus órdenes.'],
    ['Cuentan que la Guardia de {estado} no dormía porque {pila} no dormía, y que nada se murmuraba en todo el Estado que no llegara a su mesa antes del alba.', 'Imperó en la penumbra de {estado}: su Guardia tenía oídos en cada pared y ningún perdón, y de tanto callar los vivos aprendieron que el silencio también tiene dueño.', 'Hizo de la noche una ley en {estado}: al frente de la Guardia, borró nombres de las listas de los vivos con la misma pluma con que los apuntó, y los archivos aún guardan las fichas de los que nunca regresaron.'],
  ]);

  F('cargo_capitan', [
    ['Fue capitán{|a} de la {nave}, una nave mercante.', 'Mandó la {nave}, mercante; hubo un motín a bordo.', 'Gobernó la {nave}, mercante, y enterró a parte de su dotación.'],
    ['Asumió el mando de la {nave}, un mercante de línea, y la llevó de puerto en puerto cumpliendo plazos, cobrando fletes y esquivando líos con las aduanas.', 'Capitaneaba la {nave} con la contabilidad al límite: cada travesía dependía de un flete mal pagado, y la tripulación vivía con el temor de no cobrar.', 'Comandó la {nave} por rutas sin escolta; en una travesía enterró a parte de la tripulación y siguió el viaje porque la carga debía llegar.'],
    ['Mantuvo la {nave} impecable en todos los puertos, con la bodega siempre ordenada y las cuentas a la vista; las dotaciones se disputaban un puesto bajo su mando.', 'Navegó la {nave} sobre el filo de la quiebra, regateando fletes en cada muelle y escondiendo los números a una dotación que ya los intuía.', 'Sacó la {nave} de un puerto en llamas con la bodega medio vacía y la tripulación a medias, y desde entonces cada travesía le olió a ceniza.'],
    ['Capitán{|a} de la {nave} en la época en que el espacio entre los mundos se llenó de mercantes, hizo de su travesía una línea regular, y los muelles reconocieron que aquella nave jamás faltaba a su cita.', 'Con la {nave} cruzó rutas disputadas por flotas, aduanas y piratas, y los muelles de media galaxia guardaron su nombre como el de quien paga sus deudas y no cuenta de dónde saca los fletes.', 'Al mando de la {nave} soportó la ruina de una casa mercante: vendió la carga para pagar a la dotación, perdió el flete y vio cómo los acreedores esperaban en cada puerto con los papeles en la mano.'],
    ['Cuando las rutas eran apenas hilos tendidos entre mundos, llevó la {nave} de un puerto a otro como se lleva una promesa; no hubo carga que no llegara, y de eso se hizo su leyenda.', 'Hizo de la {nave} una ciudad en la oscuridad: los muelles encendían las luces de bahía a su paso, y las dotaciones juraban que {pila} se sabía de memoria el rumbo de cada estrella.', 'Condujo la {nave} por la noche más larga del comercio: perdió la carga, perdió la dotación, perdió el rumbo; y aun así, dicen en los muelles, siguió hablando de zarpar.'],
  ]);

  F('cargo_pirata', [
    ['Fue capitán{|a} pirata de la {nave}.', 'Mandó la {nave} como pirata; los puertos le cerraron las bahías.', 'Navegó como pirata en la {nave}; murió mucha gente en sus abordajes.'],
    ['Se hizo pirata al mando de la {nave} y vivió de asaltar mercantes en las rutas menos vigiladas, repartiendo el botín a partes iguales.', 'Dirigió la {nave} bajo una bandera que ningún puerto quería ver: compartía el botín con los suyos, pero la desconfianza en cubierta crecía con cada travesía.', 'Llevó la {nave} por rutas de saqueo; en cada asalto dejó cadáveres tras de sí y en cada puerto una recompensa por su cabeza.'],
    ['Gobernó la {nave} con la elegancia de quien roba sin alzar la voz: abordajes rápidos, tripulaciones respetadas y un botín que nunca faltaba en la cuenta de los suyos.', 'Hizo de la {nave} un nido de lobos: cada noche en cubierta era una votación a cuchillo, y {él|ella} conservaba el timón a fuerza de repartir más y temer menos.', 'Surcó el vacío en la {nave} dejando una estela de mercantes mudos y bodegas vacías, y con cada asalto crecía la lista de quienes juraban cobrarle la deuda.'],
    ['Lanzó la {nave} contra las rutas del comercio durante años, y las casas de seguros cambiaron sus tarifas por su culpa; los cronistas de los muelles guardan el recuerdo de aquella plaga del vacío.', 'Capitaneó la {nave} fuera de toda ley con una tripulación que ya no sabía pertenecer a ningún otro sitio; los Estados pusieron precio a su cabeza y la crónica anota que ninguno logró cobrarlo.', 'Condujo la {nave} por los años más sangrientos de la piratería: los abordajes dejaron cubiertas rojas y puertos de luto, y la crónica pesa con repugnancia el botín frente a las vidas.'],
    ['Cuentan los muelles que la {nave} no tenía puerto sino vacío, y que {nom} dormía con un ojo en la bodega y otro en las estrellas.', 'Con la {nave} enarboló una bandera hecha de hambre y desafío; los capitanes de los mercantes la nombraban en voz baja, como se nombra a lo que acecha en la oscuridad.', 'Dejó la {nave} en la memoria de las rutas como una cicatriz en el casco del mundo: cada abordaje fue una herida, cada botín una deuda de sangre, y su nombre quedó atado a ellas para siempre.'],
  ]);

  F('cargo_corsario', [
    ['Fue corsari{o|a} de {estado}, al mando de la {nave}.', 'Mandó la {nave} con patente de {estado}; el botín causó disputas.', 'Asaltó naves con la {nave} y patente de {estado}; hubo muertos.'],
    ['Recibió patente de {estado} para hostigar a sus enemigos, y al mando de la {nave} cumplió el encargo con puntualidad, entregando a la hacienda la parte que le tocaba.', 'Cruzó el espacio al mando de la {nave} con una patente de {estado} que protegía y condenaba a la vez: una paz en el papel y la sospecha de todos los puertos.', 'Capitaneó la {nave} bajo la patente de {estado} en una guerra sucia de abordajes nocturnos y rehenes; cuando {estado} firmó la paz, {él|ella} cargó con las culpas.'],
    ['Armó la {nave} con el visto bueno de {estado}: patente sellada, lista de objetivos y una reputación de buenos modales que los capitanes capturados contaron luego en los muelles.', 'Sirvió a {estado} con la {nave} y con la sospecha de que servía sobre todo a su bolsa; la patente le daba la ley, y el botín, la costumbre de olvidarla.', 'Zarpó con la {nave} y la patente de {estado} en el cofre, y volvió con cubiertas manchadas y cuentas que nadie quiso revisar; muchos de los abordados jamás regresaron a puerto.'],
    ['Corsari{o|a} al servicio de {estado}, hizo de la {nave} un brazo de la política sin uniforme: su patente abrió rutas a la flota y cerró las del enemigo, y los archivos de la hacienda anotan aquel servicio como uno de los más rentables.', 'Peleó con la {nave} para {estado} en una guerra sin nombre oficial, y al acabar el conflicto la patente quedó sin respaldo; la crónica anota la lección: la ley protege al corsario solo mientras le conviene.', 'Llevó la {nave} a una guerra de abordajes con la patente de {estado} por único amparo; dejó tras de sí naves incendiadas y tripulaciones muertas, y la crónica no sabe repartir entre la guerra y el botín la sangre vertida.'],
    ['Surcó el vacío con la {nave} y una patente de {estado}, y quienes la vieron pasar dijeron que era la ley con el casco negro; ningún enemigo supo cuándo llegaba, y todos supieron cuándo se iba.', 'Se hizo el filo oculto de {estado}: mientras la ley dormía en los despachos, {pila} despertaba en el vacío con la {nave}, y quien no entendía de patentes aprendía de abordajes.', 'Arrastró la {nave} por la guerra de {estado} como un cuchillo por una herida: la patente lo permitía todo, y el vacío aún guarda los pecios de todo lo que se permitió.'],
  ]);

  F('cargo_cabecilla', [
    ['Encabezó {faccion}.', 'Fue cabecilla de {faccion}; sus compañeros discutían su autoridad.', 'Dirigió {faccion}; hubo detenidos y muertos entre los suyos.'],
    ['Asumió la jefatura de {faccion} cuando nadie más quiso tomarla, y la llevó con constancia: reuniones, cuotas y una organización cada vez menos improvisada.', 'Se puso al frente de {faccion} entre rivalidades internas: unos exigían acción, otros prudencia, y {él|ella} tuvo que contentar a todos sin traicionar a ninguno.', 'Condujo {faccion} en una época de persecución: las detenciones diezmaron las filas, hubo compañeros que no volvieron y {él|ella} siguió adelante sin un respiro.'],
    ['Puso voz a quienes no la tenían, y {faccion} creció en torno a su palabra sencilla, repetida de taller en taller; quienes acudían a sus reuniones salían con la sensación de pertenecer a algo mayor que ellos.', 'Mantuvo unida {faccion} con alfileres: entre sus lugartenientes crecían los celos, en los pasillos circulaban los reproches, y {él|ella} gobernaba el descontento con la cautela con que se desactiva un núcleo averiado.', 'Arrastró tras de sí {faccion} por calles y muelles vigilados, enterrando compañeros y cambiando de refugio cada noche; de cada reunión salía con un nombre menos en la lista de los vivos.'],
    ['Al frente de {faccion} dio cuerpo a un descontento que hasta entonces no tenía nombre; los cronistas recogen que sus proclamas se leyeron en los muelles y que ni sus adversarios pudieron despreciarlas.', 'Gobernó {faccion} entre la clandestinidad y el poder, siempre a un paso del arresto y siempre a otro de la victoria; la crónica recuerda aquella etapa como una de las más temidas y más divididas de su tiempo.', 'Capitaneó {faccion} hasta el borde del abismo: en su nombre se levantaron barricadas y se llenaron las cárceles, y en las listas de caídos figuran muchos que creyeron en su palabra.'],
    ['Su voz levantó {faccion} como una marea levanta un casco varado: sin violencia aparente, sin prisa, con la certeza de quien sabe que el descontento tiene memoria.', 'Empuñó {faccion} como se empuña un filo sin vaina: con cuidado y con riesgo; cuentan que cada noche contaba a los suyos por si faltaba alguno, y que cada alba faltaba uno.', 'Hizo de {faccion} un incendio lento que alumbró todas las rutas y quemó a muchos de los suyos; el nombre de {nom} sigue sobre los muelles como una chispa que ningún viento apagó.'],
  ]);

  F('cargo_predicador', [
    ['Fue predicador{|a} itinerante.', 'Predicó de puerto en puerto; casi nadie le hacía caso.', 'Pasó hambre y palizas anunciando profecías de puerto en puerto.'],
    ['Recorrió los puertos con un hatillo y una voz clara, anunciando profecías en las plazas de los muelles a cuantos quisieran detenerse a oírlas.', 'Anduvo de muelle en muelle repitiendo sus profecías ante auditorios hostiles: unos reían, otros escupían, y los guardias vigilaban cada una de sus palabras.', 'Voceó sus profecías por los puertos en tiempos de epidemia; la gente {lo|la} escuchaba con terror y, a veces, {lo|la} apedreaba.'],
    ['Vivió de escala en escala con la profecía como único equipaje, y su voz, que nunca alzó, acabó siendo la que los estibadores esperaban al caer la tarde, junto a la sirena del último turno.', 'Lanzó desde las pasarelas de los muelles lo que otros callaban: profecías incómodas que los administradores quisieron acallar y que la gente aprendió a repetir con la boca pequeña.', 'Profetizó sobre muelles vacíos y puertos de luto, y cada vez que la desgracia llegaba a una escala, el pueblo se volvía hacia {él|ella} con una mezcla de reproche y de terror.'],
    ['Peregrinó de puerto en puerto durante una era de calma anunciando profecías de bonanza, y los cronistas dejaron constancia de que sus palabras apaciguaron más de una revuelta de hambre antes de estallar.', 'Llevó su voz de escala en escala en una época de bandos enfrentados; las autoridades de más de un puerto prohibieron sus profecías, y la crónica anota que fueron esas prohibiciones las que las hicieron célebres.', 'Atravesó los puertos anunciando la desgracia en los años negros; la crónica registra con espanto que cada ruina llegó con su palabra por delante, y que en los entierros se oía su nombre.'],
    ['Su voz viajaba más deprisa que las naves: cuentan que, antes de que {pila} atracara en un puerto, ya se esperaba a quien anunciaba el futuro con las manos vacías.', 'Se movió por los puertos como un presagio con piernas, y los poderosos temblaban al oír sus profecías; en las noches de espera, los guardias aseguraban que hasta los motores callaban cuando {él|ella} hablaba.', 'Anunció el fin entre muelles quemados, con la voz quebrada por el humo; los que la oyeron no supieron si era un grito o una elegía, y por si acaso la guardaron en la memoria como se guarda una advertencia.'],
  ]);

  F('cargo_mercader', [
    ['Fue cabeza de {faccion}, casa mercante.', 'Dirigió {faccion}, casa mercante; los socios discutían sus cuentas.', 'Presidió {faccion}, casa mercante; hubo quiebras y suicidios.'],
    ['Llevó {faccion} con buen pulso: fletes puntuales, deudores controlados y una flota pequeña que crecía cada año sin hacer ruido.', 'Se puso a la cabeza de {faccion} entre socios que se vigilaban unos a otros; la casa prosperaba, pero nadie confiaba en nadie.', 'Asumió {faccion} en plena crisis, vendió naves, despidió dotaciones y vio cómo algunos de sus capitanes se perdían con la carga sin que nadie los buscara.'],
    ['Hizo de {faccion} una casa de apellido temido y firma segura: sus fletes llegaban siempre, sus cuentas cuadraban siempre, y en los muelles bastaba su sello para abrir las bodegas.', 'Gobernó {faccion} como se maneja un tablero de intrigas: alianzas con aduanas, deudas sembradas en los puertos, rivales que desaparecían de las rutas sin dejar siquiera un parte de avería.', 'Sostuvo {faccion} a costa de sacrificios que no figuraban en ningún libro: sobornos, embargos, familias de acreedores arruinadas, y alguna noche en que el precio de una carga fue una vida.'],
    ['Al frente de {faccion} extendió las rutas comerciales sobre sistemas enteros; los archivos de las aduanas acreditan una época de intercambios regulares que llevó su sello de un puerto a otro.', 'Pilotó {faccion} con ambición y sin escrúpulos, comprando voluntades en los puertos y financiando bandos rivales; la crónica comercial recuerda aquel tiempo como uno de fortunas rápidas y alianzas que no sobrevivían a la siguiente cosecha.', 'Rigió {faccion} en los años del embargo y la peste del crédito: quebraron casas hermanas, se hundieron flotas enteras, y los archivos mercantiles guardan, junto a los balances, los nombres de quienes no sobrevivieron a las deudas.'],
    ['Cuentan que {faccion} llegó a tener más naves que estrellas había sobre un puerto, y que su sello valía más que la palabra de un Estado.', 'Tejió {faccion} como una araña teje una red entre los mundos: cada hilo una deuda, cada nudo un favor, y por el centro, silenciosa, pasaba la voluntad de {nom}.', 'Levantó {faccion} sobre una montaña de fletes y una fosa de deudas; cuando la casa cayó, se oyó el estrépito en todos los puertos, y en cada uno alguien pronunció su nombre con una mezcla de maldición y asombro.'],
  ]);

  F('cargo_funcionario', [
    ['Tuvo un cargo menor: {oficio} en {lugar}.', 'Ocupó en {lugar} un puesto menor ({oficio}); no cayó bien.', 'Su cargo menor, {oficio} en {lugar}, acabó en desgracia y lutos.'],
    ['Trabajó en {lugar} como {oficio}, un puesto sin brillo que ejerció con aplicación: llegaba pronto, rellenaba sus formularios y no se metía en líos.', 'Su empleo en {lugar}, {oficio}, era de los que nadie envidia: los superiores le echaban encima los errores ajenos y los vecinos le tenían por soplón.', 'Se vio atrapad{o|a} en {lugar} en su puesto de {oficio} cuando estalló el desorden, y firmó órdenes que le pesaron toda la vida.'],
    ['Desempeñó con meticulosidad el cargo de {oficio} en {lugar}, anotando con letra cuidada lo que otros decidían; los vecinos recordaban que jamás se equivocó en una cuenta.', 'Su cargo era {oficio} en {lugar}, y desde ese puesto sin poder veía pasar las órdenes de otros: {él|ella} las firmaba, otros las cumplían, y todos {lo|la} culpaban de lo que salía mal.', 'Cuando el desorden prendió en {lugar}, el humilde cargo de {oficio} que ocupaba {lo|la} puso en la línea de fuego: hubo que decidir quién se salvaba, y cada decisión pesó más que su sueldo.'],
    ['Cumplió en {lugar} el puesto de {oficio}, modesto pero esencial, y con él sostuvo durante años la maquinaria silenciosa sin la cual ningún Estado dura; los archivos conservan la regularidad de su letra.', 'Desde la oscuridad de un cargo menor en {lugar}, el de {oficio}, vio pasar a ministros, almirantes y facciones, y fue testigo de pactos que las crónicas no recogen; guardó silencio, y el silencio fue su único poder.', 'Le tocó en suerte el cargo de {oficio} en {lugar} cuando la historia se detuvo a mirar aquel lugar: firmó lo que se le ordenó, y en los registros de las víctimas queda, junto a cada nombre, la tinta de su pluma.'],
    ['Fue la pieza menuda de un gran mecanismo: {oficio} en {lugar}, sin gloria y sin falta; cuando el engranaje se detuvo, se echó en falta aquella pieza.', 'De cargos pequeños se hace la historia: como {oficio} en {lugar} vio enfrentarse a los grandes, y entre el polvo de sus pasos siguió firmando sin que nadie recordase su cara.', 'En {lugar} ejerció el cargo más pequeño de todos, el de {oficio}, y aun así su sombra cayó larga sobre los suyos: las decisiones que firmó, por menudas que parecieran, aún pesan sobre el nombre de aquel lugar.'],
  ]);

  F('cargo_ninguno', [
    ['No tuvo cargo; fue gente corriente de {lugar}.', 'Sin cargo en {lugar}, nadie le pidió nunca su opinión.', 'Pagó en {lugar} las decisiones de otros, sin cargo ni voz.'],
    ['Vivió en {lugar} como tantos otros, sin mando ni título: trabajaba, pagaba lo suyo y volvía a casa cuando acababa el turno.', 'Se quedó en {lugar} sin cargo ni influencia, mirando cómo los de arriba se disputaban lo que otros sudaban.', 'Resistió en {lugar} sin cargo ni protección alguna; cuando llegaron los malos años, la gente corriente pagó el precio, y {él|ella} lo pagó con los demás.'],
    ['Era un{o|a} de tantos vecinos de {lugar}, sin título ni sitio en las crónicas, y sin embargo su vida tuvo ese mérito callado de quien levanta cada día la casa con el trabajo de sus manos.', 'Presenció desde abajo, sin cargo ni apellido que importase, cómo {lugar} cambiaba de manos en un tiempo de bandos; aprendió a callar, a esconder la mirada y a decir que sí a quien llegara con un arma o con un sello.', 'Entre los de abajo en {lugar}, sin otro cargo que el de sobrevivir, perdió a los suyos uno a uno a manos del hambre y de las armas; quedó en pie, y esa fue toda su historia.'],
    ['Persona corriente de {lugar}, sin mando ni crónica propia, formó parte de esa multitud anónima sin la cual ningún Estado se sostiene: sus manos descargaron muelles, y su paciencia aguantó el orden.', 'Anduvo sin cargo por {lugar} cuando los cargos lo eran todo; no fue de ningún bando, y por no serlo, unos y otros desconfiaron de {él|ella} y los cronistas no dejaron rastro de su nombre.', 'Le tocó ser, entre los sin cargo de {lugar}, de los que la crónica nombra solo en las cuentas de los muertos: vivió sin título y sin eco, y su pérdida pasó por el libro de los daños.'],
    ['Estuvo en {lugar} sin cargo ni nombre, como las piedras de un muro: sosteniendo sin ser vistas, sin gloria, y sin embargo sin ellas el muro no se levanta.', 'Nunca fue nadie en {lugar}, y por eso lo supo todo: oyó las voces de los grandes desde abajo y comprendió que ninguna de ellas llegaría hasta su puerta.', 'Ni cargo, ni nombre, ni tumba señalada: así pasó por {lugar} y así desapareció, como esas gotas que la tormenta se lleva antes de saber que habían caído.'],
  ]);

  // ── Hechos ──────────────────────────────────────────────────────────────────────────────────────────────
  F('hecho_batalla_gana', [
    ['Ganó la batalla de {sistema} contra {enemigo}: {n} enemigos muertos.', 'Venció a {enemigo} en {sistema}; {n} bajas enemigas, mando dividido.', 'Derrotó a {enemigo} en {sistema}; {n} muertos enemigos y muchos propios.'],
    ['Dirigió la batalla de {sistema} y derrotó a {enemigo}: tras el combate se contaron {n} enemigos muertos, y las escuadras volvieron a puerto en buen orden.', 'Salió vencedor{|a} de la batalla de {sistema} contra {enemigo}, pero a un precio discutido: {n} enemigos muertos, un mando dividido y recriminaciones por quién había dado cada orden.', 'Se impuso en {sistema} frente a {enemigo} entre explosiones y pecios; quedaron {n} enemigos muertos y un campo de batalla sembrado de cuerpos propios y ajenos.'],
    ['Condujo la batalla de {sistema} con la frialdad de quien juega una partida ya ganada: las escuadras de {enemigo} se deshicieron una a una, y murieron {n} sin que la línea propia llegara a quebrarse.', 'Arrancó la victoria en {sistema} en una batalla de nervios contra {enemigo}, con las reservas agotadas y media flota dudando; al final pesaron los {n} enemigos muertos, no la conformidad de sus capitanes.', 'Alzó la victoria sobre {enemigo} en {sistema} sobre un campo de restos humeantes: {n} enemigos muertos, y entre los suyos más huecos en la lista que gritos de triunfo.'],
    ['Obtuvo en {sistema} la victoria que decidió la guerra contra {enemigo}: {n} enemigos cayeron en las órbitas del sistema, y la crónica fecha en aquellas jornadas el comienzo de una paz larga.', 'Libró en {sistema} una batalla entre dos desconfianzas: la de {enemigo}, que se sabía más débil, y la de sus propios capitanes, que dudaban de su mando; murieron {n} enemigos antes de que la duda se resolviera.', 'Triunfó sobre {enemigo} en {sistema}, pero la crónica anota que la victoria se pagó con un campo de cadáveres: {n} enemigos muertos y el luto instalado en las filas propias.'],
    ['En {sistema} puso a {enemigo} de rodillas en una sola jornada; {n} enemigos murieron bajo el fuego de {nom}, y los que sobrevivieron hablaron de aquella batalla como de una tormenta con rostro.', 'Cosechó en {sistema} la victoria sobre {enemigo} con la que se hacen las leyendas: {n} enemigos cayeron bajo su mando, y desde aquel día cargó con el peso de una fama que nadie sabe soportar.', 'Quebró a {enemigo} en {sistema}, y el vacío entero se llenó con {n} enemigos muertos; dicen que durante años las escuadras que cruzaban aquel sistema apagaban sus luces en silencio.'],
  ]);

  F('hecho_batalla_pierde', [
    ['Perdió la batalla de {sistema} contra {enemigo}.', 'Fue derrotad{o|a} por {enemigo} en {sistema}; culpó a sus capitanes.', 'Cayó derrotad{o|a} ante {enemigo} en {sistema}; hubo muchos muertos.'],
    ['Retiró sus naves de {sistema} tras una jornada de combate contra {enemigo} en la que no supo imponerse, y volvió a puerto a rendir cuentas con las bajas a cuestas.', 'Salió malparad{o|a} de la batalla de {sistema} frente a {enemigo}: culpó a la inteligencia, la inteligencia a los capitanes y los capitanes a {él|ella}, y nadie quedó contento.', 'Se vio superad{o|a} en {sistema} por {enemigo} y ordenó la retirada entre pecios y gritos; muchos de los suyos quedaron atrás y no volvieron a verse.'],
    ['Cedió {sistema} a {enemigo} con la serenidad de quien sabe cuándo una batalla está perdida, y salvó lo que pudo: las naves que importaban, los archivos y a parte de la dotación.', 'Abandonó el campo en {sistema} frente a {enemigo} con la sensación de haber sido engañad{o|a} por los mapas, por los capitanes y por su propia confianza; en la capital ya redactaban el reproche.', 'Vio caer sus escuadras una tras otra en {sistema} bajo el fuego de {enemigo}, y la derrota le dejó en la boca el sabor del metal quemado; contó los pecios en silencio y nunca pudo olvidar la cuenta.'],
    ['Encajó en {sistema} la derrota que {enemigo} llevaba años esperando; la crónica la juzga sin heroicidad pero sin vergüenza: se perdió la batalla, y la flota sobrevivió para otra guerra.', 'Sufrió en {sistema} ante {enemigo} la batalla que los suyos consideraban imposible de perder; los cronistas recogen las acusaciones, los consejos de guerra y los exilios que siguieron, y no logran decidir si el culpable fue {nom} o el azar.', 'Condujo a sus escuadras a la destrucción en {sistema} frente a {enemigo}; los partes de bajas, escritos con mano temblorosa, recogen nombres de naves y de dotaciones enteras desaparecidas, y la capital lloró durante días.'],
    ['Se batió en {sistema} contra {enemigo} hasta que no quedó casco al que dar la orden; perdió, y aun así los que sobrevivieron contaron aquella derrota como se cuenta un himno.', 'Dejó en {sistema}, ante {enemigo}, algo más que naves: dejó la certeza de ser invencible, y desde entonces sus propios capitanes vieron en {él|ella} a alguien que podía perder.', 'Contempló en {sistema} cómo el vacío se tragaba sus escuadras: {enemigo} lo arrasó todo, y de la flota que partió con {él|ella} no volvió ni la sombra; sobre aquella noche se cuentan aún las historias más oscuras de la guerra.'],
  ]);

  F('hecho_conquista', [
    ['Sus tropas tomaron {lugar}.', 'Conquistó {lugar}; hubo resistencia en los barrios.', 'Tomó {lugar} a la fuerza; hubo muertos entre los vecinos.'],
    ['Ordenó el avance sobre {lugar} y sus tropas fueron ocupando el asentamiento, calle a calle, hasta que no quedó guarnición que se resistiera.', 'Se apoderó de {lugar} tras un asedio largo, durante el cual la moral de sus tropas cayó tanto como la de los defensores y las órdenes se discutían en voz baja.', 'Entró en {lugar} con sus tropas en medio de incendios y gritos, y en cada portal hubo que pelear casa por casa; los vecinos recordaron luego el estruendo mucho más que la bandera.'],
    ['Hizo suya {lugar} con una operación limpia y paciente: cortó las rutas, apagó las luces y esperó a que la guarnición saliera por su propio pie, de modo que la ocupación se hizo casi en silencio.', 'Cercó {lugar} y la fue ahogando barrio por barrio; entre sus oficiales crecieron las dudas sobre la necesidad de tanto sacrificio, y la ocupación terminó dejando más rencores que botín.', 'Abrió paso a sus tropas por {lugar} entre humo, cascos de metal y portales reventados; cada casa tomada dejó un cuerpo en el umbral, y al caer la tarde los pasillos olían a metal quemado y a duelo.'],
    ['Lanzó sus tropas sobre {lugar} al frente de una columna disciplinada que avanzó casa por casa sin saqueo ni desorden; las crónicas anotan que pocas conquistas fueron tan limpias ni tan completas.', 'Se alzó con {lugar} en una campaña de asedio y traición, en la que el asentamiento se vendió por partes y los vecinos aprendieron que de una ocupación nadie sale igual que entró; los cronistas no perdonan ni a unos ni a otros.', 'Arrasó {lugar} casa por casa, sin piedad: la conquista dejó un asentamiento en ruinas y una lista de muertos que los archivos aún se niegan a cerrar.'],
    ['Cuentan que {lugar} cayó sin que nadie oyera el ruido de la caída: sus tropas avanzaron como un amanecer sobre un puerto dormido, y cuando los vecinos despertaron ya vivían bajo otra bandera.', 'Convirtió {lugar} en la prueba de su voluntad: sus tropas tomaron cada casa como se toma una ciudadela, y los defensores aún dicen que lucharon contra una riada que no conocía la fatiga.', 'Por {lugar} pasaron las tropas de {nom} como una tormenta de hierro: casa tras casa, puerta tras puerta, y de cada una salió un silencio más hondo que el anterior; el asentamiento aún conserva el eco de aquel paso.'],
  ]);

  F('hecho_defensa', [
    ['Defendió {lugar} de un asalto y aguantó.', 'Resistió en {lugar} un asalto; la guarnición estaba dividida.', 'Aguantó en {lugar} un asalto; la guarnición sufrió muchas bajas.'],
    ['Organizó la defensa de {lugar} con lo poco que tenía: reforzó las puertas, repartió munición y mantuvo en pie la guarnición hasta que el asalto se agotó.', 'Sostuvo {lugar} durante un asalto que nadie creía poder resistir, pero también ante los suyos, que murmuraban que habría sido más sensato rendirse.', 'Mantuvo {lugar} bajo un asedio sin descanso, con la guarnición diezmada y los depósitos casi vacíos; el asalto se rompió contra las barricadas, pero a un precio de muertos que no se olvidó.'],
    ['Plantó cara en {lugar} a un asalto superior, y lo hizo con una calma que contagió a la guarnición: cada puerta sostenida, cada pasillo disputado, hasta que el enemigo comprendió que no habría rendición.', 'Cerró {lugar} como se cierra un puño: con terquedad, con rabia, con la desconfianza de quienes sabían que la ayuda no iba a llegar; el asalto se estrelló, pero la capital tardó en perdonar el tono de sus partes.', 'Se parapetó en {lugar} con la guarnición que le quedaba y aguantó el asalto entre humo y escombros; al amanecer los muertos de ambos bandos llenaban los pasillos, y los vivos no tenían fuerzas para festejar.'],
    ['Estuvo al frente de la defensa de {lugar} durante el asalto más duro de su historia, y resistió con una firmeza que los cronistas elevaron a ejemplo: ni se rindió la guarnición ni se perdió una sola esclusa.', 'Contuvo en {lugar} el asalto más temido de aquellos años, pero la crónica no olvida que lo hizo desobedeciendo órdenes de repliegue; aguantó, y la capital tuvo que premiar lo que antes habría castigado.', 'Se atrincheró en {lugar} mientras el asalto caía sobre el asentamiento como una lluvia de acero; los cronistas anotan los nombres de los caídos y la obstinación de quien, con todo perdido salvo la voluntad, no abrió las puertas.'],
    ['En {lugar} se detuvo un alud de hierro: allí donde {pila} plantó los pies el asalto se quebró, y las guarniciones de otros mundos cuentan aún que ni el fuego ni el hambre pudieron arrancar a aquel puñado de gente.', 'Convirtió {lugar} en un muro y a su guarnición en un juramento: el asalto vino, el asalto se fue, y los que aguantaron nunca perdonaron del todo a los que tardaron en llegar.', 'Dicen que {lugar} no cayó porque {él|ella} se negó a que cayera: ardieron las bodegas, murieron los centinelas, y aun así su voz siguió ordenando resistir hasta que el asalto se deshizo contra el silencio de las ruinas.'],
  ]);

  F('hecho_masacre', [
    ['Mandó disparar contra la gente en {lugar}: {n} muertos.', 'Ordenó abrir fuego contra la multitud en {lugar}; {n} muertos y protestas.', 'Dio la orden de disparar en {lugar}; murieron {n} personas desarmadas.'],
    ['Dispuso que sus tropas abrieran fuego contra la gente reunida en {lugar}; hubo {n} muertos, y el informe oficial habló de disturbios controlados.', 'Autorizó el fuego contra la multitud de {lugar} y no lo detuvo hasta que ya habían muerto {n} personas; luego los mandos discutieron quién dio la primera orden.', 'Puso a sus tropas en las galerías de {lugar} con orden de disparar contra la multitud; murieron {n} personas, entre ellas niños y ancianos, y en la plaza quedó el olor del metal caliente.'],
    ['Pronunció la orden de fuego en {lugar} con la voz sin temblor de una consigna rutinaria; cuando cesó, {n} personas yacían en las galerías, y el silencio que siguió fue más largo que cualquier discurso.', 'Selló las salidas de {lugar} y abrió fuego sobre la multitud; murieron {n} personas, y durante años los vecinos susurraron que {él|ella} había mirado desde una ventana y no apartó la vista.', 'Atrapó a la multitud de {lugar} entre puertas cerradas y dejó que sus tropas dispararan; cayeron {n} personas bajo el fuego, y los supervivientes aún cuentan los rostros que no volvieron a casa.'],
    ['Dejó una mancha en la historia de {lugar}: mandó que se disparase sobre la multitud, y {n} personas murieron aquel día. Los cronistas lo consignan sin adjetivos, porque ningún adjetivo basta.', 'Firmó la orden de fuego en {lugar}, y por esa firma se pagó: murieron {n} personas desarmadas, y en los años siguientes las crónicas, las plazas y los muelles ya no hablaron de otra cosa.', 'En {lugar} sus tropas dispararon sobre la multitud por orden suya, y la historia guarda el número de los muertos sin consuelo: {n} personas cuyos nombres se leen hoy en los muros del asentamiento.'],
    ['Unió su nombre al de {lugar} con una orden que ninguna piedra quiere guardar: sus tropas dispararon sobre la multitud, y {n} personas no volvieron a casa. Las generaciones lo recuerdan en voz baja, como una herida.', 'Impuso a {lugar} la quietud a fuego: murieron {n} personas bajo las órdenes de {nom}, y desde entonces el asentamiento calla, y ese callar no es paz, sino memoria.', 'Hizo llover el fuego sobre {lugar}, y las plazas se llenaron de nombres sin dueño: {n} muertos, y una orden que los cronistas copiaron con la mano temblorosa, porque ni los siglos la vuelven pequeña.'],
  ]);

  F('hecho_reprime', [
    ['Aplastó una insurrección armada en {lugar}.', 'Sofocó una revuelta en {lugar}; la población quedó resentida.', 'Reprimió una revuelta en {lugar}; hubo muchos muertos y presos.'],
    ['Reunió a sus tropas y marchó sobre {lugar}, donde una insurrección armada había tomado los muelles; en pocos días recuperó el control y restableció los turnos de trabajo.', 'Acabó con la insurrección armada de {lugar} gracias a refuerzos llegados a última hora, y luego tuvo que convivir con una población que no le perdonaba las detenciones.', 'Rompió la insurrección armada de {lugar} a sangre y fuego; las calles quedaron cubiertas de cascotes y cadáveres, y las cárceles, de rebeldes.'],
    ['Cerró el cerco en torno a {lugar} con paciencia de cazador: cortó los suministros, esperó a que los insurrectos se quedaran sin aire y sin ideas, y los redujo con más habilidad que ensañamiento.', 'Doblegó la insurrección de {lugar} entre promesas y amenazas, con una mano tendida y otra cerrada; los rebeldes depusieron las armas, pero los vecinos se quedaron con la certeza de que habían sido engañados.', 'Hundió la revuelta armada de {lugar} bajo un temporal de fuego: los insurrectos cayeron en sus barricadas, y el asentamiento amaneció cubierto de humo, de silencio y de nombres que ya nadie osaba pronunciar.'],
    ['Restableció el orden en {lugar} tras una insurrección armada que había puesto en vilo al Estado entero; los cronistas elogian su serenidad y su rapidez, aunque dejan constancia de cuán costosa fue la calma.', 'Venció a los insurrectos de {lugar} en una campaña de calles y almacenes que dividió a sus propios oficiales; la crónica registra su victoria con la frialdad con que se registra un pacto con el miedo.', 'Anegó en sangre la insurrección armada de {lugar}: tras los combates vinieron las ejecuciones sumarias, las deportaciones y los registros casa por casa, y la historia no {lo|la} olvida ni {lo|la} perdona.'],
    ['Cuentan que bastó la sombra de {pila} para que la insurrección de {lugar} se rindiese: las armas cayeron al suelo antes de que el primer disparo llegara a oírse, y la paz que siguió pesó como una lápida.', 'Domó {lugar} como se doma un animal herido: con el látigo y el silencio; los rebeldes tardaron una generación en volver a levantar la voz, y cuando lo hicieron fue contra otros.', 'Hizo de la insurrección de {lugar} una pira: las barricadas ardieron, los cabecillas colgaron de las vigas del muelle, y por muchos años los vecinos siguieron barriendo la ceniza de aquellos días sin atreverse a levantar la vista.'],
  ]);

  F('hecho_revolucion', [
    ['Encabezó una revolución que triunfó en {lugar}.', 'Dirigió el alzamiento que ganó {lugar}; los viejos amos huyeron.', 'Lideró la revolución de {lugar}; el triunfo costó muchos muertos.'],
    ['Reunió a estibadores, obreros y soldados descontentos y, juntos, tomaron {lugar}; el viejo poder cayó sin demasiada resistencia y se formó un consejo provisional.', 'Se puso al frente de la revolución de {lugar} cuando ya no había vuelta atrás, y aunque el alzamiento triunfó, vio cómo sus aliados empezaban a vigilarse entre sí.', 'Condujo la revolución de {lugar} a la victoria sobre cadáveres y barricadas; el viejo orden cayó, pero a un precio de muertos que enlutó a todas las casas del asentamiento.'],
    ['Hizo de las calles de {lugar} un solo clamor, y la revolución triunfó con la naturalidad de una marea: los guardias bajaron las armas, los depósitos se abrieron, y por unas semanas el asentamiento creyó que nada era imposible de cambiar.', 'Sacó adelante la revolución de {lugar} entre traiciones y sospechas, pactando en la noche lo que negaba por el día; ganó, y la victoria le supo a ceniza.', 'Cruzó la revolución de {lugar} entre barricadas y fusilamientos; cuando por fin se arriaron las banderas viejas, había más duelo que fiesta en las calles, y {él|ella} caminó entre los muertos con la bandera nueva en la mano.'],
    ['Alzó {lugar} contra el viejo poder y la revolución triunfó: la crónica la cuenta como el comienzo de una era, y no hay historiador que no deba empezar por {nom} al escribir sobre aquellos años.', 'Ganó {lugar} para la revolución en un tiempo de bandos y rencores, y la crónica anota que sus aliados fueron tan peligrosos como sus enemigos; el poder nuevo nació dividido, y esa división marcó todo lo que vino después.', 'Fue el rostro de la revolución que triunfó en {lugar}, y por esa gloria pagó el precio de ver caer a sus compañeros uno a uno; la crónica guarda cada nombre con el respeto que merece lo irrecuperable.'],
    ['Cuando {lugar} despertó, ya era otro: se dice que el alzamiento que {él|ella} encendió prendió sin ruido, de puerta en puerta, y que al caer la tarde los poderosos del asentamiento ya no tenían a quién mandar.', 'Encendió la revolución de {lugar} como quien enciende un núcleo sin blindaje: triunfó, pero el calor no dejó de crecer, y los que ganaron con {él|ella} acabaron quemándose entre sí.', 'Sostuvo con las manos ensangrentadas la revolución de {lugar}, que triunfó sobre un lecho de muertos: de aquella victoria quedó la libertad, y quedó también el nombre de cada caído, grabado en el muro de la plaza.'],
  ]);

  F('hecho_insurreccion_falla', [
    ['Encabezó una insurrección en {lugar} que fue aplastada.', 'Sublevó a los suyos en {lugar}; la insurrección fracasó y tuvo que huir.', 'Dirigió una insurrección en {lugar}; la aplastaron y murieron muchos.'],
    ['Reunió armas y gente en {lugar} y se alzó contra el poder, pero la insurrección fue aplastada en pocos días y tuvo que esconderse para no ser capturad{o|a}.', 'Convocó a la gente de {lugar} a la insurrección, y esta fracasó entre acusaciones: unos culparon a los traidores, otros a los cobardes, y todos a {él|ella}.', 'Condujo la insurrección de {lugar} hasta el aplastamiento: muchos de sus compañeros murieron en las barricadas o ante el pelotón de ejecución, y {él|ella} pasó semanas huyendo con el peso de cada nombre.'],
    ['Alzó la bandera de la insurrección en {lugar} con una fe tan serena que casi parecía ya victoria; la respuesta del poder fue rápida y total, y {él|ella} vivió desde entonces de aquel recuerdo como se vive de una brasa guardada.', 'Soñó con {lugar} libre y se lanzó a la insurrección sin los números suficientes; cuando los refuerzos no llegaron y la gente se quedó en casa, comprendió que las revoluciones, como las naves, necesitan algo más que valor para despegar.', 'Vio morir la insurrección de {lugar} entre humo y fusilamientos, y a sus compañeros caer uno tras otro en las barricadas; escapó, sí, pero el eco de aquellas descargas {lo|la} acompañó el resto de su vida.'],
    ['Encendió en {lugar} una insurrección que la crónica recoge con respeto aunque terminara aplastada: no consiguió el poder, pero dejó sentado que el poder podía ser discutido, y esa semilla germinó después en otros mundos.', 'Se levantó contra el poder en {lugar} y fue aplastad{o|a}: los cronistas se dividen entre quienes ven en aquello una imprudencia y quienes ven un acto de dignidad, y ambos tienen razón.', 'Pagó con sangre la insurrección de {lugar}: tras la derrota vinieron las ejecuciones, los registros casa por casa y las listas de proscritos, y entre los nombres que figuraron en ellas estaban casi todos los que {él|ella} había querido salvar.'],
    ['Perdió la insurrección de {lugar}, pero no su voz: se cuenta que aquella noche las banderas del asentamiento se agitaron sin viento, y que el eco de la llamada de {pila} tardó años en apagarse.', 'Arrojó a {lugar} la semilla de la insurrección y la vio morir antes de brotar; los que la acompañaron {lo|la} llamaron imprudente, y los que vinieron después, profeta.', 'Dejó en {lugar} una insurrección aplastada y un reguero de nombres tachados; dicen que desde entonces, cada año, en la fecha de su derrota, el asentamiento apaga las luces durante un rato y escucha: algo, en el silencio, todavía resiste.'],
  ]);

  F('hecho_golpe', [
    ['Dio un golpe y tomó el poder en {estado}.', 'Tomó {estado} por sorpresa; los ministros callaron.', 'Derribó al gobierno de {estado}; hubo disparos y detenidos.'],
    ['Reunió a los mandos que le debían favores y, una noche, ocupó los edificios del gobierno de {estado}; al amanecer, el poder ya estaba en sus manos y las naves seguían su rutina.', 'Planeó y ejecutó un golpe en {estado} con el respaldo justo y la prisa de quien sabe que no hay segunda ocasión; ganó, pero los que le ayudaron empezaron a cobrar enseguida.', 'Asaltó el poder en {estado} con tropas leales y mano dura: hubo disparos en los pasillos del palacio, ministros muertos y una noche de arrestos que dejó a {estado} sin voz.'],
    ['Se hizo con {estado} en una madrugada ordenada y casi silenciosa: unos sellos cambiaron de manos, un par de guardias miraron hacia otro lado, y el viejo poder se despertó sin saber cuándo lo había perdido.', 'Conspiró durante meses hasta consumar en {estado} un golpe más de desconfianza que de fuerza: los ministros le abrieron las puertas con la sonrisa torcida de quien cede para sobrevivir.', 'Cercó el palacio de {estado} y lo tomó entre tiros y gritos; cayeron guardias, cayeron ministros, y al amanecer {él|ella} firmó el primer decreto con la mano todavía manchada.'],
    ['Alcanzó el poder en {estado} mediante un golpe sin sangre, y las crónicas observan que, aunque nació de la fuerza, se mantuvo con una prudencia que apaciguó a los más díscolos.', 'Quebró el orden legal de {estado} con un golpe de mano que dividió al ejército y a la población; los cronistas lo juzgan duramente: ganó el poder, pero lo ganó a costa de una lealtad que nunca volvió a ser plena.', 'Con las armas en la mano se adueñó de {estado}: el golpe dejó la capital sembrada de cadáveres, y la historia guarda con espanto la lista de los depuestos, los desaparecidos y los que por callar fueron perdonados.'],
    ['Una noche bastó para cambiar el destino de {estado}: sin ruido y sin sangre, {pila} empuñó el poder como quien recoge un fruto maduro, y los mundos tardaron en comprender que ya habían cambiado de dueño.', 'Se alzó con {estado} como se alza un filo en la oscuridad: nadie vio la mano, todos sintieron el corte; los que hasta entonces mandaban comprendieron demasiado tarde que su tiempo se había acabado.', 'Hizo de {estado} un teatro de sombras y fuego: el golpe arrancó de cuajo el viejo gobierno, la capital ardió durante la noche, y quien despertó al día siguiente lo hizo ya en un mundo que llevaba su nombre.'],
  ]);

  F('hecho_purga', [
    ['Purgó a {n} rivales para que nadie le disputara el poder.', 'Apartó del poder a {n} rivales; hubo exilios y recelos.', 'Hizo desaparecer a {n} rivales; su cargo nunca estuvo tan seguro.'],
    ['Fue retirando uno a uno a {n} rivales de los puestos que le estorbaban, y cuando terminó nadie quedaba en el consejo con fuerza para discutirle una orden.', 'Se deshizo de {n} rivales con acusaciones, destituciones y alguna que otra detención discreta; tuvo el poder más seguro, pero dormía peor.', 'Mandó detener y ejecutar a {n} rivales en una sola oleada; los cuerpos se contaron después, y los supervivientes del consejo no volvieron a levantar la voz.'],
    ['Limpió el consejo con una paciencia casi administrativa: {n} rivales fueron saliendo por la puerta de atrás, unos al exilio, otros a un cargo sin poder, y {él|ella} no necesitó alzar la voz para quedar sol{o|a} en la cima.', 'Despejó su camino de {n} rivales mediante una mezcla de lisonjas y amenazas, y aunque nadie pudo acusar{lo|la} de nada concreto, los pasillos del poder aprendieron a mirar hacia otro lado cuando su nombre sonaba.', 'Derribó a {n} rivales en una sola temporada de lutos: unos en la cárcel, otros en el exilio, otros bajo tierra; y cuando el último se fue, {él|ella} se quedó sol{o|a} en el despacho grande y ya no pudo confiar ni en su sombra.'],
    ['Ordenó una purga metódica contra {n} rivales, y los cronistas describen con asombro su disciplina: ni una sola voz quedó en pie que pudiera disputarle el mando, y la paz que siguió fue la de un edificio sin ventanas.', 'Depuró el consejo de {n} rivales en una campaña de acusaciones cruzadas y juicios apresurados; los archivos conservan los expedientes, y la crónica anota con amargura que algunos de los purgados habían sido amigos suyos.', 'Segó de un solo golpe el futuro de {n} rivales: la purga vació despachos, cárceles y fosas, y la crónica, que registra sus nombres uno a uno, no halla manera de decir que el poder asegurado valiera tanta sangre.'],
    ['Barrió el consejo como el fuego barre un hangar abierto: {n} rivales desaparecieron del mundo, y cuando se hizo el silencio, el poder que quedó era tan limpio como el hueco de una tumba.', 'Alzó el filo contra {n} rivales una noche y lo bajó al amanecer; no quedó quien le disputase el mando, pero tampoco quedó nadie en quien confiar, y el poder le supo a metal frío.', 'Dejó tras de sí {n} rivales borrados de la historia y un palacio donde el eco habitaba cada sala; cuentan que en las noches sin luna se oye pasar la lista de los nombres, y que ni la piedra consigue olvidarlos.'],
  ]);

  F('hecho_guerra', [
    ['Declaró la guerra a {enemigo}.', 'Cortó relaciones con {enemigo} y declaró la guerra; el consejo dudó.', 'Llevó a su gente a la guerra contra {enemigo}; murieron muchos.'],
    ['Movilizó a las flotas y a las guarniciones contra {enemigo} tras rechazar un último tratado; la guerra se declaró con el orden de quien llevaba meses preparándola.', 'Empujó a su gente a una guerra contra {enemigo} que muchos en el consejo juzgaban prematura; la declaración se firmó entre murmullos y la víspera se pasó en vela.', 'Lanzó el desafío a {enemigo} con la guerra ya en el aire; cuando se declaró, había muertos en las fronteras y duelo en las casas, y ya nadie creía en una salida pactada.'],
    ['Rompió con {enemigo} tras una larga cadena de agravios y selló la guerra con una declaración sobria, casi administrativa; en los muelles se comprendió que el tiempo de los acuerdos había pasado.', 'Dictó contra {enemigo} una declaración de guerra que muchos llamaron ambiciosa y otros temeraria; el consejo la votó con los dientes apretados, y {él|ella} supo desde esa noche que, ganase o perdiese, la historia le pediría cuentas.', 'Envió a {enemigo} una declaración de guerra breve y fría; las primeras escuadras salieron antes de que la tinta se secase, y en las casas se empezó a hablar de quienes no volverían.'],
    ['Proclamó la guerra contra {enemigo} desde el salón mayor, ante un consejo en pie; las crónicas fechan en aquel día el comienzo de una era de flotas en movimiento y rutas cerradas.', 'Abrió contra {enemigo} una guerra que no deseaba nadie salvo {nom} y que, sin embargo, todos acabaron sufriendo; los cronistas discuten aún si la declaró por necesidad o por soberbia.', 'Hizo de {enemigo} el blanco de su ira y declaró una guerra que habría de segar generaciones; la crónica anota la fecha con el mismo pesar con que se anota una pérdida irreparable.'],
    ['Su voz declaró la guerra a {enemigo}, y las estrellas de la frontera parecieron encenderse a la vez: se cuenta que de cada puerto salieron flotas como ríos de luz, y que ningún mundo quedó fuera de aquel llamado.', 'Levantó la mano contra {enemigo} y declaró una guerra de la que nadie volvería a hablar sin bajar la voz; el vacío aguardó, y el fuego vino, como había venido siempre que alguien con mando decidió que la paz estorbaba.', 'Arrojó a los suyos contra {enemigo} como quien arroja una antorcha en un almacén de núcleos: la guerra prendió, y en pocos años el nombre de {enemigo} y el suyo quedaron unidos en la memoria de todos los lutos.'],
  ]);

  F('hecho_abre_deposito', [
    ['Abrió el depósito de grano de {lugar} sin disparar.', 'Se negó a disparar en {lugar} y abrió el depósito; ganó enemigos.', 'No disparó en {lugar}; abrió el depósito, tarde para algunos.'],
    ['Ante la multitud hambrienta de {lugar} rechazó dar la orden de fuego y mandó abrir el depósito de grano; el reparto se hizo en orden y nadie resultó herido.', 'Desobedeció a la capital: en lugar de disparar contra la multitud de {lugar}, abrió el depósito de grano y repartió lo que había, sabiendo que le pedirían cuentas.', 'Mandó romper el candado del depósito de grano de {lugar} cuando ya había gente muerta de hambre junto a las puertas, y se negó a disparar contra la multitud que quedaba; llegó tarde para algunos, y lo supo.'],
    ['Salió ante la multitud hambrienta de {lugar} con las manos vacías y los guardias a su espalda, y dio la orden contraria a la esperada: bajar las armas y abrir el depósito de grano; la plaza respiró como un cuerpo al que devuelven el aire.', 'Impidió que sus guardias dispararan contra la multitud de {lugar} y, sabiendo que firmaba su sentencia política, franqueó el depósito de grano; la gente comió aquella noche, y en la capital ya redactaban su destitución.', 'Cruzó la plaza de {lugar} entre cuerpos hambrientos y fusiles que dudaban, y rompió con sus propias manos el precinto del depósito de grano; no todos llegaron a comer, y {él|ella} cargó con los que no.'],
    ['Rehusó abrir fuego contra la multitud hambrienta de {lugar} y entregó a la gente el depósito de grano; las crónicas anotan el gesto como el de quien prefirió la vida a la disciplina, y el asentamiento no lo olvidó en generaciones.', 'Contra las órdenes de la capital, desatrancó el depósito de grano de {lugar} y se negó a disparar sobre la multitud; los cronistas coinciden en que aquel acto le costó el cargo y le dio, a cambio, un lugar en la memoria de los hambrientos.', 'En la hora más negra de {lugar}, con los muertos de hambre alineados en las puertas, bajó las armas ante la multitud y vació el depósito de grano; llegó a tiempo para muchos y demasiado tarde para otros, y la crónica guarda ambos hechos.'],
    ['Cuentan que ante la multitud hambrienta de {lugar} dejó caer las armas como quien suelta una cadena: el depósito de grano se abrió, el grano corrió como un río, y los que habían venido a morir o a matar volvieron a casa a comer.', 'Se plantó entre los fusiles y la multitud hambrienta de {lugar}, y dio la orden más peligrosa que puede dar un mando: ninguna; el depósito de grano se abrió, y {pila} esperó el castigo de la capital con la serenidad de quien ya ha elegido.', 'Quebró los sellos del depósito de grano de {lugar} cuando el hambre ya había hecho su cosecha; entre las filas de la multitud los vivos comieron y los muertos fueron nombrados, y los dos hechos quedaron unidos en la piedra del asentamiento.'],
  ]);

  F('hecho_funda', [
    ['Fundó {faccion} en {lugar}.', 'Reunió descontentos en {lugar} y formó {faccion} en secreto.', 'Creó {faccion} en {lugar}; detuvieron a los primeros miembros.'],
    ['Juntó a gente descontenta en una trastienda de {lugar} y, a puerta cerrada, fueron dando forma a {faccion}: reuniones discretas, cuotas y un primer reparto de tareas.', 'Armó {faccion} en {lugar} con quienes tenían cuentas pendientes con el poder; el grupo crecía, pero entre sus miembros ya se oían reproches y no todos confiaban en los demás.', 'Dio origen a {faccion} en {lugar} entre vigilancias y delaciones; los primeros reunidos fueron detenidos, y los que quedaron tuvieron que empezar de nuevo a puerta cerrada.'],
    ['Cada noche, en un almacén de {lugar}, a puerta cerrada, fue sumando nombres a {faccion} con la lentitud de quien sabe que las cosas importantes se construyen sin ruido; cuando el grupo salió a la luz, ya nadie podía ignorarlo.', 'Sembró {faccion} en {lugar} con palabras a media voz y silencios cómplices; los descontentos acudían a sus reuniones de uno en uno, atentos a las sombras, y el temor a los delatores fue el cemento secreto del grupo.', 'Levantó {faccion} en {lugar} bajo la sombra de las detenciones, reuniendo en habitaciones sin ventanas a los que habían perdido a alguien; el duelo fue su primer lazo, y el rencor, su primer estatuto.'],
    ['Moldeó {faccion} en {lugar} a puerta cerrada, y de aquellas reuniones nació lo que la crónica llama el primer germen de una fuerza capaz de cambiar los mundos; en el momento nadie sospechó la trascendencia de lo que se hablaba.', 'En {lugar}, a espaldas de la autoridad, congregó a los inconformes y creó {faccion}; los historiadores anotan con admiración y recelo que de aquel pequeño círculo salió una fuerza que acabó pesando sobre Estados enteros.', 'Alumbró {faccion} en {lugar} en medio de una oleada de detenciones; los primeros fundadores pagaron con cárcel y exilio, y la crónica recoge sus nombres con gratitud y dolor, porque de su sacrificio nació lo que vino después.'],
    ['Cuentan que {faccion} nació en {lugar} entre paredes cerradas y una sola voz, la de {pila}; y que aquellas primeras palabras, dichas en voz baja, acabarían resonando en todas las estrellas.', 'Prendió {faccion} en {lugar} como una chispa en una bodega sin ventilación: a puerta cerrada, con los descontentos apretados y el aire espeso de rencor; y la chispa creció sin que nadie supiese cómo apagarla.', 'Plantó {faccion} en {lugar} sobre una tierra de lutos, reuniendo en habitaciones a oscuras a quienes habían perdido a los suyos; de aquella tristeza hizo fuerza, y de aquella fuerza un destino cuyo precio ya no pudo dejar de pagar.'],
  ]);

  F('hecho_atentado_sufre', [
    ['Sobrevivió a un atentado contra su vida.', 'Fue objetivo de un atentado y desde entonces sospechó de todos.', 'Sufrió un atentado; murieron varios de sus escoltas.'],
    ['Escapó con vida de un atentado en el que alguien quiso matar{lo|la}; apenas unos rasguños y una semana de reposo, y luego volvió al trabajo.', 'Salvó la vida en un atentado y desde entonces miró con recelo a cada persona de su entorno, sin saber quién había encargado el golpe.', 'Resistió un atentado que se llevó a varios de sus acompañantes; las heridas tardaron en cerrar, y las noches en dejar{lo|la} dormir.'],
    ['Eludió por muy poco el estallido de una bomba colocada bajo su asiento: la sala se sacudió y reventaron los cristales, pero {él|ella} salió caminando entre el humo, con la serenidad de quien ya había hecho las paces con el riesgo.', 'Salió {ileso|ilesa} de un atentado de autor desconocido; en los días siguientes comprobó con amargura que algunos de los que acudieron a felicitar{lo|la} eran los mismos que habían dado el aviso a los asesinos.', 'Emergió de entre los escombros de un atentado con la ropa en llamas y los oídos zumbando, buscando entre los cuerpos a los suyos; encontró a algunos, y a los demás los lloró durante años.'],
    ['Sorteó un atentado planeado con esmero: la crónica recoge que {nom} sobrevivió gracias a un cambio de última hora en la agenda, y que desde entonces creyó, como creyeron los suyos, que algo {lo|la} protegía.', 'Quedó con vida tras un atentado cuyos autores nunca se conocieron; los cronistas anotan la oleada de sospechas que siguió, los arrestos arbitrarios y el clima de recelo que inundó los pasillos del poder durante meses.', 'Se libró de la muerte en un atentado que costó la vida a su escolta y a otros inocentes; la crónica recoge los nombres de los caídos y el duelo con que {él|ella} los lloró en público.'],
    ['Atravesó un atentado entre fuego y gritos, y se cuenta que la muerte, que había venido a buscar{lo|la}, se quedó mirándo{lo|la} desde el umbral sin atreverse a entrar.', 'Vivió desde un atentado con la sombra de quien debía haber muerto: los suyos {lo|la} tuvieron por algo más que mortal, y {él|ella} supo que esa fe era también una jaula.', 'Abandonó las llamas de un atentado con el cuerpo marcado y el alma partida; los que {lo|la} acompañaban quedaron en el suelo, y aquella noche aprendió que sobrevivir también puede ser una forma de condena.'],
  ]);

  F('hecho_ejecuta', [
    ['Mandó ejecutar a {victima}.', 'Decretó la muerte de {victima}; el consejo se dividió.', 'Ordenó la ejecución de {victima}; hubo protestas y arrestos.'],
    ['Dictó la sentencia de {victima} tras un juicio sumario y presenció la ejecución desde una galería, sin una palabra, antes de volver a sus papeles.', 'Firmó la ejecución de {victima} sabiendo que no todos en el consejo la aprobaban; después soportó los reproches con la cabeza alta y la conciencia en vilo.', 'Dispuso el fusilamiento de {victima} al alba, en un pasillo vacío; la descarga retumbó por los muelles y nadie se atrevió a hablarle durante el resto del día.'],
    ['Dio la orden de ejecución de {victima} con voz serena y sin vacilar; después volvió al despacho como quien vuelve de un trámite, y solo las manos, que no logró calentar en toda la tarde, delataron algo.', 'Entregó a {victima} al pelotón entre argumentos de Estado y razones de peso que ni {él|ella} creía del todo; en el consejo hubo quien aplaudió y quien bajó los ojos, y {él|ella} sospechó que no se perdonaría jamás ninguna de las dos reacciones.', 'Condenó a {victima} al paredón en una madrugada sin luna; la ejecución fue breve y sucia, y quienes la presenciaron contaron después que {él|ella} no apartó la mirada ni una sola vez, como si quisiera grabarse la escena a fuego.'],
    ['Pronunció la sentencia de muerte de {victima} en una sala llena, y la ejecución se cumplió sin demora; los cronistas anotan que el proceso fue limpio en las formas y firme en el fondo, y que nadie en el Estado osó discutirlo.', 'Hizo ejecutar a {victima} a pesar de los ruegos del consejo y las súplicas de algunos amigos; el acto dividió a los suyos y sembró un rencor que ni los años lograron borrar, y la historia lo juzga todavía con severidad.', 'Llevó a {victima} ante el verdugo en la plaza mayor: la muchedumbre guardó un silencio helado mientras sonaba la descarga, y las crónicas aseguran que aquel silencio pesó más que cualquier condena; desde entonces el nombre de {nom} quedó unido al de {victima}.'],
    ['Sentenció a {victima} con la misma frialdad con que el vacío apaga una luz, y dicen que, desde ese día, su sombra pesó más que su palabra.', 'Escribió el nombre de {victima} en la lista de los condenados, y desde entonces, cuentan, esa tinta no se secó: cada noche volvía a mojar la página en el silencio de su despacho.', 'Ofreció la vida de {victima} al fuego de la ley, y la ley la devoró entera; en la plaza sonó una sola descarga, y dicen que aquel eco fue el último de una vida y el primero de un remordimiento.'],
  ]);

  F('hecho_venganza_jura', [
    ['Juró vengar la muerte de {victima}.', 'Apuntó en una libreta los nombres de quienes mataron a {victima}.', 'Lloró la muerte de {victima} y empezó una lista de culpables.'],
    ['Tras la muerte de {victima}, anotó en una libreta los nombres de los culpables, las fechas y los lugares, y se prometió que ninguno quedaría sin su ajuste de cuentas.', 'Guardó el luto por {victima} en el bolsillo, con la libreta donde fue apuntando a los culpables; los suyos le pedían que lo olvidase, y {él|ella} fingía hacerlo.', 'Prometió sobre el cuerpo de {victima} que nadie quedaría impune y empezó a anotar en una libreta el nombre de cada responsable; dormía mal, comía poco, y la lista crecía cada noche.'],
    ['Dedicó las noches a la libreta que llevaba siempre encima: allí iba anotando, con letra menuda y paciente, los nombres de quienes habían intervenido en la muerte de {victima}, y cada línea era una promesa más seria que un voto.', 'Convirtió la muerte de {victima} en una causa privada: libreta en mano, fue reuniendo nombres, fechas y rumores, y aprendió que el rencor, bien cuidado, rinde más que la esperanza.', 'Enterró a {victima} y, con la tierra aún fresca, abrió una libreta en blanco: de aquellas páginas, escritas con mano sin temblor, saldría una lista de condenas que no perdonaría a nadie, ni a quienes solo miraron.'],
    ['Hizo de la muerte de {victima} su causa y de una libreta su arma: la crónica recoge cómo, durante años, fue anotando con minucia cada nombre, cada rumor y cada deuda, hasta que la lista tuvo el peso de una sentencia.', 'Con la muerte de {victima} clavada como una espina, se obstinó en ajustar cuentas y lo fue apuntando todo en una libreta; los cronistas cuentan que cada nombre llevaba una marca al lado y que nunca ninguna fue borrada.', 'Selló en una libreta el duelo por {victima}: nombres, fechas y lugares escritos con una mano que ya no sabía sino odiar; los archivos guardan aún aquellas páginas, y cada una pesa como una condena.'],
    ['Se dice que {pila} hizo voto sobre la memoria de {victima} y que la libreta se escribió sola: cada nombre aparecía a medida que el rencor lo reclamaba, y cuando ya no cupo uno más, el mundo entero había quedado inscrito en sus páginas.', 'Llevó la muerte de {victima} pegada al pecho como una brasa, y la libreta pegada a la brasa; cuentan que nunca la abría delante de nadie, y que aun así todos sabían que estaba allí, escribiéndose.', 'Forjó con el duelo por {victima} una promesa de fuego, y con las páginas de una libreta, el mapa de una venganza que no perdonaría ni al tiempo; cada nombre escrito fue una sentencia, y cada sentencia, una muerte anunciada.'],
  ]);

  F('hecho_venganza_cumple', [
    ['Encontró y mató a quien buscaba: {victima}.', 'Dio con {victima} tras años de búsqueda y le quitó la vida.', 'Acabó con {victima} tras una larga persecución; también cayó gente inocente.'],
    ['Siguió el rastro de {victima} durante años, de puerto en puerto, hasta darle alcance y dar la cuenta por saldada con un solo disparo.', 'Rastreó a {victima} por muchos puertos hasta acorralarle en un callejón del muelle; la venganza se cumplió sin palabras, y {él|ella} descubrió que no sentía alivio.', 'Persiguió a {victima} con la libreta en el bolsillo y el rencor en los puños; cuando por fin se encontraron, no hubo juicio ni discurso, y la sangre le manchó las manos y los años que le quedaban.'],
    ['Arrinconó a {victima} al final de una cacería que se había llevado todo cuanto tenía: dinero, amistades, años; y le dio la muerte con una calma que desmentía el odio de tantas noches.', 'Acechó a {victima} desde las sombras de un muelle durante muchas noches, y cuando por fin hizo lo que había jurado, el silencio que siguió fue más hueco que la rabia; había matado a quien buscaba y no había encontrado lo que quería.', 'Cobró la deuda de {victima} con sus propias manos, en una bodega a oscuras: mató a quien buscaba, y al hacerlo comprendió que la sangre no devolvería nada, que ya nada le devolvería a los suyos.'],
    ['Cerró el círculo de su venganza ante {victima}: los cronistas describen una persecución larga, un encuentro sin palabras y una muerte limpia, tras la cual {él|ella} volvió a la vida corriente como quien cierra un libro que llevaba años abierto.', 'Saldó con la muerte de {victima} la deuda de años; los cronistas dejan constancia de que, tras cumplir lo jurado, {nom} ya no fue la misma persona: había encontrado a quien buscaba y perdido a quien era.', 'Abatió a {victima} en un puerto sin nombre tras años de persecución; las crónicas anotan la crueldad del acto, el silencio posterior y el hecho de que, con aquella muerte, {él|ella} cerró la deuda pero abrió otra: la de su propia alma.'],
    ['Alcanzó a {victima} al final de un camino de años, y se cuenta que quien iba a morir comprendió, en el último instante, que nadie escapa a una promesa hecha sobre una tumba.', 'Cazó a {victima} por todos los mundos como se caza una sombra, y le dio fin cuando por fin se encontraron cara a cara; el vacío que quedó después, dicen, no fue de paz, sino de hambre: la de una promesa cumplida cuando ya no queda nada que prometer.', 'Segó la vida de {victima} con la mano que había jurado hacerlo, y la sangre selló el pacto con los muertos; dicen que esa noche cayó una lluvia fina sobre los muelles, como si el cielo mismo quisiera lavarse.'],
  ]);

  F('hecho_abordajes', [
    ['Abordó {n} naves.', 'Asaltó {n} naves; el reparto del botín causó disputas.', 'Saqueó {n} naves; murieron muchos tripulantes.'],
    ['Fue capturando {n} naves a lo largo de los años, con una técnica cada vez más depurada: pocos disparos, entrada rápida y el botín repartido antes de volver a su ruta.', 'Sumó {n} naves abordadas, y con cada una creció la desconfianza: entre las tripulaciones por el reparto del botín, y en los puertos por las recompensas.', 'Dejó atrás {n} naves abordadas y a muchas de sus tripulaciones muertas o a la deriva; en cada una el filo cayó sin demasiada vacilación, y la lista de víctimas creció en silencio.'],
    ['Encadenó {n} abordajes con una limpieza casi artesanal: cada entrada ensayada, cada rehén tratado con corrección fría y cada carga trasvasada como en un muelle de confianza.', 'Contó sus {n} abordajes con un orgullo que no compartían quienes los habían sufrido; en los puertos se le tenía por hábil y por maldito a la vez, y {él|ella} fingía no oír la segunda mitad de la frase.', 'Sembró el vacío de pecios: {n} naves abordadas, tripulaciones arrojadas a la oscuridad, bodegas vaciadas y cubiertas rojas; ningún botín compensó nunca la suma de los gritos.'],
    ['Condujo {n} abordajes a lo largo de una carrera que las crónicas de las rutas describen como un modelo de audacia y disciplina; no hubo capitán de convoy que no tuviera presente su nombre al zarpar.', 'Con {n} naves abordadas a sus espaldas, se ganó un nombre que los muelles pronunciaban con respeto y con miedo, y un pasivo de rencores que los años habrían de cobrarle; la crónica anota ambos libros con la misma pluma.', 'Asoló las rutas con {n} abordajes que dejaron cubiertas rojas y puertos de luto; la crónica de aquellos años no recoge su nombre sin añadir de inmediato el de los que murieron en las bodegas.'],
    ['Cuentan que {n} naves cayeron ante el casco de {nom} sin que nadie lograra oír el disparo: bastaba su sombra en las pantallas para que las tripulaciones entregaran las bodegas y bajaran los ojos.', 'Rompió el casco de {n} naves como quien rompe una nuez, y de cada una sacó oro y rencor a partes iguales; por eso dicen que su camino se lee mejor en las listas de recompensas que en los mapas.', 'Abandonó {n} naves abiertas en el vacío, y el vacío las guarda: cascos negros, bodegas sin luz, nombres que nadie recita; dicen que en las noches más quietas aún se oye el golpe de sus garfios en el metal.'],
  ]);

  F('hecho_profecia', [
    ['Anunció una profecía que acabó cumpliéndose.', 'Profetizó algo que luego ocurrió; no todos le creyeron.', 'Vaticinó una desgracia; ocurrió, y hubo muertos.'],
    ['Predijo ante una plaza escéptica lo que habría de ocurrir, y cuando ocurrió, quienes se habían reído guardaron un silencio incómodo.', 'Pronunció en voz alta una profecía que molestaba al poder; los guardias {lo|la} callaron un tiempo, pero los hechos se encargaron de darle la razón y ya nadie pudo desmentirla.', 'Auguró el desastre antes de que llegara, y el desastre llegó; entre los escombros, algunos {lo|la} buscaron para culparle, y otros, para pedirle que dijera algo más.'],
    ['Dijo lo que vendría y vino: su profecía, que había hecho sonreír a los poderosos, se cumplió punto por punto, y desde entonces {lo|la} escuchaban sin burla, con ese temor reverente que se reserva para lo que no se entiende.', 'Avisó a quien quiso oírle de lo que se acercaba, y la profecía se cumplió con una exactitud que a nadie dejó indiferente; los poderosos se movieron entre el miedo y la envidia, y {él|ella} aprendió que acertar es una forma de peligro.', 'Previó la desgracia que nadie quiso creer, y cuando llegó, la sufrió con los demás, sabiendo que su don no había servido para evitarla; entre los muertos pasó noches enteras repitiéndose las palabras que no logró hacer oír.'],
    ['Enunció una profecía que las crónicas guardaron como un tesoro: se cumplió a su hora, con la exactitud con que se cumple una ley natural, y quienes la oyeron la repitieron después a sus hijos como se repite una advertencia.', 'Declaró lo que habría de venir ante un consejo hostil que {lo|la} tachó de alarmista; cuando los hechos dieron la razón a sus palabras, la crónica anota con ironía que los mismos que {lo|la} despreciaron fueron los primeros en pedir su consejo.', 'Escribió en una pared del puerto la desgracia que se avecinaba, y la desgracia llegó con su letra: la crónica registra con espanto la exactitud con que se cumplió su profecía y el eco de sus palabras entre las ruinas.'],
    ['Sus palabras cayeron sobre el tiempo como una piedra en un estanque: la profecía se cumplió, y las ondas de aquel cumplimiento llegaron hasta los muelles más lejanos, donde aún se repite su sentido sin recordar el nombre de {nom}.', 'Vio lo que aún no existía, y lo dijo a quien no quería oírlo; los años le dieron la razón, y {él|ella} comprendió que el don de ver es una condena: ver y no ser creíd{o|a}.', 'Nombró la desgracia antes de que viniera, y la desgracia vino a su nombre: los cronistas dicen que cada ruina que siguió estaba ya escrita en su voz, y que {él|ella} las lloró todas antes de que ocurrieran.'],
  ]);

  F('hecho_corrupcion', [
    ['Aceptó sobornos; miró hacia otro lado.', 'Cobró dinero a cambio de silencio y favores.', 'Se dejó sobornar; hubo muertos por su negligencia.'],
    ['Se acostumbró a recibir sobres por debajo de la mesa, y a firmar sin leer lo que otros le ponían delante.', 'Admitió pagos de quienes querían que mirase hacia otro lado, y lo hizo con tanta frecuencia que sus propios colaboradores comenzaron a murmurar y a anotar fechas.', 'Dejó pasar contrabando y órdenes ilegales a cambio de dinero, y cuando una de aquellas cargas se perdió con muertos, fingió ignorar de quién había sido la autorización.'],
    ['Ponía precio a cada favor con la naturalidad de quien cobra un salario; las bodegas se abrían, los sellos caían, y {él|ella} lo anotaba todo en un cuaderno secreto.', 'Convirtió su cargo en un mostrador: quien pagaba, pasaba; quien no, esperaba; y entre los suyos se fue extendiendo el rumor de las cuentas dobles, de los silencios comprados y de las manos que solo se cerraban para recibir.', 'Vendió su ceguera al mejor postor y vio morir por ella lo que juró defender: los muelles sin vigilancia, los almacenes sin control, las dotaciones sin socorro; cada moneda pesó luego como una pérdida.'],
    ['Hizo de la venalidad su método de gobierno: los archivos recogen una red de sobornos tan ordenada que pareció parte de la administración, y la crónica no puede sino admirar su eficacia, aun cuando condena su falta de escrúpulos.', 'Cedió su firma a quien pudo pagarla, y los cronistas lo anotan con amargura: una corrupción que carcomió desde dentro la confianza de un Estado que ya no se fiaba de sus propios funcionarios.', 'Toleró con sus sobornos la ruina de muchos: los registros de aquellos años muestran los almacenes vaciados, los controles burlados y los muertos que de ello resultaron, y la sombra de su firma aparece en cada margen.'],
    ['Cuentan que las monedas buscaban la mano de {pila} como el agua busca la grieta, y que su mirada se volvía hacia otro lado con la docilidad de quien sabe que el precio ya está pagado.', 'Fue despachando su silencio por piezas, y cada pieza abrió una puerta que hubiera debido seguir cerrada; dicen que, al final, no quedó puerta sin vender, y que {él|ella} se encontró sol{o|a} entre habitaciones abiertas a todos los vientos.', 'Abrió la puerta a la podredumbre por un puñado de monedas, y la podredumbre entró en los depósitos, en los muelles y en las casas; cuando por fin se hizo el recuento de lo perdido, el eco de aquellas monedas aún resonaba.'],
  ]);

  F('hecho_informe_miente', [
    ['Maquilló los informes que mandaba a la capital sobre {lugar}.', 'Retocó las cifras de {lugar} para evitar reproches.', 'Calló a la capital el hambre de {lugar}; hubo muertos.'],
    ['Embelleció los informes enviados a la capital sobre {lugar}: las cosechas, las cifras de población y las cuentas del puerto aparecían mejor de lo que eran, y nadie desde lejos lo notó.', 'Redactó para la capital partes tranquilizadores sobre {lugar} mientras en el asentamiento crecían las quejas; sabía que la mentira se descubriría tarde o temprano, y esperaba que fuera tarde.', 'Mandó a la capital informes serenos sobre {lugar} en plena crisis: ocultó los muertos, redujo las cifras del hambre y calló lo que se veía desde las ventanas del puerto, y el socorro nunca llegó.'],
    ['Escribió sobre {lugar} informes de una prosa tan impecable que la capital llegó a citarlos como modelo; la realidad, que quedaba lejos, no discutió con ellos.', 'Cuidó la imagen de {lugar} ante la capital con un esmero casi artístico: borró unas cifras, suavizó otras y añadió un par de logros inventados, a sabiendas de que, si el engaño caía, caería sobre {él|ella} con todo su peso.', 'Escondió bajo columnas de cifras impecables el hambre, la peste y los entierros de {lugar}, y la capital, tranquila, siguió sin enviar ayuda; cada informe suyo fue, sin saberlo, una sentencia para los que allí vivían.'],
    ['Dibujó para la capital un cuadro sereno de {lugar} que los archivos contradicen página a página: sus informes, ejemplares en la forma, hablan de una prosperidad que solo existía en el papel, y los cronistas se asombran de la constancia con que mantuvo la ficción.', 'Mintió con método a la capital sobre {lugar}: cifras cuidadas, giros prudentes y un optimismo administrativo que encubría el desorden; la crónica censura aquella mentira como lo que fue, una forma de traición disfrazada de lealtad.', 'Falseó los partes de {lugar} mientras el asentamiento se vaciaba de grano y de vida: los informes llegaban a la capital con la tinta limpia y el hambre fuera del papel, y la historia no tiene indulgencia para quien escribió sobre la muerte sin mencionarla.'],
    ['Cuentan que los informes de {nom} sobre {lugar} eran tan hermosos que la capital los leía como poesía, y que la realidad, avergonzada, se esforzó en parecérseles; pero la realidad nunca fue tan dócil, y al final la mentira cayó con estrépito.', 'Tejió sobre {lugar} una tela de cifras tan fina que ni la luz la atravesaba; la capital se tranquilizó bajo su sombra, y {él|ella} supo, en el silencio de sus noches, que cada hilo era una deuda que alguien pagaría.', 'Trazó con tinta limpia la historia de un mundo que ya se moría: en {lugar} el hambre devoró a los suyos mientras la pluma hablaba de abundancia, y dicen que cuando la verdad llegó a la capital, ya no quedaba nadie a quien salvar.'],
  ]);


})(typeof globalThis !== 'undefined' ? globalThis : this);
