// Frases del grupo «muerte». Cada hueco: 5 filas (épica 0..4) × 3 columnas (drama 0..2).
(function (g) {
  'use strict';
  const F = g.SIM.frases;
  F('muerte_natural', [
    ['Murió a los {edad} años en {lugar}.', 'Defunción en {lugar}, a los {edad} años. Nadie reclamó el cuerpo.', 'Falleció en {lugar} a los {edad} años. No tenía a nadie.'],
    ['Se apagó en {lugar} a los {edad} años, en su cama y sin sobresaltos, como suelen irse quienes han vivido de su trabajo.', 'Le llegó el final en {lugar}, a los {edad} años, entre reproches mal digeridos y asuntos sin zanjar.', 'Tras una enfermedad larga que fue minando sus fuerzas, dejó de respirar en {lugar} a los {edad} años, sin que nadie llegara a tiempo.'],
    ['Cerró los ojos en {lugar} a los {edad} años, con la luz de la tarde entrando por el ojo de buey y el murmullo de los filtros arrullándo{lo|la}.', 'Una disputa vieja seguía atravesada en su garganta cuando, a los {edad} años, la vida se le extinguió en {lugar}; no quedaba nadie a quien dirigirla.', 'Expiró en {lugar} a los {edad} años, tras semanas de fiebre y de pasillos vacíos, con las manos aferradas a una manta que nadie iría a recoger.'],
    ['La muerte alcanzó a {nom} en {lugar}, a los {edad} años, en la quietud de quien deja el trabajo hecho; los cronistas anotaron la fecha con respeto.', 'El corazón de {pila} se detuvo en {lugar} a los {edad} años; pocos lloraron en voz alta y muchos echaron cuentas, porque una vida así dejaba demasiadas deudas.', 'Concluyó sus días en {lugar} a los {edad} años, abatid{o|a} por una dolencia que ninguna medicina del puerto supo vencer, mientras en los pasillos se discutía ya su sucesión.'],
    ['Cuando la noche vino a buscar{lo|la} en {lugar}, a los {edad} años, la recibió de pie y en paz, como se recibe a una vieja conocida.', 'A los {edad} años, en {lugar}, el tiempo logró lo que ningún rival había logrado, y la muerte, que se había visto llegar desde lejos, no admitió trato.', 'En {lugar}, tras {edad} años de incendio, el frío l{o|a} tomó sin ruido; murió como mueren los astros, dejando una luz que tardaría generaciones en acabar de llegar.'],
  ]);
  F('muerte_combate', [
    ['Murió en combate en {lugar}.', 'Cayó en el combate de {lugar}. Su unidad no fue relevada.', 'Muert{o|a} de un disparo en {lugar}. Cuerpo sin recuperar.'],
    ['Perdió la vida combatiendo en {lugar}, en el puesto que le habían asignado y sin abandonarlo.', 'Quedó tendid{o|a} en {lugar} tras un combate ya perdido; los suyos se retiraron sin poder llevárse{lo|la}.', 'Un disparo l{o|a} alcanzó en {lugar} cuando cubría la retirada de otros, y no llegó a ver cómo cesaba el fuego.'],
    ['Dejó la vida en {lugar} con la calma de quien conoce su oficio: una sola ráfaga, sin dolor, y el casco todavía vuelto hacia el enemigo.', 'En {lugar} avanzó contra una posición que sus mandos daban por inexpugnable y fue de los primeros en no volver, con la discusión sin cerrar.', 'El fuego enemigo l{o|a} segó en {lugar}, entre humo, chatarra ardiendo y una radio que repetía su nombre sin que nadie contestara; tardaron hasta pasada la noche en dar con sus restos.'],
    ['En su puesto, cuando la jornada de {lugar} estaba ya decidida, {nom} entregó la vida; los cronistas anotaron que cumplió hasta el final y que nadie tuvo que pedírselo.', 'La batalla de {lugar} se cobró su vida entre órdenes contradictorias: avanzar, como se le exigía, o retroceder, como pedía su juicio; los informes se disputaron luego la culpa.', 'Bajo un fuego que no distinguía rangos sucumbió en {lugar}; las crónicas hablan de un desastre sin gloria, de cuerpos amontonados contra los mamparos y de su nombre añadido tarde a las listas.'],
    ['De cara al enemigo, con la última orden en los labios, abandonó el mundo en {lugar}, y todo el campo supo, antes de que llegaran los partes, que algo grande acababa de terminar.', 'Su coraje y su destino se encontraron por fin en {lugar}, y ganó el destino: la muerte llegó en forma de metralla, y el humo de aquel combate tardó años en disiparse de la memoria de los suyos.', 'La noche de {lugar} se l{o|a} llevó entre fuego y chatarra, y quienes aún combatían a su lado juraron después que el estruendo calló un instante, como si el mundo quisiera oír cómo caía.'],
  ]);
  F('muerte_ejecucion', [
    ['Ejecución ordenada por {verdugo}.', 'Tras un juicio sin defensa, l{o|a} ejecutaron por orden de {verdugo}.', 'Fusilad{o|a} al amanecer por orden de {verdugo}. Sin apelación.'],
    ['La sentencia, firmada por {verdugo}, se cumplió a la hora fijada y sin incidentes.', 'Un tribunal de trámite l{o|a} condenó a muerte por orden de {verdugo}; las acusaciones se leyeron deprisa y la defensa no llegó a hablar.', 'Por orden de {verdugo}, l{o|a} sacaron de la celda de madrugada y l{o|a} mataron en el patio, ante testigos que miraban al suelo.'],
    ['Subió al patio sin que nadie tuviera que empujar{lo|la}; la orden de {verdugo} se cumplió con el primer sol, y el gesto de despedida fue sereno, casi cortés.', '{verdugo} firmó la sentencia con una sola línea de tinta y sin alzar la vista; ante el pelotón, la víctima sostuvo la mirada y no pidió nada.', 'Al alba, atad{o|a} a un poste del muelle de carga, oyó leer la orden de {verdugo}; unas pocas descargas bastaron, y el eco rodó por los pasillos vacíos hasta que alguien cerró la compuerta.'],
    ['Un decreto de {verdugo} dispuso la ejecución en acto público, en la explanada del puerto; la crónica registra que {él|ella} oyó la sentencia de pie y que el silencio posterior duró más que la lectura.', 'La orden llegó firmada por {verdugo} y selló, con la frialdad de un trámite, la suerte de {pila}; cumplieron la sentencia a puerta cerrada, y las crónicas oficiales tardaron meses en confesar el hecho.', 'Fue arrastrad{o|a} ante el pelotón por mandato de {verdugo}, y la crónica deja memoria de aquel amanecer: el humo de las descargas, la sangre sobre el metal del muelle y un nombre borrado de los registros ese mismo día.'],
    ['Cayó sobre {él|ella} la sentencia de {verdugo} como cae la noche sobre un puerto sin luces, y {él|ella} la aguardó erguid{o|a}, pues sabía que hay finales que dan estatura a una vida.', 'Hubo quien juró que {verdugo} no durmió aquella noche; la ejecución se cumplió, pero quedó entre ambos una cuenta que ningún decreto pudo cerrar.', 'Murió ante el pelotón por voluntad de {verdugo}, y el eco de las descargas recorrió los muelles, las bodegas y los pasillos, como si la propia estación se negara a olvidar el sonido.'],
  ]);
  F('muerte_purga', [
    ['Cayó en una purga de {verdugo}.', 'Desaparecid{o|a} en la purga de {verdugo}, sin proceso.', 'Purgad{o|a} y fusilad{o|a} por {verdugo} junto a otros del mismo círculo.'],
    ['Pereció en la limpieza que {verdugo} hizo entre sus antiguos aliados, con discreción: una noche, un despacho vacío, un parte sin nombres.', 'Su nombre figuraba en una lista de {verdugo} que nadie había visto circular; cuando comprendió de qué trataba, ya no quedaba aliado al que acudir, y murió esa misma semana.', 'La purga de {verdugo} l{o|a} alcanzó de madrugada: irrumpieron en su alojamiento, l{o|a} sacaron sin dejarl{o|a} vestirse y nadie volvió a verl{o|a} con vida.'],
    ['Murió como mueren los que estorban sin saberlo: apartad{o|a} sin estrépito por {verdugo}, tras una cena cortés y una mañana en que su silla apareció vacía en el consejo.', 'Había apoyado a {verdugo} en las malas y sabía demasiado; cuando llegó el tiempo de las purgas, esa memoria fue una sentencia que nadie quiso pronunciar en voz alta, y murió sin juicio.', 'Entre los primeros se llevó {verdugo} a {nom}, de noche, con las luces del pasillo apagadas por orden; los suyos buscaron su nombre en las listas durante semanas.'],
    ['Cuando {verdugo} resolvió gobernar sin testigos, la conveniencia alcanzó a quien había sido su compañer{o|a} de armas: ni proceso ni sentencia, solo un parte lacónico que fechaba su muerte.', 'Las crónicas coinciden en que {verdugo} temía menos a los enemigos que a los aliados de cierta talla; esta muerte fue menos una venganza que una medida de prudencia, y quien la sufrió lo vio venir sin hallar modo de impedirlo.', 'Fue una de las muchas sombras que dejó la purga de {verdugo}: arrestad{o|a} sin cargos, juzgad{o|a} sin defensa, enterrad{o|a} sin nombre, mientras en los salones del poder se brindaba por la estabilidad.'],
    ['Se dice que {verdugo} cortó el lazo con la misma mano que lo había anudado; así cae quien sube demasiado cerca del sillón de mando, y así acabó {pila}, sin que la historia oyera su última palabra.', 'La hoz de {verdugo} segó aquel año las cabezas más altas del poder, y la suya rodó entre las primeras: nadie sobrevive a ser tan visible junto a quien teme ser visto.', 'Hubo una noche, larga como una guardia sin relevo, en que {verdugo} cerró la cuenta de sus rivales; entre los nombres borrados estaba el de quien más años había sostenido las espaldas de quien borraba.'],
  ]);
  F('muerte_linchamiento', [
    ['La multitud l{o|a} mató en {lugar}.', 'Linchad{o|a} en {lugar} tras un rumor. Nadie fue detenido.', 'Muert{o|a} a golpes y piedras por una turba en {lugar}.'],
    ['En {lugar}, una multitud silenciosa l{o|a} sacó de su casa y l{o|a} mató en la calle sin gritos, como quien cumple un trámite colectivo.', 'Tras semanas de rumores y deudas, la gente de {lugar} se juntó a la salida del turno, l{o|a} cercó y l{o|a} golpeó hasta matarl{o|a}; la guardia llegó cuando ya no hacía falta.', 'Entre insultos y empujones fue arrastrad{o|a} hasta el centro de {lugar}, donde la turba l{o|a} remató a pedradas mientras los demás miraban desde las pasarelas.'],
    ['Una tarde de silencio espeso, los vecinos de {lugar} fueron saliendo de sus puertas uno a uno y formaron un círculo; nadie alzó la voz, y cuando el círculo se deshizo quedó en el centro un cuerpo, el suyo, y un silencio que nadie quiso nombrar.', 'Había prometido más de lo que dio, y {lugar} no lo olvidó: en una noche de racionamiento, con las linternas en alto, la multitud l{o|a} buscó por los pasillos y no halló a nadie que l{o|a} defendiera.', 'La turba de {lugar} l{o|a} sacó a rastras entre gritos y l{o|a} mató junto a las compuertas de carga; después colgaron su abrigo de una barandilla, como una bandera que nadie supo explicar.'],
    ['La crónica de {lugar} conserva el día en que el pueblo, cansado de esperar justicia, se la tomó por su mano: {nom} fue sacad{o|a} de su refugio y ejecutad{o|a} en la calle sin sentencia ni testigos oficiales.', 'El rencor de {lugar} llevaba años madurando; cuando estalló, ni la guardia ni los notables pudieron contenerlo, y quien tanto había pesado sobre aquella gente murió a manos de sus propios gobernados, entre empujones y piedras.', 'Los anales recuerdan el furor de aquella jornada: la multitud se desbordó por los muelles de {lugar}, derribó las puertas, arrastró a su víctima por las escaleras y la golpeó hasta que los gritos se volvieron un solo rugido y después nada.'],
    ['Quien vivió bajo la mirada de muchos murió bajo sus manos: en {lugar} la multitud, que durante años había obedecido, se levantó una noche como un solo cuerpo y se cobró lo que creía suyo.', 'Hay deudas que el tiempo no borra, y en {lugar} se saldaron en una sola noche: el nombre de {pila} prendió de boca en boca como una chispa en un depósito de grano, y solo se apagó cuando la multitud acabó con {él|ella}.', 'Fue marea, fue incendio, fue pedrada la multitud de {lugar}; y cuando refluyó dejó en el suelo lo que quedaba de {él|ella}, ya sin nombre ni rango, igual que los demás cuerpos que el mundo no vuelve a contar.'],
  ]);
  F('muerte_atentado', [
    ['Muert{o|a} en un atentado cometido por {verdugo}.', 'Atentado en su contra; autor: {verdugo}. Murió en el acto.', 'Emboscada tendida por {verdugo}. Murió a tiros.'],
    ['Murió en un atentado perpetrado por {verdugo}, que lo había preparado con paciencia y lo ejecutó a la hora prevista.', 'Una carga oculta bajo su asiento habitual l{o|a} mató en el acto; los investigadores señalaron pronto a {verdugo}, aunque nada se sostuvo ante un tribunal.', 'En plena calle, entre empujones y gritos, {verdugo} se abrió paso hasta {él|ella} y disparó a quemarropa; murió en brazos de un desconocido.'],
    ['Salió a pasear por el anillo como cada tarde, y una sola detonación, calculada por {verdugo} con precisión de relojero, cerró su paseo y su vida; nadie oyó nada más que un portazo lejano.', 'Había recibido avisos, notas sin firma, una puerta forzada; el día en que {verdugo} por fin acertó, el disparo l{o|a} derribó en el pasillo y la guardia llegó cuando aún olía a metal caliente.', 'La explosión arrancó el mamparo del salón y se llevó consigo a {nom}; {verdugo} había calculado la hora para que no sobrara ni un testigo, y apenas quedó algo que enterrar.'],
    ['La historia conserva el atentado como un golpe limpio: {verdugo} esperó semanas, eligió el lugar y el instante, y un solo disparo, el que acabó con su vida, bastó para cambiar el rumbo de aquella época.', 'Cuando se supo que {verdugo} estaba detrás del atentado, ya nadie podía devolver la vida a quien había caído en el salón del consejo; las acusaciones cruzadas empezaron antes de que se enfriara el cuerpo.', 'El atentado cayó sobre la capital como un trueno sin nubes: {verdugo} había entrado con credenciales falsas, y a la hora convenida una carga de núcleo desgarró la sala y segó tanto la vida de {pila} como la última esperanza de paz.'],
    ['Dicen que la mano de {verdugo} no tembló; un solo golpe derribó lo que tantos enemigos no habían podido tocar, y desde entonces los dos nombres, el de quien mató y el de quien murió, caminan juntos por la memoria de los mundos.', 'El que se creyó a salvo tras innumerables guardias cayó por una puerta que nadie vigilaba: {verdugo} supo esperar, y el atentado probó que ninguna muralla basta cuando la paciencia ajena es mayor.', 'Hubo un estallido, un resplandor que borró las sombras de la estación y después el silencio; {verdugo} se alejó entre el humo, y lo que dejó atrás no fue solo un cadáver, sino un hueco con la forma de {pila}.'],
  ]);
  F('muerte_silencio', [
    ['Apareció muert{o|a}; pareció natural y nadie supo más.', 'Hallad{o|a} muert{o|a} en su alojamiento. Causa: natural. Nadie preguntó.', 'Muerte sin testigos. El expediente se cerró ese mismo día.'],
    ['L{o|a} encontraron por la mañana en su alojamiento, sin señales de violencia; el médico firmó un parte breve y nadie pidió más explicaciones.', 'Se fue de la noche a la mañana, con una rapidez que a algunos les pareció demasiada; el parte habló de causas naturales y nadie quiso contradecirlo.', 'Su cabina estaba cerrada por dentro cuando la abrieron y l{o|a} hallaron sin vida; se habló de corazón y, en voz baja, de otras cosas.'],
    ['Una mañana no bajó a su puesto. Cuando abrieron la puerta, la cama estaba hecha, la taza aún tibia y {él|ella} sentad{o|a} ante el ventanal, sin un gesto de dolor; el parte decía que fue el corazón, y todos asintieron.', 'Murió de golpe, en mitad de unas semanas de recelos y de visitas a deshoras; el médico habló de un corazón cansado, y a nadie le cuadró del todo el momento.', 'Dejó una copa a medio beber, una carta sin terminar y un cuerpo frío en el suelo del despacho; el parte no halló nada raro, y quienes sí lo hallaron tuvieron miedo de decirlo.'],
    ['Las crónicas apenas dedican una línea a su fin: murió en su alojamiento, de causa natural según los médicos del puerto, en una jornada sin más acontecimientos que ese.', 'Su muerte llegó en un momento tan oportuno para algunos que la historia nunca dejó de sospechar; pero los médicos firmaron causa natural, los papeles se archivaron, y el silencio se volvió la versión oficial.', 'Fue hallad{o|a} sin vida una madrugada, con el rostro helado y las manos crispadas, y se enterró deprisa; la crónica oficial registró una indisposición fatal, y la sospecha pasó, sin pruebas, a la leyenda.'],
    ['Se apagó como se apagan las estrellas lejanas, sin estruendo y sin testigos: una mañana el mundo, sin saber por qué, notó que ya no sonaba su paso.', 'Su fin llegó callado, y fue ese silencio lo que lo delató: cuando una vida tan ruidosa se apaga sin ruido, es que alguien ha pagado para que así sea.', 'La muerte entró sin llamar en su cabina y salió sin dejar huella; solo el frío del aire y la mirada fija del cuerpo contaron lo que la historia no quiso oír, y lo contaron tan bajo que se perdió en el eco de los pasillos.'],
  ]);
  F('muerte_venganza', [
    ['Muert{o|a} a manos de {verdugo}, por venganza.', 'L{o|a} mató {verdugo}, que l{o|a} buscaba desde hacía años.', 'Asesinad{o|a} por {verdugo}. Motivo: una muerte anterior sin saldar.'],
    ['Tras años de búsqueda paciente, {verdugo} dio con {él|ella} en un puerto menor y l{o|a} mató sin discursos, como quien por fin cierra una cuenta.', '{verdugo} l{o|a} había buscado de puerto en puerto durante años; cuando por fin l{o|a} tuvo delante, hubo pocas palabras, ninguna de perdón, y un solo disparo.', 'Una deuda de sangre vieja l{o|a} alcanzó: {verdugo} l{o|a} acorraló en un almacén a oscuras, y entre el miedo y los gritos l{o|a} mató con las mismas manos que durante años habían temblado de rabia.'],
    ['No hizo falta violencia en la mirada: {verdugo} llegó con calma, se sentó ante {él|ella} y esperó a que reconociera su rostro; después, sin prisa, saldó con un solo golpe lo que llevaba años pendiente.', 'Durante años cambió de nombre y de puerto; {verdugo}, que había jurado vengarse, aprendió a leer sus huellas, y el día que l{o|a} halló no hubo súplica que valiera: murió allí mismo.', 'Ni los guardias ni las puertas blindadas l{o|a} salvaron: {verdugo} había rastreado cada una de sus huidas, y cuando por fin cerró su última salida, el ajuste de cuentas fue breve y sangriento, y sin nadie que lo lamentara.'],
    ['En secreto guardó {verdugo} durante años el nombre de quien le había arrebatado lo que más quería; cuando la ocasión se presentó, la justicia privada se cumplió con una frialdad que las crónicas citan todavía como ejemplo de paciencia.', 'La venganza de {verdugo} tardó años en madurar y un instante en cumplirse; las crónicas no condenan ni aprueban, solo recogen que el odio, bien alimentado, alcanzó al fin a {nom} donde menos lo esperaba.', 'Por fin l{o|a} encontró {verdugo}, después de años de pistas, de naves alquiladas y de noches sin sueño; el encuentro fue corto, la sangre abundante, y la crónica, que lo anotó con severidad, no dejó dudas sobre quién había cobrado qué.'],
    ['El odio es una brasa paciente, y el de {verdugo} aguardó años junto a la puerta; cuando se abrió, no hizo ruido: quemó una sola vez, y de aquel fuego no se levantó nadie.', 'Anduvo {verdugo} tras su sombra por incontables puertos, y como la sombra no huye de quien la sigue, acabó por alcanzarla: se encontraron al fin, y solo uno salió de aquel encuentro.', 'Hay muertes que se cobran con otras muertes, y la de {pila} fue la cuenta pendiente de {verdugo}: años de rabia, un último encuentro a solas y un nombre más grabado en el libro de agravios.'],
  ]);
  F('muerte_veneno', [
    ['Murió envenenad{o|a}.', 'Veneno en la bebida. Se sospechó de alguien de su casa.', 'Muerte por veneno, tras horas de agonía. Sin culpable.'],
    ['Una dosis medida, disuelta en la comida, hizo su efecto en pocas horas; se apagó sin dolor aparente y el médico tardó en sospechar.', 'Bebió lo que le sirvieron en una cena tensa, entre miradas esquivas y brindis forzados; al amanecer estaba muert{o|a}, y la copa había desaparecido.', 'El veneno obró despacio y con crueldad: náuseas, espasmos, un sudor frío y días de agonía en los que nadie supo ponerle nombre al mal.'],
    ['La taza llegó a su mesa como todas las mañanas, humeante y dulce; el sabor extraño era apenas un matiz, y cuando el mundo empezó a ladearse ya no quedó tiempo más que para cerrar los ojos.', 'Alguien de confianza vertió algo en su copa mientras brindaban; durante semanas había notado un gusto raro en el agua y había callado, por no ofender, y ahora ese silencio le costaba la vida.', 'Convulsionó sobre la mesa del banquete entre platos rotos y gritos; el veneno no dejó salida alguna, y los comensales tardaron horas en atreverse a tocar el cuerpo.'],
    ['La crónica de su muerte es breve y prudente: bebió, enfermó y murió en menos de una noche; los médicos hablaron de veneno, el consejo de fatalidad, y la mesa de aquella cena no volvió a sentarse nunca completa.', 'Hubo quien vio la mano del poder en aquella copa; el veneno, que no necesita ejército, resolvió en una noche lo que años de intrigas no habían logrado, y las cortes enterraron a la víctima mirándose unas a otras con recelo.', 'Entre convulsiones, ante testigos que no supieron qué hacer, el veneno acabó con {él|ella}; la crónica la tiene por una de las muertes más infames de la época y no se atrevió a nombrar al culpable.'],
    ['Quien no quiere sangre en sus manos elige el veneno; una gota bastó, y lo que no habían rendido tantas batallas lo rindió un trago.', 'Brindaron los que sabían, bebió quien no sabía, y la copa, que había pasado por tantas manos, devolvió al fin la deuda: murió con la sonrisa torcida de quien comprende demasiado tarde.', 'Fue una muerte lenta y cargada de ceniza: el veneno l{o|a} fue recorriendo como un río oscuro, vena a vena, hasta apagar la última luz de sus ojos, y quienes lo vieron no volvieron a probar bocado sin mirar antes a su alrededor.'],
  ]);
  F('muerte_explosion', [
    ['Murió en una explosión en {lugar}.', 'Explosión en {lugar} por mantenimiento omitido. Murió en el acto.', 'Muert{o|a} en {lugar} al explotar un depósito, con otras víctimas.'],
    ['Un fallo de presión en {lugar} provocó una explosión que se l{o|a} llevó sin aviso; no sufrió y no hubo tiempo para el miedo.', 'Había avisado más de una vez del estado de las válvulas de {lugar}; la explosión le dio la razón, y esa razón fue lo último que conoció.', 'La explosión de {lugar} l{o|a} alcanzó de lleno: la onda arrasó el pasillo, el fuego se comió el aire, y de los suyos solo salió quien estaba más lejos.'],
    ['No llegó a oír el estruendo: en {lugar}, una luz blanca en el fondo de la bodega, un golpe de aire y un largo silencio de metal retorcido fueron todo lo que conoció de su muerte.', 'Se habían saltado todas las revisiones; en {lugar}, la explosión llegó con la puntualidad de lo que se sabe inevitable, y al ver las llamas por el pasillo comprendió que lo había visto venir y no lo había detenido.', 'La cadena de explosiones recorrió {lugar} de un extremo a otro, arrancando mamparos y puertas; cuando por fin pudieron entrar los equipos de rescate, hallaron su cuerpo entre los restos fundidos de una compuerta.'],
    ['En {lugar} estalló lo que no debía estallar, y entre los muertos de aquella jornada estaba {nom}, cuyo nombre figuró el primero en los informes; la comisión recogió los restos, reformó las normas y dio el asunto por cerrado.', 'Se dijo después que la explosión de {lugar} no fue un accidente, que alguien había manipulado los sellos, y la sospecha alimentó años de acusaciones; los restos de la víctima apenas bastaron para llenar un féretro.', 'Una llamarada recorrió {lugar} como un aliento de fragua, y entre los muertos de aquella catástrofe se contó {pila}; los cronistas hablan de cuerpos irreconocibles, de pasillos fundidos y de un duelo que duró hasta que se reconstruyó la última cubierta.'],
    ['El fuego que sostiene los mundos es el mismo que los devora, y en {lugar} se mostró de golpe: un resplandor más intenso que cualquier sol, y en él {él|ella} se fue, sin que quedara de su cuerpo más que una sombra en el mamparo.', 'Un estruendo sin eco, una luz sin amanecer: el núcleo de {lugar} se rompió, y la onda se llevó por delante a quien había desafiado tantas veces al peligro; esta vez el peligro cobró todas las deudas juntas.', 'Ardió {lugar} desde las entrañas, y del humo que subió por los conductos se dijo durante generaciones que llevaba su nombre; no quedó de {él|ella} ni la ceniza, y fue como si la explosión hubiese querido borrar hasta el recuerdo de su rostro.'],
  ]);
  F('muerte_peste', [
    ['Murió de peste en {lugar}.', 'Peste en {lugar}. Murió y su casa fue sellada.', 'Muert{o|a} por la peste en {lugar}. Cuerpo incinerado sin velatorio.'],
    ['Cayó enferm{o|a} en {lugar} durante el brote y murió a los pocos días, atendid{o|a} hasta el final por quien quedaba en pie.', 'Al cerrarse el puerto de {lugar}, la peste l{o|a} sorprendió dentro; se quejó del abandono de las autoridades hasta que la fiebre le quitó la voz.', 'Se l{o|a} llevó la fiebre en {lugar}, entre cuerpos que ya nadie recogía y pasillos donde el aire sabía a desinfectante y miedo.'],
    ['Sin ruido llegó la peste a {lugar}, como un huésped al que nadie invita y que no se despide: tras unos días de calor en la frente y de cansancio sereno, se durmió y ya no despertó.', 'Hubo advertencias, y no se atendieron; cuando la peste ya estaba dentro de {lugar}, le tocó cuidar a los enfermos con los medios que no existían, y la enfermedad acabó con {él|ella} entre reproches y listas de nombres.', 'En {lugar}, con el puerto clausurado y los almacenes de medicina vacíos, la peste l{o|a} fue consumiendo en una cabina sellada, mientras fuera la gente pasaba deprisa y de lado, por miedo a su aliento.'],
    ['Entre los muertos que la peste se cobró en {lugar} estuvo {nom}, que murió sin aspavientos entre los suyos; los cronistas lo anotaron junto a los demás muertos del brote, con el mismo respeto y la misma tristeza.', 'Mientras el contagio recorría {lugar}, los gobernantes discutían de cuarentenas y de culpas; la enfermedad, que no distingue entre cuentas ni cargos, alcanzó a {pila} en plena disputa, y la crónica no omite la ironía.', 'En los peores días de la peste de {lugar}, cuando los cuerpos se amontonaban en los muelles y las incineradoras no daban abasto, se apagó su vida; la historia recuerda su nombre como uno más en una lista que ya nadie leía.'],
    ['No distingue rangos ni méritos la peste; entró en {lugar} como un viento helado, y quien había desafiado tantos peligros fue derribad{o|a} por una fiebre invisible, tras demostrar que hasta lo más grande cae si lo toca lo pequeño.', 'Cuentan que la peste de {lugar} llamó a su puerta como llama a todas, sin anunciarse, y que no hubo cerrojo, ni guardia, ni nombre que la detuviera: aquella vez el enemigo no tenía rostro ni bandera, y l{o|a} venció.', 'La muerte vino a {lugar} en forma de fiebre y de silencio, y entre los cuerpos que la noche recogió en carretillas sin nombre iba el de {pila}, envuelto en la misma sábana que todos, olvidado un instante hasta por quienes le debían la vida.'],
  ]);
  F('muerte_nave', [
    ['Se perdió con su nave, la {nave}.', 'La {nave} no llegó a puerto. Iba a bordo.', 'Desaparecid{o|a} con la {nave}, sin supervivientes ni restos.'],
    ['Siguió la ruta marcada a bordo de la {nave} y no volvió a dar señales; en el puerto de destino esperaron semanas, y al fin la dieron por perdida.', 'Salió de puerto con el depósito justo y las órdenes cambiadas a última hora la {nave}; no llegó, y entre quienes iban a bordo estaba {él|ella}.', 'Un fallo en cadena dejó sin aire y sin rumbo a la {nave}, con {él|ella} dentro; nadie recogió el último mensaje, y el casco derivó sin nombre durante meses.'],
    ['Se fue con la {nave} como se van los navegantes de verdad: el casco alejándose despacio hacia el vacío, las luces de posición parpadeando una a una y la radio, por fin, en silencio.', 'Había dicho muchas veces que la {nave} acabaría por matar{lo|la}; el día que cruzó la zona de escombros sin escolta, nadie se atrevió a decirle lo que todos pensaban, y la nave no volvió a aparecer en ningún registro.', 'Durante días se recibió el mismo pitido desesperado desde la {nave}, cada vez más débil, hasta que dejó de oírse; cuando los equipos de rescate llegaron, solo encontraron el casco abierto y una deriva de hielo y de cosas rotas.'],
    ['Declarada perdida con todos los suyos a bordo, la {nave} se llevó consigo a {nom}; el registro de aquella travesía, el último que se conserva, termina a media frase y las crónicas lo citan aún como una de las grandes ausencias de su tiempo.', 'Hubo quien afirmó que la {nave} no se perdió, sino que alguien la hizo desaparecer; los archivos se contradicen, los testigos callan, y {pila} sigue consignad{o|a} en el parte de pérdidas con la fecha de su última salida.', 'Sin un mensaje, sin una baliza, sin un solo resto, la {nave} se desvaneció en el vacío con {él|ella} a bordo y con toda su gente; las crónicas dedican a la tragedia un capítulo entero y una pregunta que nunca tuvo respuesta.'],
    ['El vacío no devuelve lo que se lleva, y aquel día se llevó a la {nave} con quien iba en ella: allí donde las estrellas no tienen nombre, su rumbo se volvió leyenda de puerto en puerto.', 'Se dice que la {nave} sigue navegando, silenciosa, por la oscuridad entre sistemas, y que quien iba a bordo no murió, sino que se hizo parte del viaje; los muelles guardan todavía una luz encendida para {él|ella}.', 'En el abismo se rompió la {nave}, sin testigos, y con ella se hundió el nombre de quien la llevaba, que ya nadie volvió a pronunciar sin bajar la voz; por su pérdida, los puertos apagaron una luz.'],
  ]);
  F('cadena_1', [
    ['Causa inmediata: {hecho}.', 'Murió por esto, y hubo culpables: {hecho}.', 'Motivo de la muerte, con víctimas: {hecho}.'],
    ['Lo que acabó con su vida fue lo siguiente: {hecho}.', 'La muerte no fue casual, sino consecuencia directa de un suceso muy concreto: {hecho}.', 'Todo se precipitó de golpe, y el golpe fue este: {hecho}.'],
    ['Tras su final no hubo misterio, solo una cadena corta y clara de acontecimientos que acaba aquí: {hecho}.', 'Cuando se le preguntó a la historia por qué murió, respondió con una sola frase, amarga y exacta: {hecho}.', 'El golpe definitivo llegó sin aviso, con la brusquedad de las tragedias que parecían evitables: {hecho}.'],
    ['Las crónicas coinciden en señalar la causa inmediata de su muerte, y no la adornan: {hecho}.', 'Los historiadores discutirían durante generaciones de quién fue la culpa, pero no sobre el hecho que cerró su vida: {hecho}.', 'Aquel día, con testigos y sin remedio, el destino cobró su cuenta: {hecho}.'],
    ['Y así, como en las viejas historias que acaban en una sola línea, bastó esto para cerrar una vida entera: {hecho}.', 'No hizo falta más que lo que sigue, y bastó para borrar su nombre del mundo de los vivos: {hecho}.', 'Allí se rompió el hilo: la mano del azar, o del rencor, o de una voluntad ajena, se posó sobre su vida y la cortó en seco, y el golpe fue este: {hecho}.'],
  ]);
  F('cadena_2', [
    ['Esto, a su vez, venía de: {hecho}.', 'Antecedente, con agravio previo: {hecho}.', 'Antes de aquello, ya con víctimas: {hecho}.'],
    ['Y eso, a su vez, tenía su origen en lo siguiente: {hecho}.', 'Aquello no había surgido de la nada, sino de un agravio que ya nadie recordaba del todo: {hecho}.', 'Pero detrás de aquello había algo peor, que ya había costado vidas: {hecho}.'],
    ['Tirando del hilo se llegaba a un punto más atrás, y allí, sin sobresaltos, aparecía lo que lo había puesto todo en marcha: {hecho}.', 'De otra decisión descendía aquello, tomada a regañadientes y con mala conciencia: {hecho}.', 'La causa de la causa era todavía más dolorosa, porque olía a sangre antes de que nadie quisiera verlo: {hecho}.'],
    ['Los archivos, consultados con paciencia, remontan aquel desenlace a un hecho anterior que lo hizo posible: {hecho}.', 'Los historiadores señalan un eslabón previo, menos visible y más culpable que el último: {hecho}.', 'Un eslabón más atrás, la cadena entera pesaba ya sobre aquella vida con el plomo de la fatalidad: {hecho}.'],
    ['Como el río nace lejos de su desembocadura, aquel suceso hundía sus raíces en un manantial anterior: {hecho}.', 'Detrás del golpe había una sombra más larga que el golpe mismo, y esa sombra tenía un nombre en los anales: {hecho}.', 'Y aquel golpe, que parecía el centro de todo, solo era el eco de otro más antiguo y más terrible, que ya se había cobrado su parte de sangre: {hecho}.'],
  ]);
  F('cadena_3', [
    ['Origen remoto: {hecho}.', 'Raíz lejana, nunca saldada: {hecho}.', 'Al principio de todo, ya con muertos: {hecho}.'],
    ['Y todo había empezado mucho antes, en lo que parecía un asunto menor: {hecho}.', 'El principio de aquel hilo era muy anterior, y casi nadie lo recordaba, pero allí estaba la raíz del agravio: {hecho}.', 'Y en el origen de todo, años antes de que hubiera sangre, estaba esto: {hecho}.'],
    ['Si se seguía la cadena hasta su primer eslabón no se hallaba ninguna maldad, solo un suceso corriente, y sin embargo todo había partido de aquí: {hecho}.', 'En el comienzo de aquella cadena había una cuenta sin saldar, de las que se heredan como las deudas: {hecho}.', 'Mucho antes de que nadie sospechara el precio, se había sembrado la semilla de la tragedia: {hecho}.'],
    ['Los cronistas, al retroceder en el tiempo, sitúan el origen remoto de todo en un episodio que entonces pasó casi inadvertido: {hecho}.', 'Hay un punto, lejano y olvidado, desde el que los historiadores suelen contar todo lo que vino después: {hecho}.', 'Más atrás aún, cuando la tragedia era todavía una posibilidad y no una certeza, el mundo ya había tomado una decisión que le saldría muy cara: {hecho}.'],
    ['En el principio de aquel hilo, antes de que los nombres importaran y de que las naves tuvieran bandera, había una sola chispa: {hecho}.', 'Todo viene de más lejos de lo que la memoria alcanza: de una herida antigua que supuró en silencio durante generaciones, y cuyo origen fue este: {hecho}.', 'Como en todo incendio, hubo una brasa pequeña que alguien pisó sin ver, y que ya entonces tenía escrita su sentencia: {hecho}.'],
  ]);
  F('cadena_mano', [
    ['Causa desconocida.', 'No consta la causa. Nadie quiso investigar.', 'Sin causa conocida. Hubo muertos y ninguna explicación.'],
    ['Nadie supo nunca por qué ocurrió; ninguna investigación halló una razón, y con el tiempo se dejó de preguntar.', 'Los informes se contradicen y ninguno explica nada; hay quien habla de mala suerte y quien prefiere no hablar.', 'Sucedió sin motivo, sin aviso y sin culpable, y esa falta de explicación fue casi más cruel que el hecho mismo.'],
    ['Ninguna cadena de hechos explica lo ocurrido; fue, sencillamente, una de esas cosas que el mundo hace de vez en cuando, y los vivos aprendieron a aceptarla sin comprender.', 'Se buscaron culpables en los registros, en las sombras y en los rencores viejos, y no se halló ninguno; lo ocurrido seguía sin causa, y esa ausencia incomodaba más que cualquier acusación.', 'No hubo orden, ni error, ni mano que lo explicara: la desgracia vino sola, como una racha de viento sin origen, y se llevó lo que quiso.'],
    ['Los cronistas, tras repasar cuantas pruebas se conservan, admiten que no hay causa conocida que dé razón de lo ocurrido; lo consignan con la modestia de quien reconoce los límites de su oficio.', 'El misterio ocupó años a investigadores y a rivales por igual, y ninguno halló un culpable ni un motivo; la historia lo cuenta como una herida cerrada en falso.', 'La tragedia no tuvo origen que los anales sepan nombrar: ni una orden, ni un descuido, ni una venganza; solo el golpe, el estruendo y la pregunta, que nadie logró responder.'],
    ['Hay hechos que el mundo hace sin dar razones, como hace el invierno o la tormenta, y este fue uno: no tuvo causa, no tuvo autor, y por eso mismo quedó para siempre como una pregunta.', 'Se dice que no hubo causa, y que quien la busque se perderá en los archivos como se pierde una nave en un campo de ceniza; el mundo, a veces, castiga sin razón, y es inútil pedirle cuentas.', 'Ni mano que lo guiara ni razón que lo explicara: vino de la nada, como vienen los grandes males, y se fue dejando tras de sí un silencio que ningún cronista ha sabido llenar.'],
  ]);
  F('edad_joven', [
    ['Murió joven, a los {edad} años.', 'Casi nada vivido: la muerte llegó a los {edad} años.', 'Tenía {edad} años. No llegó a más.'],
    ['Apenas había pasado de los {edad} años cuando la muerte l{o|a} sorprendió, con casi todo por hacer.', 'Se cortó en seco, a los {edad} años, lo que prometía una vida larga; la prisa con la que había vivido pareció después una advertencia.', 'No pasó de los {edad} años; la vida l{o|a} dejó a medias, como una frase interrumpida.'],
    ['Aún no había terminado de aprender el oficio de vivir cuando, a los {edad} años, se despidió sin aspavientos; dejó pendientes unas pocas cosas pequeñas, que la memoria de los suyos fue recogiendo despacio.', 'Cuando empezaba a ganarse un sitio en el mundo, a los {edad} años, la muerte l{o|a} apartó del camino; hubo quien vio en la prisa de su vida un presagio.', 'Con la vida a medio estrenar y los planes en el cajón, se fue a los {edad} años; cuando los suyos recogieron sus cosas, hallaron proyectos para un futuro que ya no era de nadie.'],
    ['La crónica l{o|a} recuerda como una promesa truncada: a los {edad} años, cuando el mundo empezaba a fijarse en {nom}, llegó el final, y los contemporáneos se preguntaron cuánto habría dado de sí con tiempo.', 'Los suyos sostuvieron siempre que morir a los {edad} años fue un robo, y que la prisa con que se le fue la vida tenía algo de condena; los rivales, en cambio, respiraron.', 'Truncada a los {edad} años, su vida quedó como esos relatos que se cortan en mitad de una frase; los cronistas, al narrarla, no ocultan la desazón de lo que pudo haber sido.'],
    ['Ardió joven, como arden las estrellas que más brillan: {edad} años le bastaron para que su luz alcanzara a muchos mundos, y su ausencia, desde entonces, fue una forma de luz.', 'Hay vidas que no se miden en años sino en incendios, y la suya, que se apagó a los {edad}, tuvo más de lo segundo; quienes vinieron después aún discuten si fue cumplirse o malograrse.', 'Como se arranca una flor al amanecer, la muerte se l{o|a} llevó de golpe a los {edad} años; el mundo quedó con las manos vacías y con la certeza de haber perdido algo que nunca llegó a ser del todo.'],
  ]);
  F('edad_plena', [
    ['Murió en plena madurez, a los {edad} años.', 'Quedaron asuntos sin cerrar al morir, a los {edad} años.', 'Tenía {edad} años. La muerte llegó sin aviso.'],
    ['Estaba en la plenitud de sus fuerzas y de su oficio, a los {edad} años, cuando le llegó la muerte, que nadie esperaba.', 'Su carrera iba en lo mejor cuando, a los {edad} años, la muerte l{o|a} interrumpió; había hecho enemigos y deudas, y ninguno tuvo ocasión de saldarse.', 'Se fue a los {edad} años, cuando más contaban con {él|ella}; los suyos no habían tenido tiempo de prepararse.'],
    ['Con {edad} años y los brazos aún llenos de proyectos, la muerte l{o|a} halló trabajando, con la mirada puesta en la próxima travesía, como halla a los que no se resignan a descansar.', 'Cuando el oficio ya le pesaba menos que el nombre, a los {edad} años, una vida a medio gobernar se quedó sin timón; los de abajo respiraron y los de arriba, por una vez, callaron.', 'Los {edad} años deberían haber sido los de la cosecha, y fueron los de la ceniza: la muerte se l{o|a} llevó con la herramienta aún en la mano, y los suyos aprendieron de golpe cuánto sostenía.'],
    ['La muerte alcanzó a {nom} a los {edad} años, en plena madurez y en pleno vigor; la crónica subraya que ni los amigos ni los rivales habían pensado en la sucesión, porque nadie creía que fuera a morir tan pronto.', 'En la cumbre de su influencia, a los {edad} años, cayó el telón sobre su vida; los contemporáneos vieron en ello un castigo, un accidente o un alivio, según el bando.', 'Truncó el destino, a los {edad} años, una madurez que prometía todavía mucho; las crónicas lamentan que {pila} no viera cumplidas sus obras, y el vacío que quedó fue tan grande que tardó años en llenarse.'],
    ['En el mediodía de su vida, cuando la sombra es más corta y la luz más recta, llegó la noche para {él|ella}: {edad} años de cumbre bastaron para que su nombre quedara inscrito en los muros del tiempo.', 'Quien tantas veces había visto pasar de largo a la muerte la tuvo por fin sentada a su mesa, a los {edad} años, sin permiso pedido; lo que dejaba a medias se quedó a medias para siempre.', 'Cayó en la cima, a los {edad} años, como cae el árbol más alto cuando el rayo lo elige; el bosque de los suyos quedó en pie, pero con un claro enorme, por donde entró un frío que nada volvió a templar.'],
  ]);
  F('edad_vieja', [
    ['Murió vie{jo|ja} a los {edad} años.', 'Tenía {edad} años. Nadie de su generación seguía con vida.', 'Tardaron días en saber que había muerto, a los {edad} años.'],
    ['Llegó a los {edad} años, que son muchos en estos puertos, y se fue tranquil{o|a}, con la casa en orden.', 'Vivió hasta los {edad} años, más de lo que muchos habrían querido; sus herederos esperaban, y su carácter no se suavizó con la edad.', 'A los {edad} años estaba ya sol{o|a}: había enterrado a los suyos, y la muerte, cuando llegó, encontró la casa vacía.'],
    ['Se despidió a los {edad} años, con el pelo blanco, las manos cuarteadas y una paz de metal templado; había visto cambiar tantas veces el orden de los mundos que ya nada l{o|a} asombraba.', 'Había durado {edad} años, mucho más que sus enemigos y que sus aliados, y esa longevidad fue su mejor venganza; la vejez, sin embargo, le cobró lo suyo con una lentitud cruel.', 'La memoria se le fue deshaciendo como un casco viejo bajo una estrella dura, y a los {edad} años murió sin reconocer a nadie, entre los cuidados de quienes habían sido sus rivales y ahora eran sus únicos visitantes.'],
    ['Cargad{o|a} de años y de recuerdos, {nom} se extinguió a los {edad} años rodead{o|a} de quienes l{o|a} habían seguido; la crónica señala que vio morir a su época y tuvo la dignidad de no sobrevivirla.', 'La vejez fue para {pila} un largo ajuste de cuentas: a los {edad} años, cuando por fin se apagó, muchos de los que habían temido su nombre lo pronunciaron en voz alta por primera vez.', 'Sobrevivió a guerras, intrigas y epidemias, y a los {edad} años la edad terminó con quien no pudieron los enemigos; las crónicas anotan con melancolía que muy pocos de los que presenciaron su ascenso vivieron para ver su fin.'],
    ['Los años se le acumularon como polvo de estrella en una bodega vieja, hasta sumar {edad}: tantos que llegó a ser casi parte del paisaje, y cuando se fue, el paisaje lo notó.', 'Vio caer a sus enemigos, a sus amigos y a sus propias obras, y a los {edad} años se marchó con la serenidad amarga de quien lo ha visto todo y no se ha dejado engañar por nada.', 'Hay ancianos que se apagan y ancianos que se desmoronan, y {pila} fue de estos últimos: a los {edad} años se deshizo pedazo a pedazo, ante los ojos impotentes de los suyos, como un casco viejo que ya no resiste el vacío.'],
  ]);
  F('legado_nada', [
    ['Nada cambió con su muerte.', 'Su puesto se cubrió al día siguiente, sin cambios.', 'Su muerte no dejó huella. Ni un duelo, ni un cambio.'],
    ['Apenas alteró aquella muerte el curso de los asuntos; el puerto siguió funcionando como si nada y a los pocos días casi nadie la mencionaba.', 'Con su muerte no cambió nada de lo que importaba, y eso fue lo que más amargó a los pocos que habían esperado un cambio.', 'El mundo no se alteró: las naves siguieron saliendo, los depósitos abriendo y cerrando, y la ausencia se fue cubriendo de rutina, sin que nadie la lamentara.'],
    ['Los muelles se llenaron y se vaciaron como siempre; solo un hueco en una lista de turnos recordaba, al cabo de unos días, que {él|ella} ya no estaba.', 'Se había creído insustituible, y su muerte fue la prueba de lo contrario: el engranaje que ayudó a mover siguió girando sin una sola vacilación, como si {él|ella} nunca hubiera existido.', 'Su desaparición no dejó eco: ni un duelo, ni un decreto, ni una pregunta; las luces del pasillo siguieron encendidas, y esa indiferencia fue la última cosa cruel que le hizo el mundo.'],
    ['Las crónicas, tan generosas con otros, apenas anotan la muerte de {nom}: los asuntos del Estado siguieron su curso sin interrupción, y la historia tardó en reconocer la falta.', 'Contra lo que muchos esperaban, la muerte de {pila} no desató crisis alguna: los poderosos se miraron, comprobaron que nada se tambaleaba y volvieron a sus mesas; la normalidad fue el verdadero epitafio.', 'Como una piedra en un pozo sin fondo cayó su muerte en el vacío: ningún eco volvió, ningún decreto la nombró, y la crónica del año dedica más palabras al precio del grano que al final de una vida entera.'],
    ['Cuando se fue, los mundos siguieron girando alrededor de sus estrellas con la misma calma de siempre; la corriente del tiempo se cierra sobre quien parte como el agua sobre una piedra.', 'Murió, y la historia no se estremeció; hay personas que dejan una grieta en el mundo y hay quienes, por grandes que parezcan, dejan solo una marca en la arena: esa fue la suya.', 'Ni las estrellas se apagaron, ni los reactores cambiaron su ritmo, ni los muelles guardaron luto: el universo, que a todos acoge, l{o|a} despidió con el mismo silencio con que l{o|a} había recibido.'],
  ]);
  F('legado_sucesion', [
    ['L{o|a} sucedió {heredero}.', 'Su puesto pasó a {heredero}, entre protestas.', 'Heredó el puesto {heredero}, a costa de sangre.'],
    ['Fue {heredero} quien tomó el relevo, y la transición se hizo en orden, con los papeles firmados y sin sobresaltos.', 'Ocupó su lugar {heredero}, aunque no todos estaban de acuerdo; hubo murmullos, reuniones a puerta cerrada y un acuerdo que nadie celebró.', 'La sucesión recayó en {heredero}, que la aceptó entre luto, sospechas y un rastro de sangre todavía fresco en los pasillos.'],
    ['Recogió el testigo {heredero}, que había aprendido a su lado el modo de mandar y supo hacerlo sin romper nada de lo que dejaba; el paso de uno a otro fue suave como un relevo de guardia.', 'Sobre sus huesos se sentó {heredero}, que durante años había esperado ese momento con paciencia de cazador; nadie pudo reprocharle nada, pero tampoco nadie se fió.', 'La silla vacía fue a parar a {heredero}, que la ocupó con las manos aún manchadas de la sangre de la sucesión; en el primer consejo ya faltaban voces, y nadie se atrevió a preguntar por ellas.'],
    ['Conforme a lo dispuesto en vida por {nom}, sucedió en el mando {heredero}, y la crónica registra que el cambio de manos se hizo con solemnidad, ante los consejos reunidos y sin una sola voz en contra.', 'Un asunto de dos filos fue la sucesión de {pila}: {heredero} heredó el poder, pero también las deudas, los rivales y los secretos que quien le precedió dejó a medias.', 'Aún no se había enfriado su cuerpo cuando {heredero} se hizo con el mando, entre purgas y conjuras; la historia anota aquel relevo como un golpe disfrazado de herencia, y recuerda que costó más muertos que la propia muerte.'],
    ['Cayó el árbol y creció el brote: {heredero} recogió la herencia como se recoge una antorcha en plena carrera, y la llama, que había cambiado de manos, siguió ardiendo con la misma altura.', 'Hay herencias que son regalos y hay herencias que son sentencias; la de {heredero} fue ambas cosas: recibió un mundo y, con él, la sombra de quien lo había forjado, que no se dejó ignorar nunca.', 'Con el entierro aún reciente, {heredero} alzó su estandarte, y los vivos juraron lealtad con la boca mientras los muertos, en silencio, la maldecían; así comenzó, entre ceniza, un nuevo gobierno.'],
  ]);
  F('legado_caos', [
    ['Su muerte dejó {estado} sin cabeza.', 'Tras su muerte, {estado} se partió en bandos.', 'Una guerra interna se abrió en {estado} con su muerte.'],
    ['Con su muerte, {estado} se quedó sin quien mandara, y durante un tiempo las decisiones se tomaron por turnos y sin urgencia.', 'La falta de sucesor claro dividió a los suyos en {estado}; cada bando se creyó heredero legítimo y ninguno cedió.', 'En {estado}, la noticia de su muerte desató una guerra entre sus propios partidarios, que se acusaron mutuamente y acabaron a tiros en los pasillos.'],
    ['Se abrió en {estado} un interregno lento y casi educado, de reuniones sin fin y copas sin brindis, mientras los notables buscaban a alguien en quien confiar.', 'Sin su mano firme, {estado} se llenó de murmullos y de alianzas cambiantes; los que l{o|a} habían servido se miraron unos a otros, y cada uno empezó a calcular cuánto valía su traición.', 'Cuando faltó su voz, {estado} se quebró como un cristal con una grieta antigua: los bandos se armaron, los puertos cerraron sus puertas y el primer cuerpo apareció antes de que acabase el luto.'],
    ['La muerte de {nom} dejó {estado} sin cabeza, y los cronistas advierten que el vacío de poder fue ordenado, casi solemne: los consejos se reunieron, se juraron fidelidades provisionales y se esperó, con prudencia, a que alguien tomara el timón.', 'Con {pila} desapareció el único equilibrio posible entre las facciones de {estado}; las crónicas coinciden en que las rivalidades, contenidas durante años por su autoridad, estallaron en cuanto se cerró el último sello.', 'La caída de su autoridad hundió a {estado} en la guerra civil: bandos armados disputaron cada puerto y cada depósito, y la crónica de aquellos años es una lista de asentamientos tomados, perdidos y vueltos a tomar.'],
    ['Cayó el eje y {estado} giró sin rumbo, como una nave sin timonel entre campos de escombros; atravesó un tiempo de sombras antes de que alguien, por fin, volviera a tomar el mando.', 'Sobre su tumba se abrió un abismo, y en {estado} cada facción se creyó la llamada a llenarlo; el tiempo no dio la razón a ninguna y el hierro se la quitó a todas.', 'Un incendio de bandos y venganzas devoró a {estado}, que se había quedado sin cabeza: el nombre de quien había sostenido el edificio se pronunció entre sangre y ceniza, y hubo generaciones que crecieron sin conocer otra cosa que la guerra de los herederos.'],
  ]);
  F('legado_martir', [
    ['Su muerte encendió la calle en {n} mundos.', 'Hubo manifestaciones en {n} mundos tras su muerte.', 'Disturbios con muertos en {n} mundos al saberse su muerte.'],
    ['La noticia de su muerte corrió por {n} mundos y la gente salió a la calle, en silencio, a guardar luto; pasó a ser {un|una} mártir.', 'No cayó en saco roto aquella muerte: en {n} mundos hubo manifestaciones, pancartas y consignas, y quienes antes l{o|a} ignoraban empezaron a llamarl{o|a} mártir.', 'Al saberse la noticia, la calle estalló en {n} mundos: se quemaron cuarteles, se asaltaron depósitos y la palabra mártir pasó de boca en boca ante cada cuerpo caído.'],
    ['En {n} mundos se encendieron velas en los muelles y se guardó silencio ante cada pantalla; la gente hablaba de {él|ella} con una ternura que en vida no se le había concedido.', 'Tan oportuna para algunos, aquella muerte tuvo un efecto que nadie había calculado: en {n} mundos la rabia se organizó en torno a su nombre, y quienes l{o|a} habían dejado sol{o|a} se disputaron ahora su herencia moral.', 'Corrió la sangre en {n} mundos: las multitudes tomaron las calles al enterarse, las guarniciones dispararon, y cada cuerpo caído en su nombre hizo más grande el símbolo que {él|ella} nunca quiso ser.'],
    ['Con la rapidez de una señal de socorro, la muerte de {nom} recorrió {n} mundos; las crónicas registran duelos multitudinarios, comités espontáneos y el nacimiento, en pocos días, de una devoción cívica hacia su memoria.', 'Los gobernantes subestimaron la muerte de {pila}: en {n} mundos se alzaron voces, se reunieron asambleas, y el poder, que había creído cerrar un expediente, descubrió que había abierto una herida.', 'La respuesta fue unánime y brutal: en {n} mundos las multitudes tomaron las calles al grito de su nombre, hubo cargas, incendios y muertos, y la historia guarda aquellos días como la hora en que un cadáver se volvió bandera.'],
    ['De su muerte nació otra vida, más larga y más grande: {n} mundos pronunciaron su nombre a un tiempo, y {el|la} mártir, que ya no podía callarse, empezó a hablar por todos los que habían callado.', 'Quisieron apagar una llama con su muerte, y la llama prendió en {n} mundos a la vez; sus verdugos comprendieron, demasiado tarde, que habían dado a su enemigo lo único que le faltaba: un nombre grabado en la piedra.', 'Y la calle tembló: en {n} mundos, a un mismo clamor, su nombre se cubrió de flores y de fuego, y el cuerpo caído se alzó, como se alzan los mitos, por encima del ruido de las armas.'],
  ]);
  F('legado_fiesta', [
    ['Se le recuerda cada año con una fiesta: {fiesta}.', 'Fiesta anual en su recuerdo, con protestas: {fiesta}.', 'Se conmemora su muerte con un día de luto: {fiesta}.'],
    ['Cada año, en el aniversario de su muerte, la gente se reúne para celebrar una fiesta que lleva su recuerdo: {fiesta}.', 'Su recuerdo se celebra todos los años, aunque no todos están de acuerdo en lo que hay que celebrar: {fiesta}.', 'Cuando vuelve la fecha de su muerte, los barrios se visten de luto y recuerdan lo ocurrido: {fiesta}.'],
    ['Con los años, el recuerdo de su vida se hizo fiesta: los vecinos sacan las mesas al pasillo, encienden luces de colores y brindan por {él|ella}, bajo un nombre que ya es de todos: {fiesta}.', 'La fiesta con que se l{o|a} recuerda tiene algo de agridulce: unos brindan, otros miran hacia otro lado, y todos saben que el nombre es una forma de no decir lo que pasó: {fiesta}.', 'En la fecha en que murió se encienden luces en los muelles y se cantan los nombres de los caídos junto al suyo; la fiesta, cuyo nombre es {fiesta}, nació del duelo y aún no ha aprendido a ser alegre.'],
    ['Los consejos instituyeron en honor de {nom} una fiesta anual, que desde entonces recorre los mundos con solemnidad creciente: {fiesta}; cuentan los cronistas que ni en las épocas peores se dejó de celebrar.', 'Una decisión política dio origen a la fiesta que lleva la memoria de {pila}, y la costumbre popular la hizo suya: {fiesta}, que unos celebran con fervor y otros soportan con paciencia.', 'Al volver la fecha de su muerte, los pueblos conmemoran con un duelo solemne los días de sangre que la rodearon: {fiesta}, nombre que se pronuncia en voz baja y no se olvida nunca.'],
    ['Pasaron las generaciones y su nombre se hizo calendario: hoy se l{o|a} recuerda cada año con una fiesta de luces y canciones, y el pueblo, que no lee crónicas, la sabe de memoria: {fiesta}.', 'Hay fechas que el pueblo adopta y fechas que le imponen, y esta, la que lleva su nombre, es de las que nadie impuso y nadie podría abolir: {fiesta}.', 'De su sangre nació una fiesta, y de la fiesta un calendario: cada año, al llegar la noche de su muerte, los mundos encienden luces, cantan su nombre y vuelven a llorar por {él|ella}, aunque ya nadie recuerde bien por qué: {fiesta}.'],
  ]);
  F('legado_memorial', [
    ['Hay un memorial en {lugar} con los muertos por su orden.', 'Las familias de sus víctimas exigieron un muro en {lugar}.', 'Los muertos por su orden llenan un muro entero en {lugar}.'],
    ['Se levantó en {lugar} un monumento sencillo con los nombres de quienes murieron por orden suya, y cada año alguien lo limpia y deja flores.', 'Tras años de protestas, las familias de los muertos por su orden consiguieron un memorial en {lugar}; en la placa no consta el nombre de quien dio las órdenes.', 'Quienes sobrevivieron a su mando alzaron en {lugar} un muro con los nombres de los muertos, y lo cubrieron de fotografías, de cartas y de rabia.'],
    ['Con el tiempo, en {lugar}, una explanada de piedra gris recoge uno a uno los nombres de los que murieron por su orden; el viento de los conductos los acaricia, y la gente pasa despacio y con la cabeza baja.', 'Un memorial que habría querido destruir se alza en {lugar}: una placa tras otra con los nombres de quienes murieron por su orden, y un espacio en blanco al final donde la gente deja pintadas.', 'En {lugar} se alza un muro al que ya no cabe añadir ni un nombre más de los muertos por su orden; los deudos van allí el día del recuento y dejan flores bajo cada letra grabada.'],
    ['Por decreto de los consejos se erigió en {lugar} un memorial a los que murieron por orden de {nom}, y la crónica señala que su inauguración fue ocasión de silencio, de reconciliación y de balance.', 'El memorial de {lugar} tardó años en levantarse: los que mandaron callar no querían nombres a la vista, y los muertos por orden de {pila} no tuvieron lápida hasta que cambió el poder.', 'En el centro de {lugar}, junto al antiguo puerto, se alza hoy un muro negro en el que figuran, uno a uno, los nombres de quienes murieron por su orden; las crónicas lo llaman el testimonio de piedra de una época de sangre.'],
    ['Piedra sobre piedra, en {lugar}, los nombres de los que murieron por su orden se alinean bajo la luz de los reflectores, y el mundo, que a veces olvida a los verdugos, no olvida a sus víctimas.', 'Existe un lugar, {lugar}, donde cada nombre grabado es una acusación, y donde los vivos acuden a recordar que una voluntad bastó para llenar un muro: la de quien dio las órdenes, cuya memoria el mundo prefirió no amar.', 'Sobre la ceniza de {lugar} se alzó un muro, y en él los nombres de los que murieron por su orden, tan numerosos que la luz, al caer sobre ellos, parece cargar con todos los mundos a la vez.'],
  ]);
  F('legado_hijos', [
    ['Dejó descendencia: {hijos}.', 'La herencia enfrentó a su descendencia: {hijos}.', 'Sin amparo quedó su descendencia: {hijos}.'],
    ['L{o|a} sobrevivió su descendencia, que siguió viviendo con holgura y sin sobresaltos: {hijos}.', 'Quedó al frente de la casa su descendencia, que no se puso de acuerdo en casi nada: {hijos}.', 'Murió dejando a {hijos} sin su amparo, en tiempos en que quedarse sin un nombre poderoso era quedarse a la intemperie.'],
    ['Su descendencia mantuvo encendida la lámpara de la casa, y en ella vivieron, con apellido propio y carácter distinto del suyo: {hijos}.', 'Sus herederos pasaron el luto con un ojo en la herencia y otro en los vecinos; la casa quedó en manos de {hijos}, a quienes tocó decidir cuánto pesaba el apellido.', 'Un apellido que pesaba como una losa y nadie que lo defendiera: eso heredó su descendencia, y el luto cayó sobre {hijos}, a quienes en adelante se nombró siempre junto a {él|ella}.'],
    ['Con {nom} se extinguió una generación, pero no una casa: la crónica registra a su descendencia, {hijos}, sobre quienes caía ahora el peso de su apellido y de sus hechos.', 'Los herederos de sangre de {pila} cargaron con un nombre ilustre y un rastro de enemigos: {hijos}, que las crónicas mencionan siempre a la sombra de quien los engendró.', 'Su muerte dejó a {hijos} en un mundo que ya no los protegía: huérfanos y perseguidos por los rivales de la casa, aprendieron a la fuerza que apellidarse como quien fue poderoso no es una defensa, sino un blanco.'],
    ['Cada generación deja su semilla, y la suya fue su descendencia, {hijos}: ramas jóvenes de un árbol que cayó, y en las que el viento de los años siguió reconociendo el perfil del tronco.', 'Los hijos de los grandes llevan una carga que ninguna otra persona conoce: la de ser, a la vez, recuerdo y reproche; esa fue la herencia de {hijos}, y el mundo no les concedió dejarla.', 'La noche cayó sobre su casa y los suyos quedaron solos ante el mundo: {hijos}, que cargaron con el apellido como se carga una antorcha cuando el viento arrecia, sabiendo que podía alumbrarlos o quemarlos.'],
  ]);
  F('legado_venganza', [
    ['{vengador} juró vengarl{o|a}.', 'La muerte quedó sin saldar: {vengador} prometió vengarl{o|a}.', 'Tras el entierro, {vengador} juró cobrarse su muerte.'],
    ['Pasado el luto, {vengador} decidió, sin ruido y sin prisa, que aquella muerte no quedaría sin respuesta y que había que dar con los culpables.', 'En voz baja, entre rencores mal contenidos, {vengador} juró vengarl{o|a}; los que oyeron la promesa supieron que no era una frase vacía.', 'En el mismo entierro, con las manos todavía manchadas de polvo, {vengador} juró vengarl{o|a} y apuntó en un cuaderno los nombres de los responsables.'],
    ['Lo que {vengador} sintió fue más hondo que la rabia: una especie de deuda serena, de las que se pagan con el tiempo; juró vengarl{o|a} y se puso a esperar, con una paciencia que daba miedo.', 'No hubo lágrimas en {vengador}: miró el cuerpo, guardó silencio y, ya a solas, prometió vengarl{o|a}; hay promesas que se hacen sin testigos y pesan más que cualquier juramento público.', 'Llevó {vengador} el duelo como se lleva una herida abierta y juró vengarl{o|a} con sangre; la cólera se le fue haciendo objetivo, y el objetivo, razón para vivir.'],
    ['Ante los consejos reunidos, {vengador} juró solemnemente vengar la muerte de {nom}, y la crónica registra la fórmula del juramento, el nombre de los testigos y la fecha, como se registra un tratado.', 'Un odio nuevo sembró la muerte de {pila}: {vengador} se comprometió a vengarl{o|a} y, según las crónicas, lo hizo con la frialdad de quien sabe que las deudas de sangre no prescriben.', 'Sobre el cadáver aún caliente, {vengador} alzó la mano y juró vengarl{o|a}, y aquel juramento, pronunciado entre lágrimas y gritos, fue el comienzo de una cadena de sangre que la historia aún no ha terminado de contar.'],
    ['En el silencio de los muelles, donde solo el viento de los conductos se atrevía a hablar, {vengador} juró vengarl{o|a}, y aquel juramento, hecho a las estrellas, empezó a girar como un astro oscuro sobre el destino de los mundos.', 'Hay muertes que no acaban, porque dejan a alguien con la sangre en vilo: {vengador} juró vengarl{o|a}, y su nombre, repetido cada noche como una consigna, se volvió una espada.', 'Cuando cubrieron su rostro, {vengador} se alzó de entre el duelo como se alza una sombra al caer la noche, y juró, por todo lo que aún le quedaba, vengarl{o|a}; y el mundo, que sabe de estas cosas, comprendió que la sangre llamaba a la sangre.'],
  ]);
  F('legado_epoca', [
    ['Una época entera lleva su marca: {epoca}.', 'Su tiempo se llama así, aunque no a gusto de todos: {epoca}.', 'Su época quedó marcada por la sangre: {epoca}.'],
    ['Aquellos años recibieron luego un nombre que los resume y que debe mucho a su paso por ellos: {epoca}.', 'Los historiadores bautizaron su tiempo con un nombre que unos aplauden y otros discuten: {epoca}.', 'Quienes vivieron aquellos años prefieren no recordar el nombre que la historia les dio, marcados como estaban por su paso: {epoca}.'],
    ['Como una moneda guarda su cuño, una época entera guarda su huella, y los almanaques, al nombrarla, aluden a su obra sin mencionarla: {epoca}.', 'Los cronistas no se pusieron de acuerdo sobre cómo llamar a su tiempo, pero ninguno pudo evitar que el nombre, al fin, recordara lo que {él|ella} dejó: {epoca}.', 'Marcados a fuego quedaron aquellos años, y el nombre con que los recuerda la historia aún sabe a ceniza: {epoca}.'],
    ['La historia reconoce en aquel tiempo la obra de {nom}, y lo ha hecho constar en el nombre mismo con que lo designa: {epoca}.', 'Pocas vidas han logrado teñir un tiempo entero; la de {pila} lo logró, para bien y para mal, y los anales conservan el nombre de aquel periodo como testimonio de una influencia que nadie pudo ignorar: {epoca}.', 'Fue su huella tan profunda y tan sangrienta que las crónicas rotularon aquel periodo con el nombre de una herida: {epoca}.'],
    ['Hay personas que pasan por el mundo y personas por las que el mundo pasa; de estas últimas fue {él|ella}, y su tiempo, rendido a su sombra, lleva ahora su sello: {epoca}.', 'Toda época es la sombra alargada de unos pocos, y la de {pila} fue larga como un río y honda como un pozo: las generaciones que vinieron después aprendieron a nombrar aquel tiempo así: {epoca}.', 'Ardieron los mundos bajo su estrella, y lo que quedó fue una época entera con su marca grabada a fuego en la memoria, como se graban las cicatrices en el hierro: {epoca}.'],
  ]);
  F('cuenta_muertes', [
    ['Muertos bajo su mando o por orden suya: {n}.', 'Según registros que se discuten, a su cuenta van muertos: {n}.', 'Por sus órdenes murieron, sin juicio previo: {n}.'],
    ['Al final, la cuenta de quienes murieron bajo su mando o por orden suya ascendía a {n}.', 'Se le atribuyen, entre muertos bajo su mando y muertos por su orden, un total de {n}, cifra que sus partidarios rebajan y sus enemigos engordan.', 'Quienes llevaron la cuenta de los muertos de su mando la dejaron en {n}, y cada uno de ellos tuvo un nombre.'],
    ['Quien revise los archivos hallará, ordenados con meticulosidad, los nombres de quienes murieron bajo su mando o por su orden: {n}, uno tras otro, en un registro limpio y sin adjetivos.', 'Hizo falta una comisión para contar a los muertos de su mando, y la comisión, tras disputas de cifras y de métodos, fijó la cuenta final en {n}.', 'La suma de los caídos bajo su mando o por su orden, contada despacio por los deudos, llegó a {n}; cada uno tuvo una cabina, un nombre y alguien que esperaba su regreso.'],
    ['Los anales consignan con fría exactitud el balance de su mando: entre los que cayeron bajo sus banderas y los que murieron por sus órdenes, {n}; cifra con la que la historia habrá de medirle.', 'La contabilidad de sus actos se hizo después de su muerte, a regañadientes, y arrojó una suma que nadie quiso leer en voz alta: {n}, entre ejecutados, caídos en combate y muertos por orden suya.', 'Entre los que cayeron bajo su mando y los que murieron por su orden, los cronistas contaron {n}, y señalaron que tras cada número había un rostro, una casa y un duelo que el Estado no quiso reconocer.'],
    ['Si las estrellas llevaran cuenta de las vidas, anotarían junto a su nombre {n}: tantas fueron las que se apagaron bajo su mando o por su voz, y en cada una dejó una huella que el tiempo no borró.', 'Hay balances que pesan más que los mundos: el suyo, escrito con tinta y con ceniza, dice {n}, y la historia, que todo lo suma, lo lleva siempre a su cuenta como un lastre que ninguna gloria compensó.', 'Una marea de muertos siguió a su nombre, y cuando por fin se retiró quedó el recuento: {n}, tantos como granos de ceniza deja un incendio, y cada uno murió bajo su mando o por una orden que salió de su boca.'],
  ]);
  F('cuenta_manos', [
    ['Muertos por sus propias manos: {n}.', 'Con sus propias manos mató a {n}, según el registro.', 'Víctimas de su mano directa: {n}. Sin condena alguna.'],
    ['A lo largo de su vida mató con sus propias manos, y sin alardes, a {n}.', 'Sus enemigos decían que había matado con sus propias manos a {n}, y {él|ella} nunca lo desmintió.', 'Llevaba la cuenta, aunque nadie se la pidiera: a mano, sin armas ajenas ni órdenes de otros, había matado a {n}.'],
    ['Nunca presumió de ello, pero sus manos, anchas y llenas de cicatrices, habían matado a {n}; guardaba memoria de cada muerte, con la misma calma con que se recuerdan las rutas de un viaje largo.', 'Se contaba en los puertos que tenía las manos manchadas con la sangre de {n} y que, de noche, no lograba dormir más de unas horas seguidas; {él|ella} lo negaba con una sonrisa que no engañaba a nadie.', 'Había matado a {n} con sus propias manos, a corta distancia y a la cara, y esos rostros fueron volviendo, noche tras noche, a visitarl{o|a} sin que hubiera modo de ahuyentarlos.'],
    ['Las crónicas, que no suelen entrar en esas cuentas, anotan que {nom} mató con sus propias manos a {n}, y lo hacen como quien registra una circunstancia más de una vida pública.', 'Se afirmaba, y nunca se logró probar del todo, que {pila} había dado muerte con sus propias manos a {n}; la leyenda, que no necesita pruebas, convirtió la cifra en una sombra que acompañó su nombre.', 'De todas las muertes que se le atribuyen, las que cometió con sus propias manos suman {n}; los testigos hablan de golpes secos, de miradas que no parpadeaban y de un silencio que seguía a cada una como un eco.'],
    ['Dicen que sus manos eran de hierro y de ceniza, y que con ellas segó, una a una y sin ayuda, a {n}; la leyenda añade que el metal de aquellas manos aprendió a no temblar.', 'La sangre de {n} corrió por sus manos, y no hubo agua en todos los depósitos del mundo que pudiera lavarla; así lo cuentan los viejos de los muelles, y así lo creyó {él|ella} hasta el final.', 'Nadie tuvo que empuñar arma por {él|ella}: eran sus manos, solo sus manos, las que dieron muerte a {n}, y cada una de esas muertes quedó impresa en su carne como un nombre grabado en el acero.'],
  ]);
  F('vive', [
    ['Sigue viv{o|a}: tiene {edad} años y está en {lugar}.', 'Vive en {lugar}, con {edad} años. Pocos le dirigen la palabra.', 'Tiene {edad} años y vive en {lugar}, sin salud ni dinero.'],
    ['Todavía vive: a sus {edad} años reside en {lugar}, donde lleva una vida tranquila y rutinaria.', 'Aferrad{o|a} a lo que le queda de influencia, sigue en {lugar} a sus {edad} años, vigilando de reojo a los que esperan su turno.', 'Malvive en {lugar}, enferm{o|a} y sol{o|a}, con sus {edad} años a cuestas, esperando una muerte que no acaba de llegar.'],
    ['Los años no l{o|a} han doblegado: a sus {edad} años, en {lugar}, se levanta cada mañana con la luz de los filtros y repasa sus recuerdos como quien repasa una colección de mapas.', 'Ya tiene {edad} años y sigue en {lugar}, con el aire de quien aún tiene cuentas pendientes; los que l{o|a} conocen saben que su silencio no es resignación, sino espera.', 'A los {edad} años sobrevive en {lugar} entre ruinas de lo que fue: ha perdido el mando, los amigos y buena parte de la memoria, y los que pasan a su lado ya no recuerdan quién es.'],
    ['Aún vive {nom}, que a sus {edad} años reside en {lugar}, retirad{o|a} de la vida pública; los cronistas l{o|a} visitan con respeto, como quien visita un monumento que todavía respira.', 'A muchos les parecía ya cosa del pasado, y sin embargo {pila} sigue en {lugar}, a sus {edad} años: de nombre temido pasó a sombra que atraviesa los pasillos sin que nadie se vuelva a mirar.', 'Sin más que el aliento, tras haberlo perdido todo, vive aún a los {edad} años en {lugar}; la crónica, que ya ha cerrado un capítulo sobre {él|ella}, deja una página en blanco por si la historia aún tiene algo que añadir.'],
    ['Camina, a los {edad} años y en {lugar}, como camina quien ha cruzado épocas enteras con la espalda recta, y todavía hay mundos que se detienen cuando {él|ella} pasa.', 'En {lugar} vive, con {edad} años a cuestas, alguien que ya empieza a estorbar a los vivos: demasiad{o|a} grande para morir, demasiad{o|a} vie{jo|ja} para mandar y, siempre, más recordad{o|a} que presente.', 'Sobrevive, pero ya no es de este mundo: a los {edad} años, en {lugar}, camina entre las ruinas de su propia gloria, y los que l{o|a} miran no saben si contemplan a una persona o a la sombra de lo que fue.'],
  ]);
  F('vive_preso', [
    ['Sigue viv{o|a}, pres{o|a} en {lugar}.', 'Vive pres{o|a} en {lugar}, sin juicio.', 'Aislad{o|a} en una celda de {lugar}, sin visitas.'],
    ['Cumple su encierro en {lugar} sin quejas, con horario fijo y los libros que le permiten.', 'En {lugar} sus carceleros no se fían de {él|ella} ni dormid{o|a}: l{o|a} vigilan de día y de noche, y {él|ella} lo sabe y los desafía con la mirada.', 'Languidece en una celda de {lugar}, sin luz natural ni noticias del exterior, mientras se deshace poco a poco el recuerdo de lo que fue.'],
    ['Pasa los días en {lugar} tras unos muros que ya conoce como a un viejo compañero; lee, escribe, pasea en círculos por el patio, y parece haber hecho las paces con su encierro.', 'Pres{o|a} en {lugar}, escribe cartas que no sabe si llegan y planea lo que haría si volviera a salir; sus carceleros lo saben y le registran la celda a menudo.', 'La celda de {lugar} es ya toda su vida: apenas ve la luz, apenas oye una voz, y cada día se parece más al anterior que a cualquier recuerdo; aún respira, y no se sabe si es un castigo o una forma de olvido.'],
    ['Encerrad{o|a} en {lugar} por decisión de los consejos, {nom} cumple una pena que la crónica considera ejemplar; la visita periódica de los delegados es el único vínculo con el mundo.', 'Tras los muros de {lugar} vive {pila} aislad{o|a} y vigilad{o|a}: los vencedores no se atreven a ejecutarl{o|a} ni a liberarl{o|a}, y l{o|a} guardan como se guarda una bomba sin desactivar.', 'Detrás de las puertas de {lugar} sigue con vida, privad{o|a} de todo salvo del recuerdo; la historia l{o|a} señala como ejemplo de lo que ocurre a quien pierde, y los que l{o|a} visitan, de tarde en tarde, no vuelven del todo iguales.'],
    ['La leyenda no ha muerto, y tampoco quien la encarna: en {lugar}, tras muros de acero, un nombre que fue de multitudes vive ahora entre paredes, y los que pasan cerca bajan la voz como se baja ante un monumento.', 'Quien un día hizo temblar mundos está hoy encerrad{o|a} en {lugar}, y los guardianes cuentan que ni siquiera la cadena le resta altura: sigue siendo un rival al que se vigila con las armas en la mano.', 'En las profundidades de {lugar}, entre sombras de acero y silencios más largos que una noche sin estrellas, sigue vivo el nombre que hizo temblar a los mundos, y no hay llave que lo cierre del todo: algo de {él|ella}, sin remedio, sigue fuera.'],
  ]);
  F('cierre', [
    ['No hay más que contar.', 'El expediente se cerró con asuntos pendientes.', 'Fin del registro. Nadie l{o|a} lloró.'],
    ['Fue una vida como tantas, y se cerró sin ruido; quedaron los hechos y casi ninguna pregunta.', 'Una vida de aciertos y de cuentas sin saldar: eso es todo lo que puede decirse con honradez.', 'Terminó mal lo que había empezado con algo de promesa, y de ello solo quedó un puñado de lágrimas sinceras.'],
    ['Como el agua que corre por una canalización antigua, aquella vida siguió su curso hasta el final, sin estrépito, y dejó el suave sabor de lo que ha sido cumplido con calma.', 'Hay vidas que se resuelven como una disputa larga: nadie gana del todo, nadie pierde por completo, y al final solo queda el cansancio de haberlas presenciado.', 'Tal fue su paso por el mundo: un fulgor, un estrago y un silencio; quienes lo presenciaron no supieron si llorar o respirar aliviados.'],
    ['Así concluye la historia de una vida que importó a los mundos, y que la crónica cierra con respeto: hizo lo que pudo, lo que debió y no siempre lo que quiso.', 'La historia, que rara vez perdona y casi nunca absuelve, deja esta vida en el aire, a mitad de camino entre la gloria y la condena; que cada generación decida de qué lado la pone.', 'Quedan las cenizas, la sangre y el eco de un nombre; la historia, tras sopesarlos, los anota juntos, sin consuelo, en el libro de lo que no debió ocurrir y ocurrió.'],
    ['Pasan los Estados y se apagan los soles; de cuanto fue grande solo queda lo que se hizo con las manos y se dijo con valor: así se mide una vida.', 'Toda gloria es una deuda y toda deuda es una sombra: esta vida fue ambas cosas, y el mundo, que la cobró entera, no sabe todavía si pagó o si perdió.', 'Y el viento de las estaciones vacías se llevó lo demás: el nombre quedó en la piedra, la sangre en la memoria y la sombra en el camino de quienes vinieron después, para que supieran qué cuesta ser grande.'],
  ]);
})(typeof globalThis !== 'undefined' ? globalThis : this);
