// Frases del grupo «figuras». Cada hueco: 5 filas (épica 0..4) × 3 columnas (drama 0..2).
(function (g) {
  'use strict';
  const F = g.SIM.frases;
  F('figura_caudillo', [
    ['Dirigió {faccion}. Su nombre se conoce en {n} mundos.', 'Entre disputas internas, capitaneó {faccion}. Conocid{o|a} en {n} mundos.', 'Con bajas constantes, sostuvo {faccion}. Conocid{o|a} en {n} mundos.'],
    ['Fue sumando voluntades hasta tener tras de sí {faccion}; su nombre ya sonaba en {n} mundos.', 'Mantuvo unidos a los suyos en {faccion} a fuerza de promesas y de miedo, y su nombre pesaba ya en {n} mundos.', 'Enterró a muchos de los suyos para mantener en pie {faccion}; su nombre llegó a {n} mundos.'],
    ['Recibía a cualquiera en su mesa, y de tanta conversación armó {faccion}; su nombre viajó por {n} mundos en bodegas y rumores.', 'Sonreía al hablar y no perdonaba una deslealtad; así tejió {faccion}, con hilos de gratitud y de deuda, hasta que su nombre se oyó en {n} mundos.', 'Armó {faccion} sobre los cadáveres de sus primeros compañeros, y cada uno fue una piedra más; ya en {n} mundos se pronunciaba su nombre.'],
    ['Los anales consignan que supo convertir un rumor de muelles en un poder duradero, {faccion}, y que su nombre se pronunciaba ya en {n} mundos.', 'Nadie ocultó el precio: para sostener {faccion} hubo desterrados, rivales callados y pactos rotos. Su nombre, sin embargo, llegó a {n} mundos.', 'La crónica anota lo que costó sostener {faccion}: los mejores lugartenientes cayeron uno tras otro, y fue sobre sus tumbas donde su nombre llegó a {n} mundos.'],
    ['Dicen que bastó su voz para juntar {faccion}, y que su nombre cruzó el vacío como la luz hasta posarse en {n} mundos.', 'Se cuenta que quien juraba lealtad ante {faccion} juraba también temor, y que amor y temor, trenzados, llevaron su nombre hasta {n} mundos.', 'La leyenda añade que sembró de sangre, propia y ajena, el camino que abrió para {faccion}, y que {n} mundos guardan su nombre como se guarda una herida.'],
  ]);
  F('figura_profeta', [
    ['Fundó {credo}; tiene fieles en {n} mundos.', 'Predicó {credo} ante autoridades hostiles; fieles en {n} mundos.', 'Murieron fieles suyos por {credo}; hay creyentes en {n} mundos.'],
    ['Empezó predicando en los muelles y acabó fundando {credo}, que hoy suma fieles en {n} mundos.', 'Predicó {credo} a pesar de las autoridades, que querían callar{lo|la}, y aun así reunió fieles en {n} mundos.', 'Difundió {credo} entre persecuciones y funerales, y los fieles que quedaron, repartidos por {n} mundos, juraron no olvidar{lo|la}.'],
    ['Hablaba en voz baja a quien quisiera oír{lo|la}, y con aquellas palabras sencillas se levantó {credo}, que tiene fieles en {n} mundos.', 'Predicaba al amanecer, entre estibadores, y lo que decía incomodaba a gobernadores y a mercaderes; aun así {credo} echó raíces en {n} mundos.', 'Seguía predicando {credo} mientras ardían los templos de sus primeros fieles, y de aquellas cenizas brotó una fe que hoy tiene altares en {n} mundos.'],
    ['Los cronistas l{o|a} recuerdan como quien fundó {credo}, fe que hoy congrega a creyentes en {n} mundos.', 'Con su prédica, {credo} dividió a familias y a Estados; ni los edictos ni los destierros impidieron que llegara a {n} mundos.', 'La crónica asienta que fundó {credo} entre hogueras y destierros, y que su sangre y la de sus discípulos abonó la fe que hoy profesan fieles en {n} mundos.'],
    ['Dicen que oyó una voz en el silencio del vacío y que de esa voz hizo {credo}; {n} mundos la repiten ahora cuando se apagan las luces.', 'Cuentan que {credo} nació de una duda y de un desafío a los poderosos, y que ni la espada ni el decreto lograron cerrarle el paso hasta {n} mundos.', 'Hay quien jura que antes de callar ofreció su vida y la de los suyos, y que {credo} creció a costa de sangre, la suya primero, hasta alzar altares en {n} mundos.'],
  ]);
  F('figura_martir', [
    ['Mártir tras su muerte; {n} mundos protestaron.', 'Muerte disputada, que l{o|a} hizo mártir; protestas en {n} mundos.', 'Muerte violenta; pasó a mártir; disturbios en {n} mundos.'],
    ['Su muerte fue lamentada en {n} mundos, y con el tiempo l{o|a} llamaron mártir.', 'A unos indignó y a otros convino su muerte; en {n} mundos hubo protestas y empezaron a llamar{lo|la} mártir.', 'Murió a manos de quienes temían su voz, y {n} mundos salieron a la calle con luto y con piedras; desde entonces es mártir.'],
    ['Se apagó sin estruendo, pero la noticia fue de puerto en puerto y {n} mundos salieron a la calle, en silencio, a despedir{lo|la}; desde ese día es mártir.', 'Cuando se supo cómo murió, los muelles dejaron de trabajar; en {n} mundos hubo huelgas, pintadas y disputas por quién tenía derecho a su memoria.', 'La noticia de su muerte llegó con la sangre aún caliente; {n} mundos ardieron esa semana, y entre el humo su nombre empezó a ser bandera.'],
    ['Los cronistas fechan en su muerte el nacimiento de un culto cívico: {n} mundos guardaron luto y su nombre quedó escrito entre los de los mártires.', 'Su muerte partió en dos a la opinión pública: quienes l{o|a} lloraban llenaron las calles de {n} mundos, y quienes l{o|a} temían callaron, pero no por mucho tiempo.', 'Al saberse su fin, {n} mundos se echaron a las calles; hubo cargas, hubo caídos, y de aquella sangre derramada en su nombre salió un martirologio.'],
    ['Dicen que su última palabra aún viaja por el vacío, y que {n} mundos la oyeron a la vez y supieron, sin que nadie se lo dijera, que había nacido un mártir.', 'Cuentan que los poderosos creyeron enterrar su nombre con {él|ella} y lo plantaron sin saberlo: de él brotaron, en {n} mundos, las banderas que no dejaron de ondear.', 'Hay quien jura que murió y que la noche entera se llenó de gritos: {n} mundos se alzaron a la vez, y la sangre de aquel día no se borró jamás de su nombre.'],
  ]);
  F('figura_invicto', [
    ['Ganó {n} batallas y no perdió ninguna.', 'Invict{o|a} en {n} batallas; los rivales l{o|a} envidiaban.', 'Venció en {n} batallas, ninguna perdida; pagó cada una con bajas.'],
    ['Libró {n} batallas al mando de sus flotas y salió victorios{o|a} de todas.', 'No perdió ni una de {n} batallas, y cada victoria le granjeó un enemigo más en la corte.', 'Encadenó {n} victorias a costa de tripulaciones enteras; ninguna batalla perdida, y cada una dejó su cuenta de muertos.'],
    ['Maniobraba con la calma de quien ya conoce el resultado, y {n} batallas después seguía sin saber lo que era una derrota.', 'Ninguna de sus {n} batallas acabó en derrota, y de tanto ganar empezó a resultar incómod{o|a} para quienes l{o|a} habían nombrado.', 'Triunfó en {n} batallas y las lloró todas en privado: no hubo una sola en la que no dejara atrás los cascos rotos de sus naves y los nombres de los suyos.'],
    ['Los anales l{o|a} cuentan entre los grandes almirantes: {n} batallas libradas, ninguna perdida, y una flota que le obedecía como un solo cuerpo.', 'Los cronistas apuntan que, tras {n} batallas sin derrota, ya no había almirante rival ni consejo que no l{o|a} mirara con recelo.', 'La crónica registra {n} batallas ganadas y renuncia a sumar los muertos: ningún enemigo logró vencer{lo|la}, pero cada victoria dejó la cubierta resbalosa de sangre.'],
    ['Dicen que el vacío mismo se apartaba ante su flota, y que en {n} batallas ninguna estrella vio retroceder su estandarte.', 'Cuentan que ganó {n} batallas sin perder una, y que por eso los suyos le temían más que sus enemigos: de quien nunca cae se espera que un día se alce.', 'La leyenda dice que se alzó invict{o|a} de {n} batallas y que en cada una dejó un jirón de alma entre los restos; vencedor{|a} de todos, no pudo con el silencio de las cubiertas vacías.'],
  ]);
  F('figura_reformador', [
    ['Gobernó {estado}; bajó impuestos y abrió depósitos.', 'Reformas contestadas por los notables durante su gobierno de {estado}.', 'Reformó {estado} pese a un atentado.'],
    ['Gobernó {estado} con mano templada: bajó los tributos y abrió los depósitos de grano al pueblo.', 'En {estado} rebajó los tributos y abrió los depósitos, y los notables l{o|a} acusaron de arruinar al Estado.', 'Bajó tributos y abrió depósitos en {estado}; las reformas costaron la vida a varios de sus ayudantes, y a {él|ella} le costaron el sueño.'],
    ['Recorría los almacenes de {estado} con un cuaderno en la mano; cuando acabó, los tributos eran más leves y no había un depósito cerrado al hambriento.', 'En {estado} repartió el grano de los depósitos y aligeró los tributos; los notables, ofendidos en su bolsillo, empezaron a tramar contra {él|ella}.', 'Mientras en {estado} se abrían los depósitos y bajaban los tributos, en las sombras se afilaban los cuchillos de quienes perdían privilegios.'],
    ['Los historiadores de {estado} l{o|a} recuerdan como reformador{|a}: bajó los tributos, abrió los depósitos y dejó un Estado más justo que el que halló.', 'Su gobierno de {estado} alivió al pueblo con tributos menores y depósitos abiertos, pero se ganó el odio de las casas que vivían del hambre ajena.', 'Los anales de {estado} consignan sus reformas, tributos recortados y depósitos abiertos, y consignan también el precio: los suyos fueron cayendo uno a uno a manos de los privilegiados.'],
    ['Dicen que en {estado} abrió los depósitos como quien abre las puertas del día, y que bajo su mano los tributos pesaron como plumas.', 'Cuentan que en {estado} dio de comer al hambriento y que aquellos a quienes quitó la mesa jamás se lo perdonaron.', 'Hay quien jura que {estado} l{o|a} lloró con graneros abiertos y tributos olvidados, y que fue la gratitud del pueblo lo único que la daga de sus enemigos no pudo cortar.'],
  ]);
  F('figura_tirano', [
    ['Gobernó {estado} con dureza; purgó a {n} personas.', 'Purgas en {estado}: {n} rivales eliminados; nadie se fiaba.', 'Hubo ejecuciones en {estado}; purgó a {n} personas.'],
    ['Con puño firme y {n} rivales purgados, nadie le discutió el sitio en {estado}.', 'Purgó a {n} personas en {estado} y gobernó entre rumores y delaciones; en cada mesa había un oído de más.', 'En {estado} mandó purgar a {n} personas, y los patios de las prisiones se llenaron de ecos y de nombres tachados.'],
    ['No levantaba la voz nunca; en {estado} bastaba una lista firmada en silencio, y {n} personas desaparecieron de los registros sin un solo grito.', 'Escuchaba puertas en {estado}: {n} purgados enseñaron a todos que callar era la única manera de seguir respirando.', 'En {estado} los vecinos aprendieron a cerrar las ventanas: {n} personas fueron purgadas, y cada madrugada trajo otra lista, otro silencio.'],
    ['Los anales de {estado} l{o|a} retratan como tiran{o|a} metódic{o|a}: purgó a {n} rivales con papeles en regla y mantuvo el orden a base de ausencias.', 'Durante su gobierno {estado} vivió bajo sospecha: {n} purgados, delatores en cada muelle y un miedo tan extendido que se confundía con la costumbre.', 'La crónica de {estado} guarda con espanto la cuenta: {n} purgados, fosas sin nombre y un pueblo que aprendió a no preguntar por los suyos.'],
    ['Dicen que su sombra cubría {estado} de un puerto a otro, y que {n} nombres borrados bastaron para que nadie osara decir el suyo.', 'Cuentan que en {estado} hasta el eco se callaba al pasar {él|ella}: {n} purgados, y el miedo se volvió la única ley que nadie quebrantó.', 'Hay quien jura que {estado} se quedó sin lágrimas: tras {n} purgados, el pueblo lloraba hacia dentro, y el miedo recorría las calles con paso de dueño.'],
  ]);
  F('figura_genio', [
    ['Ingenier{o|a} de {estado}; sus diseños se usaron durante años.', 'Diseños suyos, muy discutidos, acabaron adoptados por {estado}.', 'Trazó planos decisivos para {estado} y no los vio terminados.'],
    ['Sus diseños de naves y reactores dieron a {estado} una generación de ventaja sobre sus rivales.', 'Los generales de {estado} se disputaron el mérito de unos diseños que daban una generación de ventaja, y apenas se acordaron de {él|ella}.', 'El esfuerzo de dar a {estado} una generación de ventaja con sus diseños l{o|a} dejó exhaust{o|a} y medio cieg{o|a}.'],
    ['Dibujaba reactores en los márgenes de los partes de guardia, y de aquellos garabatos salieron las naves que dieron a {estado} una generación de ventaja.', 'Cada diseño suyo era un golpe de ingenio y una discusión con el almirantazgo; con ellos {estado} se adelantó una generación a sus rivales, y nadie le dio las gracias.', 'Sus planos pusieron a {estado} una generación por delante, y también pusieron en sus manos máquinas que mataron a mucha gente; no volvió a dormir sin soñar con ellas.'],
    ['Los anales de la ingeniería l{o|a} cuentan entre los grandes: sus diseños dieron a {estado} una generación de ventaja que ningún rival logró cerrar.', 'Sus diseños dieron a {estado} una generación de ventaja, y los cortesanos, celosos, trataron de apropiárselos antes de que se enfriara la tinta.', 'Los archivos de {estado} custodian sus diseños y la nota fúnebre de quienes los probaron: la ventaja de una generación se pagó con naves perdidas y con tripulaciones enteras.'],
    ['Dicen que oía hablar a los metales, y que de esa conversación sacó los diseños que adelantaron a {estado} una generación entera.', 'Cuentan que {estado} le debió una generación de ventaja y que el almirantazgo se la cobró en silencio: quien sabe tanto, mandaron, no debe salir nunca de la sala de planos.', 'La leyenda dice que levantó con sus manos el ingenio de {estado} una generación por delante de todos, y que cada pieza que forjó se llevó consigo un pedazo de su vida.'],
  ]);
  F('figura_rey_pirata', [
    ['Re{y|ina} pirata; {n} naves bajo su mando.', 'Sus {n} naves piratas le obedecían, pero sus capitanes desconfiaban.', 'Capitaneó {n} naves y perdió a muchos de los suyos.'],
    ['Juntó bajo su bandera a {n} naves de renegados y se hizo respetar en todos los puertos.', 'Mandaba {n} naves piratas y ninguno de sus capitanes se fiaba de otro; la bandera común duraba lo que durase el botín.', 'Reunió {n} naves bajo su bandera negra, y cada saqueo dejó puertos incendiados y tripulaciones sin retorno.'],
    ['Repartía el botín a partes iguales y bebía con la tripulación de cualquiera; por eso {n} naves se pusieron bajo su bandera sin que mediara una orden.', 'Gobernaba {n} naves a golpe de pactos y de amenazas; dormía con el sable al alcance, porque sabía que cada capitán de su flota soñaba con la corona.', 'Sus {n} naves dejaron una estela de puertos ardidos y mercantes a la deriva; el humo del último asalto aún no se había disipado cuando ya preparaba el siguiente.'],
    ['La crónica de los muelles l{o|a} nombra soberan{o|a} de la piratería: {n} naves obedecían su bandera y ni los Estados se atrevían a cruzarle la ruta.', 'Con {n} naves bajo su bandera tuvo en jaque a los puertos de medio sector; pero el pacto entre piratas es de papel mojado, y los suyos empezaron a mirarle la espalda.', 'Los anales mencionan {n} naves bajo su bandera y mencionan los asaltos: tripulaciones pasadas a cuchillo, bodegas vaciadas y una ruta comercial convertida en cementerio.'],
    ['Dicen que {n} naves siguieron su bandera como siguen las lunas a un planeta, y que el vacío entero era su reino.', 'Cuentan que gobernó {n} naves sin más ley que el miedo y la codicia, y que su corona era una soga que cada noche se le apretaba un poco más.', 'Hay quien jura que {n} naves bajo su bandera dejaron el vacío sembrado de restos, y que el espacio, harto de pagar, aún cobra aquella cuenta.'],
  ]);
  F('figura_unificador', [
    ['Sumó {n} mundos a {estado}; los integró.', 'Anexionó {n} mundos a {estado} entre protestas locales.', 'Hubo muertos al unir {n} mundos a {estado}.'],
    ['Fue anexando mundos hasta sumar {n} a {estado}, y logró que se sintieran parte de él.', 'A base de tratados y presiones agregó {n} mundos a {estado}, y no todos se sintieron parte del conjunto.', 'Los que se resistieron a entrar en {estado} pagaron caro, y los {n} mundos reunidos aprendieron a llamarse del Estado.'],
    ['Viajó de mundo en mundo con más palabras que armas, y cuando regresó, {estado} tenía {n} mundos nuevos que se sentían en casa.', 'Entre pactos, becas y amenazas fue cosiendo {n} mundos a {estado}; los remiendos se veían, pero sostenían.', 'Cosió {n} mundos a {estado} con hilo de promesas y con hilo de fuego, y las costuras todavía sangraban cuando alzó la bandera común.'],
    ['Los historiadores de {estado} l{o|a} llaman unificador{|a}: sumó {n} mundos al Estado y consiguió que se sintieran parte de una sola casa.', 'Bajo su mano, {estado} se extendió sobre {n} mundos; la unidad fue más obra de la fuerza que del afecto, y los recelos quedaron enterrados, no muertos.', 'La crónica deja constancia de que sumó {n} mundos a {estado} y de lo que costó: ciudades tomadas, jefes locales ejecutados, una paz firmada sobre ceniza.'],
    ['Dicen que llamó a {n} mundos por su nombre, uno a uno, y que todos respondieron: desde entonces son {estado} y se reconocen en una sola bandera.', 'Cuentan que {n} mundos se rindieron a su palabra o a su espada, y que {estado} nació de esa mezcla de ruego y de miedo que ningún mundo olvida.', 'La leyenda dice que juntó {n} mundos en {estado} con el hierro y con el fuego, y que la bandera común ondeó sobre más tumbas que cunas.'],
  ]);
  F('figura_sanador', [
    ['Cuidó a los enfermos en la peste de {lugar}.', 'Pocos agradecieron lo que hizo por los enfermos en la peste de {lugar}.', 'Enfermó también, tras atender a los apestados de {lugar}.'],
    ['Durante la peste de {lugar} no se apartó de los enfermos mientras los demás se marchaban.', 'En la peste de {lugar} atendió a los enfermos mientras las autoridades huían y el vecindario le cerraba las puertas por miedo al contagio.', 'Con los enfermos de {lugar} permaneció hasta que ya no quedó quien enterrase a los muertos, y cayó enferm{o|a} entre ellos.'],
    ['Cuando la peste vació las calles de {lugar}, siguió recorriendo las casas con un maletín de remedios y una paciencia que nadie más tuvo.', 'En {lugar} la peste dividió a la gente entre los que huían y los que se quedaban a mirar; {él|ella} se quedó a curar, y nadie supo si l{o|a} movía la bondad o la terquedad.', 'Cerró los ojos a más muertos de los que pudo contar en la peste de {lugar} y no dejó de curar; cuando por fin se detuvo, tenía las manos llagadas y la voz rota.'],
    ['Los cronistas de {lugar} l{o|a} recuerdan como sanador{|a}: en los meses de la peste atendió a los enfermos cuando todos huían, y no pidió nada.', 'Mientras la peste devoraba {lugar}, los notables huyeron y el pueblo temió al contagio; {él|ella} cuidó a los enfermos y, por no huir, fue señalad{o|a} como portador{|a} del mal.', 'La crónica de {lugar} guarda su nombre junto al de los muertos de la peste: curó a los enfermos cuando todos huían, y por cada vida salvada enterró a otra.'],
    ['Dicen que la peste de {lugar} pasó junto a {él|ella} sin tocar{lo|la}, como si el mal respetara a quien no le temía, y que los enfermos sanaban con solo oír su paso.', 'Cuentan que en la peste de {lugar} todos huyeron salvo {él|ella}, y que los huidos, al volver, no supieron mirar{lo|la} a los ojos.', 'Hay quien jura que se quedó en {lugar} cuando la peste llamaba puerta por puerta, y que fue velando a los moribundos como se fue gastando, hasta que de {él|ella} no quedó más que la luz de la lámpara.'],
  ]);
  F('figura_rubicon', [
    ['Volvió su flota contra la capital de {estado}.', 'Desobedeció y apuntó su flota a la capital de {estado}; la tropa l{o|a} siguió.', 'Atacó la capital de {estado} con su flota; hubo muertos.'],
    ['Dio la orden de poner proa a la capital de {estado}, y la flota, leal a {él|ella} antes que al Estado, obedeció.', 'Volvió su flota contra la capital de {estado} sabiendo que los soldados seguirían a {él|ella} y no al gobierno; el gobierno también lo sabía.', 'La flota viró hacia la capital de {estado} con {él|ella} al frente, y en el primer cruce de disparos cayeron soldados que hasta la víspera habían jurado la misma bandera.'],
    ['Una mañana ordenó rumbo a la capital de {estado} sin levantar la voz, y los soldados, que le eran leales a {él|ella} y no al Estado, obedecieron como quien cumple un hábito.', 'Entre el juramento al Estado y la lealtad de sus soldados eligió a estos últimos; con la flota apuntando a la capital de {estado}, en palacio nadie durmió aquella noche.', 'Cruzó el punto sin retorno con la flota entera hacia la capital de {estado}; la tropa l{o|a} siguió, y disparó contra hermanos de uniforme.'],
    ['La crónica anota que, cuando volvió la flota contra la capital de {estado}, los soldados eligieron seguir{lo|la} antes que obedecer al Estado, y que esa elección cambió el curso de una época.', 'Unos lo llamaron traición y otros fidelidad: volvió su flota contra la capital de {estado}, y los soldados, leales a {él|ella} y no al Estado, no dudaron.', 'Cuando la flota apareció sobre la capital de {estado}, el Estado supo que ya no mandaba sobre sus soldados; hubo asalto, hubo incendio, y la ciudad pagó la lealtad de la tropa a quien la mandaba.'],
    ['Dicen que cruzó con la flota entera una frontera que no estaba en ningún mapa, y que la capital de {estado} tembló sin que nadie hubiera disparado.', 'Cuentan que los soldados juraron al Estado con la boca y a {él|ella} con el alma, y que el día que la flota giró hacia la capital de {estado} se supo cuál de los dos juramentos pesaba más.', 'La leyenda dice que la flota se volvió contra la capital de {estado} como una marea de hierro, que la lealtad de los soldados fue un cuchillo, y que el Estado sangró por la herida de los suyos.'],
  ]);
  F('figura_traidor', [
    ['Abrió las puertas de {lugar} al enemigo.', 'Vendió la entrada del enemigo a {lugar} por unas promesas.', 'Dejó entrar al enemigo en {lugar}; hubo matanza.'],
    ['Franqueó el paso del enemigo a {lugar} y pasó a ser conocid{o|a} como traidor{|a}.', 'Pactó en secreto con el enemigo y le dejó abiertas las puertas de {lugar}, convencid{o|a} de que obraba por el bien de todos.', 'Esa misma noche el enemigo entró en {lugar} por una puerta sin cerrojo, y sus calles se llenaron de gritos y de humo.'],
    ['Una noche sin luna descorrió los cerrojos de {lugar} con sus propias manos, y el enemigo pasó sin disparar un solo tiro.', 'Tardó semanas en decidirse, y cuando por fin abrió las puertas de {lugar} al enemigo, ya no sabía si lo hacía por dinero, por miedo o por cansancio.', 'Dejó sin cerrojo las puertas de {lugar} y vio entrar por ellas a quienes, antes del alba, incendiaron su propia casa.'],
    ['La historia de {lugar} guarda su nombre como sinónimo de traición: abrió las puertas al enemigo y no hubo defensa que resistiera lo que dejó entrar.', 'Los anales de {lugar} no le perdonan haber dado paso al enemigo; los suyos aseguran que lo hizo por salvar vidas, pero ninguna vida salvada bastó para absolver{lo|la}.', 'La crónica asienta con vergüenza que, por sus manos, el enemigo entró en {lugar}: hubo saqueo, fuego y muertos sin cuento, y todos tuvieron un mismo nombre para quien abrió las puertas.'],
    ['Dicen que las puertas de {lugar} crujieron cuando l{o|a} vieron acercarse con la llave, y que desde aquella noche cada cerrojo lleva su nombre grabado por dentro.', 'Cuentan que malvendió {lugar} por un puñado de promesas, y que el enemigo, que sabe pagar la traición pero no honrarla, l{o|a} despreció aun antes de cruzar las puertas.', 'Hay quien jura que {lugar} ardió noche tras noche y que en todas se oyó, al fondo, el chirrido de la puerta que abrió {él|ella}, y que no hubo mano capaz de cerrar jamás.'],
  ]);
  F('ev_brote', [
    ['Se registran los primeros enfermos en {lugar}.', 'Los médicos de {lugar} recelan de una fiebre desconocida.', 'Mueren en {lugar} los primeros afectados por una fiebre sin nombre.'],
    ['Brota una peste en {lugar}; las autoridades piden calma.', 'La fiebre se extiende por {lugar} mientras las autoridades discuten si darle nombre de peste.', 'Estalla la peste en {lugar}: las primeras casas aparecen selladas, con los muertos dentro.'],
    ['En {lugar} se declara una peste silenciosa; en los muelles, los estibadores se miran la piel con inquietud.', 'La peste asoma en {lugar} entre rumores y desmentidos; el gobernador la niega y los enterradores no dan abasto.', 'Se desata la peste en {lugar}: en pocos días las calles huelen a lejía y a luto.'],
    ['Se declara oficialmente una peste en {lugar}; los archivos fijarán aquí el inicio de una época.', 'Avanza el contagio por los muelles de {lugar} mientras las casas mercantes callan para no perder los puertos: la peste ya tiene nombre.', 'La peste cae sobre {lugar} como un golpe de mazo: los hospitales se desbordan, las bodegas se llenan de cuerpos y nadie sabe de dónde viene.'],
    ['Una peste nueva despierta en {lugar}, y la historia, que aún no lo sabe, empieza a contar sus años desde esta fecha.', 'El mal que ha de recorrer la galaxia empieza en {lugar}: lo anuncian primero los rumores y luego los silencios.', 'Nace en {lugar} la peste que habrá de vaciar mundos; en sus calles el aire se vuelve espeso, y los vivos empiezan a contar a los muertos.'],
  ]);
  F('ev_peste_muertos', [
    ['La peste suma {n} muertos en {lugar}.', 'Crece el recelo en {lugar}: {n} muertos por la peste.', 'La peste mata ya a {n} personas en {lugar}; faltan enterradores.'],
    ['Los registros de {lugar} cuentan {n} muertos por la peste; el ritmo parece estabilizarse.', 'La peste lleva {n} muertos en {lugar}; la gente culpa a los puertos y los puertos culpan a la gente.', 'Con {n} muertos ya en {lugar}, la peste obliga a abrir fosas comunes junto a los hangares.'],
    ['En {lugar} los médicos anotan con paciencia la cifra de la peste: {n} personas fallecidas, y ningún signo de que el avance se detenga.', 'Tras {n} muertos en {lugar}, la peste ya no distingue entre casas ricas y pobres, y la calma de los notables se resquebraja.', 'La peste ha segado a {n} personas en {lugar}; las sirenas de duelo suenan sin descanso y ya nadie les hace caso.'],
    ['La crónica fija en {n} los muertos de la peste en {lugar} y anota que la población empieza a reorganizarse en torno al luto.', 'Partida en dos queda {lugar} con {n} muertos de peste: los que lo pierden todo y los que atrancan las puertas.', 'Los cementerios de {lugar} se agotan y los cuerpos esperan turno en las esclusas: {n} vidas lleva cobradas la peste.'],
    ['El recuento de la peste en {lugar} alcanza {n} muertos, y el silencio que sigue a la cifra es más largo que cualquier discurso.', 'En {lugar} ya son {n} los muertos de la peste, y el miedo, que no necesita contagio, se ha extendido más rápido que la fiebre.', 'La peste se ha llevado {n} vidas en {lugar}; los vivos andan como sombras entre los muertos, y no queda quien lleve la cuenta con la voz firme.'],
  ]);
  F('ev_cuarentena', [
    ['Se decreta cuarentena en {lugar}.', 'Cuarentena en {lugar}; los mercaderes protestan por las pérdidas.', 'Hay disturbios en el muelle de {lugar} por la cuarentena.'],
    ['{lugar} cierra el puerto por la peste y las naves esperan fuera, en órbita, a que pase el mal.', 'Las autoridades de {lugar} cierran el puerto por la peste; las casas mercantes amenazan con reclamar, y los guardias de la esclusa ya no discuten con nadie.', 'Con las esclusas de {lugar} selladas por la peste, las naves que llegan, aunque pidan auxilio, reciben por respuesta el silencio.'],
    ['En {lugar} se cierra el puerto y se enciende una luz roja sobre los muelles; la cuarentena empieza con orden, casi con ceremonia.', 'La cuarentena cae sobre {lugar}: puertos cerrados, mercancías podridas en las bodegas y vecinos que se miran desde las ventanas con sospecha.', 'La peste aísla {lugar}, y la cuarentena separa a familias a ambos lados de las esclusas; los que quedan fuera lloran contra el casco.'],
    ['Con la peste a las puertas, {lugar} decreta la cuarentena y cierra sus muelles; en los libros de rutas queda tachado un puerto entero.', 'La cuarentena de {lugar} aísla el contagio y también la economía: el puerto cerrado enfurece a las casas mercantes, y la gente teme más al hambre que al mal.', 'A cal y canto queda el puerto de {lugar} por la peste; las naves que se acercan son rechazadas a cañonazos, y en los muelles ya no hay quien recoja a los caídos.'],
    ['Todo el movimiento de {lugar} se detiene: por la peste, el puerto enmudece y las luces de atraque se apagan, una a una, como estrellas que mueren en orden.', 'Cuando {lugar} clausura el puerto por la peste, el comercio de medio sector contiene el aliento: ya nadie sabe quién será el siguiente en quedarse solo.', '{lugar} sella el puerto con la peste dentro; tras los muros, los vivos y los muertos comparten el mismo aire, y ninguna nave se atreve a responder a sus llamadas.'],
  ]);
  F('ev_peste_fin', [
    ['La peste remite; saldo final de {n} muertos.', 'Se frena la peste sin explicación: {n} muertos y muchas dudas.', 'Cierre de la peste: {n} muertos y varias casas vacías.'],
    ['La peste se retira poco a poco; los registros cierran la cuenta en {n} muertos.', 'Se da por terminada la peste: {n} muertos, y un reparto de culpas que apenas empieza.', 'Acaba la peste tras {n} muertos; los supervivientes vuelven a las calles sin atreverse a levantar la voz.'],
    ['La peste se apaga como una lámpara sin aceite; deja {n} muertos y los puertos vuelven, despacio, a abrir sus esclusas.', 'Se va la peste dejando {n} muertos y una desconfianza que tardará en curarse: nadie quiere volver a estrechar la mano del vecino.', 'La peste se detiene por falta de gente a quien matar: {n} muertos, barrios enteros vacíos y puertas con marcas de cal que nadie se atreve a borrar.'],
    ['Se declara extinguida la peste. Los archivos fijan en {n} los muertos y los años que vienen se contarán como los posteriores al mal.', 'Termina la peste con {n} muertos en total; los supervivientes se miran con alivio y con rencor, y los poderosos empiezan ya a discutir a quién culpar.', 'Pasa la peste tras {n} muertos; el aire vuelve a ser limpio, pero cada familia cuenta ya un nombre menos en la mesa.'],
    ['Al fin cede el mal, como si hubiera cumplido una tarea; quedan {n} muertos, y una galaxia que mirará el futuro con otra cautela.', 'Cuando por fin amaina el contagio, la galaxia cuenta {n} muertos y descubre que el mal más hondo fue el que sembró entre unos y otros: sospecha, destierro y puertas cerradas.', 'La peste se agota tras llevarse {n} vidas: lo que deja no es alivio sino un inmenso vacío en los muelles, en las mesas y en los nombres.'],
  ]);
  F('ev_arsenal', [
    ['Accidente en el almacén de núcleos de {lugar}: {n} muertos.', 'Hay {n} muertos y acusaciones de negligencia tras un accidente en el almacén de núcleos de {lugar}.', 'Explota un núcleo en el almacén de {lugar}: {n} muertos.'],
    ['Se recalienta un núcleo en el almacén de {lugar}; la contención se logra a tiempo, aunque con {n} muertos.', 'Una cadena de fallos en el almacén de núcleos de {lugar} se cobra {n} muertos; la dirección culpa al personal y el personal a la dirección.', 'Un núcleo del almacén de {lugar} se desgarra y arrastra a los vecinos: {n} muertos entre fuego y esquirlas.'],
    ['En el almacén de núcleos de {lugar} cede una junta y salta la primera chispa; la evacuación es ordenada, pero deja {n} muertos.', 'El almacén de núcleos de {lugar} estalla por descuidos acumulados: {n} muertos, y todo el mundo sabía lo que iba a pasar menos quien firmó las inspecciones.', 'Revienta en cadena el almacén de núcleos de {lugar}: {n} muertos, y la luz de la explosión se ve desde los puertos vecinos.'],
    ['Una reacción en cadena sacude el almacén de núcleos de {lugar} y borra de los planos varios muelles; {n} muertos y un debate abierto sobre la seguridad de los depósitos.', 'Tras la explosión del almacén de núcleos de {lugar}, con {n} muertos, el sector descubre que nadie vigilaba aquellos depósitos; empieza la caza de culpables.', 'Una cadena de núcleos revienta en {lugar} y arrasa distritos enteros: {n} muertos, sirenas durante días y un humo negro que no deja ver el horizonte.'],
    ['El almacén de núcleos de {lugar} se enciende como una segunda estrella: {n} muertos, y una luz tan blanca que durante un instante nadie en el sistema proyecta sombra.', 'Con el estallido del almacén de núcleos de {lugar} se rompe también la confianza del sector en sus depósitos: {n} muertos, y un miedo nuevo a lo que dormía bajo sus pies.', 'Revientan los núcleos de {lugar} uno tras otro, como golpes de un mismo tambor: {n} muertos, un cráter donde hubo barrios y un silencio que dura más que el eco.'],
  ]);
  F('ev_llamarada', [
    ['Llamarada solar en {sistema}; {n} personas se trasladan por precaución.', 'Evacuación desordenada de {n} personas por una llamarada en {sistema}.', 'Huyen {n} personas de {sistema} tras una llamarada; hay heridos.'],
    ['La estrella de {sistema} lanza una llamarada; {n} personas evacuan los muelles exteriores.', 'Evacuación apresurada ante una llamarada de la estrella de {sistema}: {n} personas huyen entre empujones y discusiones por las plazas en las naves.', 'Escupe una llamarada la estrella de {sistema}; {n} personas huyen, y las que no llegan a tiempo a los refugios quedan atrás.'],
    ['Un latigazo de luz sale de la estrella de {sistema}; las sirenas ordenan evacuar y {n} personas abandonan los muelles en filas, sin prisa visible.', 'Una llamarada de la estrella de {sistema} barre los puertos exteriores: {n} personas evacúan, y los pasajes en las naves se pagan a precio de oro.', 'Las antenas y los cascos más débiles se queman bajo la llamarada de la estrella de {sistema}; {n} personas huyen hacia los refugios y muchas no llegan.'],
    ['Una llamarada de una violencia que los registros no recuerdan sale de la estrella de {sistema}; se ordena evacuar y {n} personas huyen, mientras las flotas se reorganizan.', 'Una tormenta de la estrella de {sistema} obliga a evacuar: {n} personas huyen, los más ricos compran plazas y los pobres esperan en los muelles bajo una luz que quema.', 'Abrasa los muelles exteriores la llamarada de {sistema}; {n} personas huyen entre sirenas, y en los refugios llenos se cierran las puertas a quienes llegan tarde.'],
    ['Con un rugido de luz que cruza el sistema entero despierta la estrella de {sistema}; {n} personas huyen, y bajo aquel resplandor los puertos parecen juguetes.', 'A todos recuerda una llamarada de la estrella de {sistema} quién manda en el sistema: {n} personas huyen, abandonando casas y deudas, y no hay Estado que pueda detener la marcha.', 'La estrella de {sistema} arde como un puño abierto y arrasa cuanto toca; {n} personas huyen con la luz a la espalda, y la luz alcanza a muchas.'],
  ]);
  F('ev_hallazgo', [
    ['Aparece una máquina antigua en {lugar}; {estado} la recoge.', 'Una máquina antigua sale a la luz en {lugar}; {estado} se la lleva sin dar explicaciones.', 'Hay muertos en la disputa por una máquina antigua aparecida en {lugar}; {estado} se la lleva.'],
    ['Los ingenieros de {estado} empiezan a estudiar una máquina antigua hallada en {lugar}.', 'Los vecinos de {lugar} protestan: {estado} se ha quedado con una máquina antigua aparecida en su suelo.', 'En {lugar} desentierran una máquina antigua; {estado} se hace con ella por la fuerza y la disputa se salda con heridos y detenidos.'],
    ['De la roca de {lugar} emerge una máquina antigua que nadie sabe quién construyó; {estado} se la queda y sus ingenieros aprenden de ella con paciencia.', 'Sin pedir permiso, {estado} se queda con la máquina antigua que aparece en {lugar}; sus ingenieros la desmontan en silencio mientras los notables locales se quejan.', 'Al abrir una bóveda de {lugar} aparece una máquina antigua que mata a los primeros curiosos; {estado} se la queda y sus ingenieros aprenden de ella, a costa de más vidas.'],
    ['Se descubre en {lugar} una máquina de una era anterior a toda crónica; {estado} la reclama, y de su estudio nacerá una ventaja que cambiará el equilibrio del sector.', 'Para {estado}, la máquina antigua hallada en {lugar} es un golpe de suerte: se la apropia, y las demás potencias, sabiendo lo que significa, empiezan a mirar con envidia y a afilar los argumentos.', 'El hallazgo de una máquina antigua en {lugar} cuesta vidas antes de dar frutos; {estado} se la queda, y sus ingenieros, entre accidentes y duelo, aprenden de ella lo que nadie debía aprender.'],
    ['Algo despierta en {lugar}: una máquina de una edad olvidada, que llevaba eras esperando; {estado} se la queda, y sus ingenieros descubren que aún les queda mucho por aprender.', 'En {lugar} aparece una máquina que nadie construyó en esta era; {estado} se la queda y, al aprender de ella, descubre que su poder es también una deuda con quienes vendrán.', 'De las entrañas de {lugar} sale una máquina antigua, y con ella una muerte lenta para quienes la tocan; {estado} se la queda y sus ingenieros aprenden de ella, sin atender al precio.'],
  ]);
  F('ev_oleada', [
    ['Los fieles de {credo} se concentran en {n} mundos.', 'Se alzan los fieles de {credo} en {n} mundos; las autoridades dudan.', 'Hay muertos en el alzamiento de los fieles de {credo} en {n} mundos.'],
    ['Salen a la vez a las calles de {n} mundos los fieles de {credo}, que reclaman libertad para su culto.', 'El día señalado, los fieles de {credo} se alzan en {n} mundos y las guarniciones reciben orden de disolverlos.', 'Las guarniciones responden con fuego al alzamiento de los fieles de {credo} en {n} mundos; las calles se llenan de heridos.'],
    ['Al amanecer del día señalado, los fieles de {credo} abandonan a una sola voz talleres y muelles en {n} mundos, y toman las plazas sin un solo grito.', 'Con una puntualidad que asusta, los fieles de {credo} se alzan a la vez en {n} mundos; los gobernadores comprenden tarde que alguien lo había coordinado todo.', 'Disparan las guarniciones, arden los templos y el amanecer se llena de humo y de lamentos: los fieles de {credo} se han alzado en {n} mundos.'],
    ['Los anales anotan el día señalado: los fieles de {credo} se alzan a la vez en {n} mundos, y por primera vez una fe demuestra que puede mover mundos enteros a un tiempo.', 'La oleada de {credo} recorre {n} mundos en un solo día: gobiernos que se creían firmes ven a sus súbditos alzarse, y ya no saben a quién obedece su gente.', 'El alzamiento de los fieles de {credo} estalla a la vez en {n} mundos y la respuesta de los Estados es de hierro: guarniciones desplegadas, plazas tomadas y cuentas de muertos que la crónica no se atreve a cerrar.'],
    ['A la hora señalada, un solo grito sale de los fieles de {credo} y cruza {n} mundos como un trueno sin cielo; la galaxia, atónita, conoce el poder de una fe que nadie creyó posible.', 'Los poderosos descubren que habían confundido el silencio con la sumisión: los fieles de {credo} se alzan en {n} mundos y el miedo cambia de bando.', 'La galaxia entera arde en una sola noche: los fieles de {credo} se alzan a la vez en {n} mundos, se tambalean los Estados, y lo que amanece no se parece a lo que anocheció.'],
  ]);
  F('ev_martirio', [
    ['Muere {martir}; hay protestas en {n} mundos.', 'Opiniones divididas por la muerte de {martir}; protestas en {n} mundos.', 'Matan a {martir}; disturbios en {n} mundos.'],
    ['En {n} mundos se guarda luto en las plazas al conocerse la muerte de {martir}.', 'Tras la muerte de {martir}, en {n} mundos hay manifestaciones y los gobiernos se acusan entre sí de haberla provocado.', 'Cae {martir} a manos de sus enemigos y {n} mundos salen a la calle; hay cargas, piedras y heridos.'],
    ['La noticia de la muerte de {martir} viaja de puerto en puerto y {n} mundos salen a la calle en silencio, con una luz encendida en cada ventana.', 'La muerte de {martir} enciende la calle en {n} mundos; unos exigen justicia, otros venganza, y los gobiernos no saben quién hablará primero.', 'La rabia por la muerte de {martir} llena {n} mundos: se queman cuarteles, se asaltan depósitos y la sangre que se derrama ya no distingue de bandos.'],
    ['La crónica fija en la muerte de {martir} el nacimiento de un símbolo: {n} mundos guardan luto, y ese nombre será desde ahora una bandera.', 'Una mitad de {n} mundos llora la muerte de {martir} y la otra calla; ambas saben que el asunto no ha terminado.', 'El eco de la muerte de {martir} incendia {n} mundos; la calle ruge, los cuarteles responden y las páginas de la crónica se llenan de nombres de caídos.'],
    ['Se detienen a la vez {n} mundos para escuchar el silencio que deja {martir} al morir; la galaxia entiende, sin discursos, que la historia acaba de cambiar de rumbo.', 'Arranca la máscara a los poderosos la muerte de {martir} y levanta {n} mundos en una sola marea; no hay decreto que la detenga ni promesa que la calme.', 'Se apaga {martir} y la galaxia se desgarra: {n} mundos arden esa noche, y de la sangre de una sola vida brota un río que ya nadie sabrá cerrar.'],
  ]);
  F('ev_guerra_santa', [
    ['Se declara la guerra santa entre {estado} y {enemigo}, por {credo}.', 'Para los críticos, {credo} es un pretexto: {estado} declara la guerra santa a {enemigo}.', 'Ya hay muertos en la frontera: {estado} declara la guerra santa a {enemigo} en nombre de {credo}.'],
    ['{estado} proclama la guerra santa contra {enemigo} y levanta sus banderas con los símbolos de {credo}.', 'En nombre de {credo}, {estado} declara la guerra santa a {enemigo}; los comerciantes sospechan que la fe es la excusa y el botín la causa.', '{estado} lanza a sus guarniciones contra {enemigo} bajo la bandera de {credo}; la guerra santa empieza con incendios y prisioneros.'],
    ['Con ceremonia y cantos, {estado} declara la guerra santa a {enemigo} en nombre de {credo}; las flotas zarpan entre bendiciones y los muelles se llenan de familias.', 'Hasta en los puertos de {estado} hay quienes murmuran que ninguna fe pide tanta sangre, mientras se declara la guerra santa a {enemigo} en nombre de {credo}.', 'Antes de que zarpe la primera flota ya arden los barrios de los disidentes: {estado} lanza la guerra santa contra {enemigo} en nombre de {credo}.'],
    ['La crónica anota un giro: {estado} declara la guerra santa a {enemigo} en nombre de {credo}, y por primera vez una fe sirve de bandera a una flota entera.', 'Con la guerra santa proclamada contra {enemigo}, {credo} se convierte en razón de Estado en {estado}, y quienes dudan de la guerra son ya sospechosos de dudar de la fe.', 'Se abre la guerra santa: {estado} marcha contra {enemigo} en nombre de {credo}, y las primeras listas de caídos, aún sin cerrar, ya llenan los muros de los templos.'],
    ['El cielo entero se llena de estandartes: {estado} declara la guerra santa a {enemigo} en nombre de {credo}, y la galaxia, que creía haberlo visto todo, contiene el aliento.', 'Con la guerra santa que {estado} declara a {enemigo} en nombre de {credo} llega también un precio que ningún cielo repara: la fe, que unía, empieza a dividir sectores enteros.', 'Arde la galaxia en nombre de {credo}: {estado} declara la guerra santa a {enemigo}, y las flotas que zarpan cantando regresarán en pedazos o no regresarán.'],
  ]);
  F('ev_conversion', [
    ['El gobernante de {estado} abraza {credo}; pasa a ser fe oficial.', 'Se divide la corte de {estado} cuando su gobernante abraza {credo}.', 'Hay detenciones entre los disidentes tras abrazar {credo} el gobernante de {estado}.'],
    ['Quien gobierna {estado} acoge {credo} y decreta que sea la fe del Estado.', 'En {estado}, el trono adopta {credo} como fe oficial; los notables aplauden en público y se quejan en privado.', 'Tras abrazar {credo} su gobernante, {estado} impone esa fe a todos sus súbditos; los que se niegan acaban en prisión o en el destierro.'],
    ['En una ceremonia austera, quien gobierna {estado} jura {credo} ante los suyos; desde ese día, muelles, cuarteles y escuelas se rigen por su calendario y sus ritos.', 'Al volcarse en {credo}, quien manda en {estado} le da rango de fe del Estado; los viejos aliados de la corte, que no comparten esa fe, empiezan a sentirse extranjeros en su propia casa.', 'Por edicto, la fe se convierte en ley: {estado} abraza {credo} de la mano de su gobernante, y las primeras purgas en los cuarteles llegan con el primer sermón.'],
    ['La crónica asienta el día en que quien gobierna {estado} profesa {credo}: desde esa fecha, el trono y el altar caminan juntos, y {estado} cambia de rumbo.', 'La fe pasa a ser asunto de Estado en {estado}: su gobernante abraza {credo}, la nobleza se divide, la flota calla y el sector entero espera a ver quién se atreve a oponerse.', 'Una purga de disidentes acompaña la proclamación de {credo} como fe del Estado en {estado}; los edictos se publican en un día y las listas de proscritos, en otro.'],
    ['Una nueva fe sube al trono: quien gobierna {estado} toma {credo} por guía, y con ese gesto el Estado entero se inclina, como se inclinan los astros ante un sol mayor.', 'La corte aplaude, el pueblo duda: {estado} tiene ya una fe para todos, {credo}, y desde ese instante cada gesto y cada palabra serán juzgados como fidelidad o como traición.', 'Sobre {credo}, fe del gobernante de {estado}, se funda un imperio de dogma y de hierro; bajo su sombra, los disidentes aprenderán lo que cuesta pensar distinto.'],
  ]);
  F('ev_credo_nace', [
    ['En {lugar}, {fundador} predica por primera vez {credo}.', 'Las autoridades de {lugar} toman nota de que {fundador} predica {credo}.', '{fundador} predica {credo} en {lugar} y recibe una paliza a la salida.'],
    ['{fundador} empieza a predicar {credo} en {lugar}; los primeros oyentes son estibadores y cocineros.', 'A pesar de la prohibición del gobernador de {lugar}, {fundador} predica {credo}; los curiosos acuden y los guardias los anotan.', 'La guardia irrumpe en la reunión donde {fundador} predica {credo} en {lugar}; hay detenidos y un fiel muerto.'],
    ['Al caer la tarde, {fundador} sube a un contenedor del muelle de {lugar} y empieza a predicar {credo}; la gente se detiene, escucha y no se va.', 'Con la mirada puesta en los poderosos, {fundador} predica {credo} en voz alta en {lugar}; lo que dice incomoda a muchos, y los que escuchan lo hacen ya con miedo.', 'Entre hogueras y gritos, {fundador} predica {credo} en {lugar}; la primera comunidad nace entre cenizas, con sus muertos aún calientes.'],
    ['La crónica anota el origen: en {lugar}, {fundador} empieza a predicar {credo}, y lo que hoy es una fe de muchos mundos cabe todavía en una sola sala.', 'La autoridad toma por un desvarío que {fundador} empiece a predicar {credo} en {lugar}, pero el desvarío tiene ya discípulos y una forma.', 'En {lugar}, {fundador} empieza a predicar {credo}, y la respuesta de los poderosos es el hierro; los primeros fieles caen, y su sangre será el primer texto de la fe.'],
    ['En {lugar}, {fundador} alza la voz y {credo} nace de ella como nace una estrella de una nube: sin ruido, sin testigos y para siempre.', 'Los poderosos, que aún no lo saben, acaban de firmar su sentencia cuando {fundador} abre la boca en {lugar} para predicar {credo}: ninguna fe nacida de la duda se apaga con decretos.', 'La noche se llena de presagios cuando {fundador} empieza a predicar {credo} en {lugar}; la galaxia aún ignora que esa voz hará derramar más sangre de la que ha visto jamás.'],
  ]);
  F('epoca_guerra', [
    ['Las Maniobras de {clave}', 'Las Escaramuzas de {clave}', 'La Sangría de {clave}'],
    ['La Guerra de {clave}', 'La Larga Disputa de {clave}', 'La Guerra Sucia de {clave}'],
    ['Las Campañas de {clave}', 'El Cerco de {clave}', 'Los Años de Fuego de {clave}'],
    ['La Gran Guerra de {clave}', 'La Guerra de los Rencores por {clave}', 'El Incendio de {clave}'],
    ['La Guerra que Dio Forma a {clave}', 'La Guerra sin Vencedores de {clave}', 'El Crepúsculo Sangriento de {clave}'],
  ]);
  F('epoca_hambre', [
    ['Los Años Flacos', 'Los Graneros Vacíos', 'El Invierno de las Bodegas'],
    ['Los Años de Escasez', 'La Era del Racionamiento', 'Los Años del Pan Negro'],
    ['Las Cosechas Menguadas', 'Los Años de la Cola del Grano', 'Los Años de los Platos Vacíos'],
    ['La Gran Escasez', 'La Hambruna de los Depósitos Cerrados', 'La Hambruna de las Fosas Comunes'],
    ['El Gran Ayuno', 'La Era del Grano Contado', 'La Noche del Hambre Eterna'],
  ]);
  F('epoca_revuelta', [
    ['Los Años de las Asambleas', 'Los Años de los Pasquines', 'Las Calles Heridas'],
    ['Los Años de Cambio', 'La Era de los Descontentos', 'Los Años de las Barricadas'],
    ['La Primavera de los Muelles', 'El Tiempo de los Amotinados', 'Los Años de Pólvora y Pasquín'],
    ['La Gran Renovación', 'La Era de las Insurrecciones', 'Los Años de las Hogueras Rojas'],
    ['El Gran Despertar de los Mundos', 'La Marea de los Sin Nombre', 'La Noche de las Banderas Rotas'],
  ]);
  F('epoca_paz', [
    ['Los Años Quietos', 'La Calma Inquieta', 'La Paz Pagada'],
    ['Los Años Tranquilos', 'La Paz Armada', 'La Paz de los Vencidos'],
    ['Los Años de las Esclusas Abiertas', 'La Tregua Larga', 'La Paz de los Lutos'],
    ['La Larga Paz', 'La Paz Recelosa', 'La Paz sobre las Ruinas'],
    ['La Edad Dorada de los Muelles', 'La Paz de los Cuchillos Envainados', 'La Última Paz'],
  ]);
  F('epoca_peste', [
    ['Los Años de la Fiebre', 'Los Años de las Cuarentenas', 'Los Años de los Enterradores'],
    ['La Era del Contagio', 'Los Años del Aire Dudoso', 'Los Años de las Esclusas Selladas'],
    ['El Tiempo de la Fiebre Lenta', 'La Era de las Puertas con Cal', 'Los Años de las Fosas'],
    ['La Gran Fiebre', 'La Era del Miedo al Aire', 'La Gran Mortandad'],
    ['El Gran Contagio', 'La Era del Aliento Contado', 'El Reino de la Peste'],
  ]);
  F('epoca_figura', [
    ['Los Años de {clave}', 'El Pulso de {clave}', 'La Sombra de {clave}'],
    ['La Era de {clave}', 'Los Años Duros de {clave}', 'El Luto de {clave}'],
    ['El Esplendor de {clave}', 'El Largo Mando de {clave}', 'Los Años de Hierro de {clave}'],
    ['El Tiempo de {clave}', 'El Reinado de {clave}', 'La Larga Sombra de {clave}'],
    ['La Edad de {clave}', 'El Mundo según {clave}', 'El Ocaso de {clave}'],
  ]);
  F('epoca_caos', [
    ['Los Años Revueltos', 'Los Años del Desorden', 'Los Años Rotos'],
    ['La Era de la Confusión', 'El Tiempo Revuelto', 'Los Años de Sangre y Humo'],
    ['Los Años de Todo a la Vez', 'La Era de los Frentes Abiertos', 'Los Años del Naufragio'],
    ['La Gran Confusión', 'La Era de las Cuentas Pendientes', 'La Era de los Escombros'],
    ['La Tormenta de los Mundos', 'El Tiempo sin Dueño', 'El Gran Derrumbe de la Galaxia'],
  ]);
  F('con_poco_despues', [
    ['Luego,', 'Enseguida,', 'Al poco,'],
    ['Poco después,', 'No mucho más tarde,', 'Sin tiempo para el duelo,'],
    ['Muy poco después, cuando aún se hablaba de ello en los muelles,', 'Con las brasas todavía calientes,', 'Con el luto aún fresco,'],
    ['Según consignan los anales, poco después,', 'Sin que se hubiera enfriado la desconfianza,', 'Todavía sobre la sangre vertida,'],
    ['Cuando el eco aún no se había apagado,', 'Como si el destino tuviera prisa,', 'Antes de que se secasen las lágrimas,'],
  ]);
  F('con_anios_despues', [
    ['Pasaron {n} años.', '{n} años después, entre quejas,', 'Pasados {n} años, ya con pocos vivos,'],
    ['{n} años más tarde,', 'Tras {n} años de recelos,', 'Tras {n} años de pérdidas,'],
    ['Al cabo de {n} años de calma,', 'Al cabo de {n} años, con los rencores intactos,', 'Al cabo de {n} años, con el luto sin cerrar,'],
    ['Así corrieron {n} años.', 'Transcurrieron {n} años de tregua mal cosida.', 'Fueron {n} años de luto y de ceniza.'],
    ['Los años corrieron como corren los cometas, en silencio y sin retorno: fueron {n}.', 'El tiempo, lejos de curar, afiló la memoria durante {n} años.', 'Sobre las tumbas pasaron {n} años, y el olvido no llegó a cubrirlas.'],
  ]);
  F('con_giro', [
    ['Pero', 'Sin embargo,', 'Aun así,'],
    ['Y entonces', 'A pesar de todo,', 'De repente, sin aviso,'],
    ['Pero el destino, que gusta de los giros, quiso otra cosa.', 'Y sin embargo, bajo la calma aparente,', 'Pero la desgracia no avisó.'],
    ['No obstante, según consta en los anales,', 'Pero bajo la superficie,', 'Entonces, sin previo aviso, todo se torció.'],
    ['Mas la historia, que nunca se queda quieta, tenía otros planes.', 'Y el tiempo, que todo lo desanuda, empezó a deshacer lo hecho.', 'Hasta que cayó sobre todos la sombra que nadie quiso ver llegar.'],
  ]);
})(typeof globalThis !== 'undefined' ? globalThis : this);
